// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clan_pb/clan_search.ext.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3ClanMemberShow;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PB3ClanSearchExtRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PB3ClanSearchExtRoot : GPBRootObject
@end

#pragma mark - PB3SearchClanMemberReq

typedef GPB_ENUM(PB3SearchClanMemberReq_FieldNumber) {
  PB3SearchClanMemberReq_FieldNumber_PlayerId = 1,
};

/**
 * 根据ID搜索公会成员信息
 **/
@interface PB3SearchClanMemberReq : GPBMessage

/** 用户Id */
@property(nonatomic, readwrite) int64_t playerId;

@end

#pragma mark - PB3SearchClanMemberRes

typedef GPB_ENUM(PB3SearchClanMemberRes_FieldNumber) {
  PB3SearchClanMemberRes_FieldNumber_PlayerId = 1,
  PB3SearchClanMemberRes_FieldNumber_NickName = 2,
  PB3SearchClanMemberRes_FieldNumber_Icon = 3,
  PB3SearchClanMemberRes_FieldNumber_CharmLev = 4,
  PB3SearchClanMemberRes_FieldNumber_WealthLev = 5,
  PB3SearchClanMemberRes_FieldNumber_ShortId = 6,
};

@interface PB3SearchClanMemberRes : GPBMessage

/** 用户Id */
@property(nonatomic, readwrite) int64_t playerId;

/** 用户名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/** 用户头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 魅力等级 */
@property(nonatomic, readwrite) int64_t charmLev;

/** 财富等级 */
@property(nonatomic, readwrite) int64_t wealthLev;

/** 短号 */
@property(nonatomic, readwrite) int64_t shortId;

@end

#pragma mark - PB3ClanMemberShowListReq

typedef GPB_ENUM(PB3ClanMemberShowListReq_FieldNumber) {
  PB3ClanMemberShowListReq_FieldNumber_Page = 1,
  PB3ClanMemberShowListReq_FieldNumber_PageSize = 2,
};

/**
 * 表演模式公会成员列表
 **/
@interface PB3ClanMemberShowListReq : GPBMessage

/** 页数，从1开始 */
@property(nonatomic, readwrite) int32_t page;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - PB3ClanMemberShowListRes

typedef GPB_ENUM(PB3ClanMemberShowListRes_FieldNumber) {
  PB3ClanMemberShowListRes_FieldNumber_ListArray = 1,
};

@interface PB3ClanMemberShowListRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3ClanMemberShow*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PB3ClanMemberShow

typedef GPB_ENUM(PB3ClanMemberShow_FieldNumber) {
  PB3ClanMemberShow_FieldNumber_Id_p = 1,
  PB3ClanMemberShow_FieldNumber_Id2 = 2,
  PB3ClanMemberShow_FieldNumber_Name = 3,
  PB3ClanMemberShow_FieldNumber_Icon = 4,
  PB3ClanMemberShow_FieldNumber_WealthLev = 5,
  PB3ClanMemberShow_FieldNumber_CharmLev = 6,
};

@interface PB3ClanMemberShow : GPBMessage

/** playerId */
@property(nonatomic, readwrite) int64_t id_p;

/** 靓号 */
@property(nonatomic, readwrite) int64_t id2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 财富等级 */
@property(nonatomic, readwrite) int32_t wealthLev;

/** 魅力等级 */
@property(nonatomic, readwrite) int32_t charmLev;

@end

#pragma mark - PB3GetRandomClanRoomReq

@interface PB3GetRandomClanRoomReq : GPBMessage

@end

#pragma mark - PB3GetRandomClanRoomRes

typedef GPB_ENUM(PB3GetRandomClanRoomRes_FieldNumber) {
  PB3GetRandomClanRoomRes_FieldNumber_RoomId = 1,
};

@interface PB3GetRandomClanRoomRes : GPBMessage

@property(nonatomic, readwrite) int64_t roomId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
