// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/acm_conf.ext.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3CfgUserId2RandomScheme;
@class PB3ConfActPage;
@class PB3CouponGainRule;
@class PB3CouponIssueRule;
@class PB3MobaTeamGameMemberCfg;
@class PB3MobaTeamGameSettingCfg;
@class PB3MobaTeamGameSettingData;
@class PB3RoomShopDecorateItem;
@class PB3SolitaireEatPut;
@class PB3SolitaireRate;
@class PB3SolitaireScheme;
@class PB3SolitaireTips;
@class PB3XcmGiftSkinCfg;
@class PB3XcmGiftSkinStoreCfg;
@class PB3XcmOfficialExamPassMemberCfg;
@class PB3XcmRoomPatternCliCfg;
GPB_ENUM_FWD_DECLARE(PB3CouponDiscountType);
GPB_ENUM_FWD_DECLARE(PB3CouponJumpType);
GPB_ENUM_FWD_DECLARE(PB3CouponPackageType);
GPB_ENUM_FWD_DECLARE(PB3CouponStatus);
GPB_ENUM_FWD_DECLARE(PB3DecorateType);
GPB_ENUM_FWD_DECLARE(PB3IntimateFansTargetType);
GPB_ENUM_FWD_DECLARE(PB3NewRoomPattern);
GPB_ENUM_FWD_DECLARE(PB3SubInfoActivityType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB3IMInteractionType

typedef GPB_ENUM(PB3IMInteractionType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3IMInteractionType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3IMInteractionType_ImitZero = 0,

  /** 撩TA */
  PB3IMInteractionType_ImitTeaseTa = 1,

  /** 真心话 */
  PB3IMInteractionType_ImitSincereWord = 2,

  /** 8分钟恋爱体验 */
  PB3IMInteractionType_ImitChatCp = 3,
};

GPBEnumDescriptor *PB3IMInteractionType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3IMInteractionType_IsValidValue(int32_t value);

#pragma mark - Enum PB3MobaTeamGameSettingType

/** 开黑组队游戏设置数据 */
typedef GPB_ENUM(PB3MobaTeamGameSettingType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3MobaTeamGameSettingType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3MobaTeamGameSettingType_MtgstNone = 0,
};

GPBEnumDescriptor *PB3MobaTeamGameSettingType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3MobaTeamGameSettingType_IsValidValue(int32_t value);

#pragma mark - Enum PB3MobaTeamGameSettingDataType

/** 开黑组队游戏设置数据类型 */
typedef GPB_ENUM(PB3MobaTeamGameSettingDataType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3MobaTeamGameSettingDataType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3MobaTeamGameSettingDataType_MtgsdtNone = 0,

  /** 下拉选项 */
  PB3MobaTeamGameSettingDataType_MtgsdtOptions = 1,

  /** 输入数值 */
  PB3MobaTeamGameSettingDataType_MtgsdtInputNum = 2,

  /** 输入数值范围 */
  PB3MobaTeamGameSettingDataType_MtgsdtInputNumRange = 3,
};

GPBEnumDescriptor *PB3MobaTeamGameSettingDataType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3MobaTeamGameSettingDataType_IsValidValue(int32_t value);

#pragma mark - Enum PB3MobaTeamGameType

/** 开黑组队游戏类型 */
typedef GPB_ENUM(PB3MobaTeamGameType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3MobaTeamGameType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3MobaTeamGameType_MtgtNone = 0,

  /** 王者荣耀 */
  PB3MobaTeamGameType_MtgtKingHonor = 1,

  /** 英雄联盟手游 */
  PB3MobaTeamGameType_MtgtLolm = 2,

  /** 和平精英 */
  PB3MobaTeamGameType_MtgtGameForPeace = 3,

  /** 金铲铲之战 */
  PB3MobaTeamGameType_MtgtJcc = 4,
};

GPBEnumDescriptor *PB3MobaTeamGameType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3MobaTeamGameType_IsValidValue(int32_t value);

#pragma mark - Enum PB3FirstPayGiftRewardType

/** 首充有礼奖励类型 */
typedef GPB_ENUM(PB3FirstPayGiftRewardType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3FirstPayGiftRewardType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3FirstPayGiftRewardType_FpgrtNone = 0,

  /** 礼物 */
  PB3FirstPayGiftRewardType_FpgrtGift = 1,

  /** 特效 */
  PB3FirstPayGiftRewardType_FpgrtEffect = 2,

  /** 爵位 */
  PB3FirstPayGiftRewardType_FpgrtNobility = 3,
};

GPBEnumDescriptor *PB3FirstPayGiftRewardType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3FirstPayGiftRewardType_IsValidValue(int32_t value);

#pragma mark - Enum PB3FirstPayGiftBoxType

/** 首充有礼宝盒类型 */
typedef GPB_ENUM(PB3FirstPayGiftBoxType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3FirstPayGiftBoxType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3FirstPayGiftBoxType_FpgbtNone = 0,

  /** 初级宝箱 */
  PB3FirstPayGiftBoxType_FpgbtBase = 1,

  /** 中级 */
  PB3FirstPayGiftBoxType_FpgbtMiddle = 2,

  /** 高级 */
  PB3FirstPayGiftBoxType_FpgbtBest = 3,
};

GPBEnumDescriptor *PB3FirstPayGiftBoxType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3FirstPayGiftBoxType_IsValidValue(int32_t value);

#pragma mark - Enum PB3FirstPayGiftRewardLimitType

/** 首充有礼宝盒奖励数量限定类型 */
typedef GPB_ENUM(PB3FirstPayGiftRewardLimitType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3FirstPayGiftRewardLimitType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 无限制 */
  PB3FirstPayGiftRewardLimitType_FpgrltNone = 0,

  /** 每日限定数量 */
  PB3FirstPayGiftRewardLimitType_FpgrltDaily = 1,
};

GPBEnumDescriptor *PB3FirstPayGiftRewardLimitType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3FirstPayGiftRewardLimitType_IsValidValue(int32_t value);

#pragma mark - Enum PB3LogicRelationshipType

/** 逻辑关系类型 */
typedef GPB_ENUM(PB3LogicRelationshipType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3LogicRelationshipType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3LogicRelationshipType_LrtNone = 0,

  /** 或 */
  PB3LogicRelationshipType_LrtOr = 1,

  /** 与 */
  PB3LogicRelationshipType_LrtAnd = 2,
};

GPBEnumDescriptor *PB3LogicRelationshipType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3LogicRelationshipType_IsValidValue(int32_t value);

#pragma mark - Enum PB3CouponLimitType

typedef GPB_ENUM(PB3CouponLimitType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3CouponLimitType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3CouponLimitType_CltNone = 0,

  /** 账号 */
  PB3CouponLimitType_CltAccount = 1,

  /** 设备号 */
  PB3CouponLimitType_CltDevice = 2,
};

GPBEnumDescriptor *PB3CouponLimitType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3CouponLimitType_IsValidValue(int32_t value);

#pragma mark - Enum PB3CouponEffectType

typedef GPB_ENUM(PB3CouponEffectType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3CouponEffectType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3CouponEffectType_CetNone = 0,

  /** 固定日期 */
  PB3CouponEffectType_CetFixDate = 1,

  /** 领取后 */
  PB3CouponEffectType_CetGet = 2,
};

GPBEnumDescriptor *PB3CouponEffectType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3CouponEffectType_IsValidValue(int32_t value);

#pragma mark - Enum PB3SolitaireTarget

typedef GPB_ENUM(PB3SolitaireTarget) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3SolitaireTarget_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3SolitaireTarget_SottZero = 0,

  /** 用户投入 */
  PB3SolitaireTarget_SottUser = 1,

  /** 奖池初始值 */
  PB3SolitaireTarget_SottPrizePoolInit = 2,
};

GPBEnumDescriptor *PB3SolitaireTarget_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3SolitaireTarget_IsValidValue(int32_t value);

#pragma mark - Enum PB3SolitaireEatPutType

typedef GPB_ENUM(PB3SolitaireEatPutType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3SolitaireEatPutType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3SolitaireEatPutType_SoteapZero = 0,

  /** 吃 */
  PB3SolitaireEatPutType_SoteapEat = 1,

  /** 放 */
  PB3SolitaireEatPutType_SoteapPut = 2,
};

GPBEnumDescriptor *PB3SolitaireEatPutType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3SolitaireEatPutType_IsValidValue(int32_t value);

#pragma mark - Enum PB3SolitaireSchemeType

/** 方案类型 */
typedef GPB_ENUM(PB3SolitaireSchemeType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3SolitaireSchemeType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3SolitaireSchemeType_SotstZero = 0,

  /** 常规 */
  PB3SolitaireSchemeType_SotstNormal = 1,

  /** 吃分线 */
  PB3SolitaireSchemeType_SotstEat = 2,

  /** 放分线 */
  PB3SolitaireSchemeType_SotstPut = 3,
};

GPBEnumDescriptor *PB3SolitaireSchemeType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3SolitaireSchemeType_IsValidValue(int32_t value);

#pragma mark - Enum PB3SolitaireTimeType

typedef GPB_ENUM(PB3SolitaireTimeType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3SolitaireTimeType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB3SolitaireTimeType_SotttZero = 0,

  /** 持续时间段 */
  PB3SolitaireTimeType_SotttTimeSlot = 1,

  /** 每日定时 */
  PB3SolitaireTimeType_SotttEveryday = 2,
};

GPBEnumDescriptor *PB3SolitaireTimeType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3SolitaireTimeType_IsValidValue(int32_t value);

#pragma mark - Enum PB3XcmKickOutRoomType

typedef GPB_ENUM(PB3XcmKickOutRoomType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3XcmKickOutRoomType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 无限 */
  PB3XcmKickOutRoomType_XkortNone = 0,

  /** 秒 */
  PB3XcmKickOutRoomType_XkortSecond = 1,

  /** 分 */
  PB3XcmKickOutRoomType_XkortMinute = 60,

  /** 小时 */
  PB3XcmKickOutRoomType_XkortHour = 3600,

  /** 天 */
  PB3XcmKickOutRoomType_XkortDay = 86400,
};

GPBEnumDescriptor *PB3XcmKickOutRoomType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3XcmKickOutRoomType_IsValidValue(int32_t value);

#pragma mark - Enum PB3GiftSkinStoreShowType

typedef GPB_ENUM(PB3GiftSkinStoreShowType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3GiftSkinStoreShowType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占用 */
  PB3GiftSkinStoreShowType_GsstNone = 0,

  /** 永久 */
  PB3GiftSkinStoreShowType_GsstForever = 1,

  /** 时段 */
  PB3GiftSkinStoreShowType_GsstTime = 2,
};

GPBEnumDescriptor *PB3GiftSkinStoreShowType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3GiftSkinStoreShowType_IsValidValue(int32_t value);

#pragma mark - Enum PB3GiftSkinStoreDisplayType

typedef GPB_ENUM(PB3GiftSkinStoreDisplayType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3GiftSkinStoreDisplayType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占用 */
  PB3GiftSkinStoreDisplayType_GssdtNone = 0,

  /** 白名单 */
  PB3GiftSkinStoreDisplayType_GssdtWhiteList = 1,

  /** 固定显示 */
  PB3GiftSkinStoreDisplayType_GssdtFixDisplay = 2,

  /** 固定不显示 */
  PB3GiftSkinStoreDisplayType_GssdtFixHidden = 3,
};

GPBEnumDescriptor *PB3GiftSkinStoreDisplayType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3GiftSkinStoreDisplayType_IsValidValue(int32_t value);

#pragma mark - Enum PB3GiftSkinStoreTimeType

typedef GPB_ENUM(PB3GiftSkinStoreTimeType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3GiftSkinStoreTimeType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占用 */
  PB3GiftSkinStoreTimeType_GsttNone = 0,

  /** 天 */
  PB3GiftSkinStoreTimeType_GsttDay = 1,

  /** 时 */
  PB3GiftSkinStoreTimeType_GsttHour = 2,

  /** 分 */
  PB3GiftSkinStoreTimeType_GsttMin = 3,
};

GPBEnumDescriptor *PB3GiftSkinStoreTimeType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3GiftSkinStoreTimeType_IsValidValue(int32_t value);

#pragma mark - Enum PB3GiftSkinStoreSoldType

typedef GPB_ENUM(PB3GiftSkinStoreSoldType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3GiftSkinStoreSoldType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占用 */
  PB3GiftSkinStoreSoldType_GssttNone = 0,

  /** 永久 */
  PB3GiftSkinStoreSoldType_GssttForever = 1,

  /** 增加时长 */
  PB3GiftSkinStoreSoldType_GssttAddTime = 2,
};

GPBEnumDescriptor *PB3GiftSkinStoreSoldType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3GiftSkinStoreSoldType_IsValidValue(int32_t value);

#pragma mark - PB3AcmConfExtRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PB3AcmConfExtRoot : GPBRootObject
@end

#pragma mark - PB3IMInteractionConfList

typedef GPB_ENUM(PB3IMInteractionConfList_FieldNumber) {
  PB3IMInteractionConfList_FieldNumber_Type = 1,
  PB3IMInteractionConfList_FieldNumber_Gold = 2,
  PB3IMInteractionConfList_FieldNumber_BtnText = 3,
  PB3IMInteractionConfList_FieldNumber_BtnIcon = 4,
  PB3IMInteractionConfList_FieldNumber_Content = 5,
  PB3IMInteractionConfList_FieldNumber_GiftId = 6,
  PB3IMInteractionConfList_FieldNumber_Icon = 7,
  PB3IMInteractionConfList_FieldNumber_TypeName = 8,
  PB3IMInteractionConfList_FieldNumber_TagIcon = 9,
};

@interface PB3IMInteractionConfList : GPBMessage

/** 互动类型 */
@property(nonatomic, readwrite) PB3IMInteractionType type;

/** 金币数 */
@property(nonatomic, readwrite) int32_t gold;

/** 按钮文案 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *btnText;

/** 按钮图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *btnIcon;

/** 说明文案 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 礼物ID */
@property(nonatomic, readwrite) int32_t giftId;

/** 显示图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 类型名称:撩TA、真心话、8分钟恋爱体验 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeName;

/** 标签 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tagIcon;

@end

/**
 * Fetches the raw value of a @c PB3IMInteractionConfList's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3IMInteractionConfList_Type_RawValue(PB3IMInteractionConfList *message);
/**
 * Sets the raw value of an @c PB3IMInteractionConfList's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3IMInteractionConfList_Type_RawValue(PB3IMInteractionConfList *message, int32_t value);

#pragma mark - PB3IMVideoBtnConfList

typedef GPB_ENUM(PB3IMVideoBtnConfList_FieldNumber) {
  PB3IMVideoBtnConfList_FieldNumber_BtnType = 1,
  PB3IMVideoBtnConfList_FieldNumber_BtnOnOff = 2,
  PB3IMVideoBtnConfList_FieldNumber_BtnTitle = 3,
  PB3IMVideoBtnConfList_FieldNumber_BtnText = 4,
  PB3IMVideoBtnConfList_FieldNumber_BtnDesc = 5,
  PB3IMVideoBtnConfList_FieldNumber_ImIcon = 6,
};

@interface PB3IMVideoBtnConfList : GPBMessage

/** 按钮类型 */
@property(nonatomic, readwrite) int32_t btnType;

/** 按钮开关 */
@property(nonatomic, readwrite) BOOL btnOnOff;

/** 按钮标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *btnTitle;

/** 按钮文案 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *btnText;

/** 按钮说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *btnDesc;

/** 按钮图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imIcon;

@end

#pragma mark - PB3RoomAllDecorateItem

typedef GPB_ENUM(PB3RoomAllDecorateItem_FieldNumber) {
  PB3RoomAllDecorateItem_FieldNumber_DecorateId = 1,
  PB3RoomAllDecorateItem_FieldNumber_DecorateType = 2,
  PB3RoomAllDecorateItem_FieldNumber_CanBuy = 3,
  PB3RoomAllDecorateItem_FieldNumber_Name = 4,
  PB3RoomAllDecorateItem_FieldNumber_BgURL = 5,
  PB3RoomAllDecorateItem_FieldNumber_SmallBgURL = 6,
  PB3RoomAllDecorateItem_FieldNumber_PcURL = 7,
  PB3RoomAllDecorateItem_FieldNumber_SmallPcURL = 8,
  PB3RoomAllDecorateItem_FieldNumber_RightSignString = 9,
  PB3RoomAllDecorateItem_FieldNumber_Describe = 10,
  PB3RoomAllDecorateItem_FieldNumber_RemainTime = 11,
  PB3RoomAllDecorateItem_FieldNumber_IsUse = 12,
  PB3RoomAllDecorateItem_FieldNumber_ShopItemArray = 13,
  PB3RoomAllDecorateItem_FieldNumber_Weight = 14,
  PB3RoomAllDecorateItem_FieldNumber_IsBelong = 15,
  PB3RoomAllDecorateItem_FieldNumber_RoomTypeArray = 16,
  PB3RoomAllDecorateItem_FieldNumber_ShelterURL = 17,
  PB3RoomAllDecorateItem_FieldNumber_PcShelterURL = 18,
  PB3RoomAllDecorateItem_FieldNumber_StretchableURL = 19,
  PB3RoomAllDecorateItem_FieldNumber_IsOffShelf = 20,
  PB3RoomAllDecorateItem_FieldNumber_RoomPatternArray = 21,
  PB3RoomAllDecorateItem_FieldNumber_BgVideoURL = 22,
  PB3RoomAllDecorateItem_FieldNumber_BgVideoPcURL = 23,
};

/**
 * 房间装饰
 **/
@interface PB3RoomAllDecorateItem : GPBMessage

@property(nonatomic, readwrite) int64_t decorateId;

@property(nonatomic, readwrite) enum PB3DecorateType decorateType;

@property(nonatomic, readwrite) BOOL canBuy;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bgURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *smallBgURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pcURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *smallPcURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rightSignString;

@property(nonatomic, readwrite, copy, null_resettable) NSString *describe;

/** -1 无限时 */
@property(nonatomic, readwrite) int64_t remainTime;

/** 是否在使用 */
@property(nonatomic, readwrite) BOOL isUse;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3RoomShopDecorateItem*> *shopItemArray;
/** The number of items in @c shopItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger shopItemArray_Count;

@property(nonatomic, readwrite) int32_t weight;

/** 是否专属 */
@property(nonatomic, readwrite) BOOL isBelong;

/** 房间类型 */
// |roomTypeArray| contains |PB3RoomFlagType|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *roomTypeArray;
/** The number of items in @c roomTypeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger roomTypeArray_Count;

/** 方形庇护图片地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shelterURL;

/** 方形庇护PC图片地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pcShelterURL;

/** 拉伸图地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stretchableURL;

/** 是否装饰下架 */
@property(nonatomic, readwrite) BOOL isOffShelf;

/** 房间模式 */
// |roomPatternArray| contains |PB3NewRoomPattern|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *roomPatternArray;
/** The number of items in @c roomPatternArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger roomPatternArray_Count;

/** 客户端动态背景URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bgVideoURL;

/** pc端动态背景URL */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bgVideoPcURL;

@end

/**
 * Fetches the raw value of a @c PB3RoomAllDecorateItem's @c decorateType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3RoomAllDecorateItem_DecorateType_RawValue(PB3RoomAllDecorateItem *message);
/**
 * Sets the raw value of an @c PB3RoomAllDecorateItem's @c decorateType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3RoomAllDecorateItem_DecorateType_RawValue(PB3RoomAllDecorateItem *message, int32_t value);

#pragma mark - PB3RoomShopDecorateItem

typedef GPB_ENUM(PB3RoomShopDecorateItem_FieldNumber) {
  PB3RoomShopDecorateItem_FieldNumber_ShopId = 1,
  PB3RoomShopDecorateItem_FieldNumber_Num = 2,
  PB3RoomShopDecorateItem_FieldNumber_Price = 3,
  PB3RoomShopDecorateItem_FieldNumber_Unit = 4,
  PB3RoomShopDecorateItem_FieldNumber_Pic = 5,
  PB3RoomShopDecorateItem_FieldNumber_PcPic = 6,
  PB3RoomShopDecorateItem_FieldNumber_Weight = 7,
  PB3RoomShopDecorateItem_FieldNumber_IsOffShelf = 8,
};

@interface PB3RoomShopDecorateItem : GPBMessage

@property(nonatomic, readwrite) int64_t shopId;

@property(nonatomic, readwrite) int32_t num;

@property(nonatomic, readwrite) int32_t price;

/** 单位 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *unit;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pcPic;

@property(nonatomic, readwrite) int32_t weight;

/** 是否商品下架 */
@property(nonatomic, readwrite) BOOL isOffShelf;

@end

#pragma mark - PB3MobaTeamGameSettingData

typedef GPB_ENUM(PB3MobaTeamGameSettingData_FieldNumber) {
  PB3MobaTeamGameSettingData_FieldNumber_DataId = 1,
  PB3MobaTeamGameSettingData_FieldNumber_DataName = 2,
};

/**
 * 开黑组队游戏设置数据
 **/
@interface PB3MobaTeamGameSettingData : GPBMessage

/** 设置数据id */
@property(nonatomic, readwrite) int64_t dataId;

/** 设置数据名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *dataName;

@end

#pragma mark - PB3MobaTeamGameSettingCfg

typedef GPB_ENUM(PB3MobaTeamGameSettingCfg_FieldNumber) {
  PB3MobaTeamGameSettingCfg_FieldNumber_SettingId = 1,
  PB3MobaTeamGameSettingCfg_FieldNumber_SettingType = 2,
  PB3MobaTeamGameSettingCfg_FieldNumber_SettingName = 3,
  PB3MobaTeamGameSettingCfg_FieldNumber_SettingDataType = 4,
  PB3MobaTeamGameSettingCfg_FieldNumber_SettingDataArray = 5,
  PB3MobaTeamGameSettingCfg_FieldNumber_SettingSort = 6,
  PB3MobaTeamGameSettingCfg_FieldNumber_DataDefault = 7,
};

/**
 * 开黑组队游戏设置配置
 **/
@interface PB3MobaTeamGameSettingCfg : GPBMessage

/** 设置id */
@property(nonatomic, readwrite) int64_t settingId;

/** 设置类型 */
@property(nonatomic, readwrite) PB3MobaTeamGameSettingType settingType;

/** 设置名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *settingName;

/** 设置数据类型 */
@property(nonatomic, readwrite) PB3MobaTeamGameSettingDataType settingDataType;

/** 设置数据 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3MobaTeamGameSettingData*> *settingDataArray;
/** The number of items in @c settingDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger settingDataArray_Count;

/** 设置排序 */
@property(nonatomic, readwrite) int64_t settingSort;

/** 默认信息ID */
@property(nonatomic, readwrite) int64_t dataDefault;

@end

/**
 * Fetches the raw value of a @c PB3MobaTeamGameSettingCfg's @c settingType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3MobaTeamGameSettingCfg_SettingType_RawValue(PB3MobaTeamGameSettingCfg *message);
/**
 * Sets the raw value of an @c PB3MobaTeamGameSettingCfg's @c settingType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3MobaTeamGameSettingCfg_SettingType_RawValue(PB3MobaTeamGameSettingCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3MobaTeamGameSettingCfg's @c settingDataType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3MobaTeamGameSettingCfg_SettingDataType_RawValue(PB3MobaTeamGameSettingCfg *message);
/**
 * Sets the raw value of an @c PB3MobaTeamGameSettingCfg's @c settingDataType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3MobaTeamGameSettingCfg_SettingDataType_RawValue(PB3MobaTeamGameSettingCfg *message, int32_t value);

#pragma mark - PB3MobaTeamGameMemberCfg

typedef GPB_ENUM(PB3MobaTeamGameMemberCfg_FieldNumber) {
  PB3MobaTeamGameMemberCfg_FieldNumber_DefaultMemberNum = 1,
  PB3MobaTeamGameMemberCfg_FieldNumber_MinMemberNum = 2,
  PB3MobaTeamGameMemberCfg_FieldNumber_MaxMemberNum = 3,
};

/**
 * 开黑组队信息排位人数
 **/
@interface PB3MobaTeamGameMemberCfg : GPBMessage

/** 默认人数 */
@property(nonatomic, readwrite) int64_t defaultMemberNum;

/** 最小人数 */
@property(nonatomic, readwrite) int64_t minMemberNum;

/** 最大人数 */
@property(nonatomic, readwrite) int64_t maxMemberNum;

@end

#pragma mark - PB3MobaTeamGameCfg

typedef GPB_ENUM(PB3MobaTeamGameCfg_FieldNumber) {
  PB3MobaTeamGameCfg_FieldNumber_GameId = 1,
  PB3MobaTeamGameCfg_FieldNumber_Name = 2,
  PB3MobaTeamGameCfg_FieldNumber_SettingsArray = 3,
  PB3MobaTeamGameCfg_FieldNumber_GameSort = 4,
  PB3MobaTeamGameCfg_FieldNumber_GameIcon = 5,
  PB3MobaTeamGameCfg_FieldNumber_GameIconRoom = 6,
  PB3MobaTeamGameCfg_FieldNumber_GameBgRoom = 7,
  PB3MobaTeamGameCfg_FieldNumber_GameFrameBro = 8,
  PB3MobaTeamGameCfg_FieldNumber_GameBgBro = 9,
  PB3MobaTeamGameCfg_FieldNumber_GameFrameColor = 10,
  PB3MobaTeamGameCfg_FieldNumber_MemberCfg = 11,
  PB3MobaTeamGameCfg_FieldNumber_DefaultDemandDesc = 12,
  PB3MobaTeamGameCfg_FieldNumber_GameBgBroPc = 13,
  PB3MobaTeamGameCfg_FieldNumber_DemandDescListArray = 14,
  PB3MobaTeamGameCfg_FieldNumber_GameType = 15,
  PB3MobaTeamGameCfg_FieldNumber_AdOpenGameLink = 16,
  PB3MobaTeamGameCfg_FieldNumber_GameNameBgColorStart = 17,
  PB3MobaTeamGameCfg_FieldNumber_GameNameBgColorEnd = 18,
};

/**
 * 服务端生成配置使用
 **/
@interface PB3MobaTeamGameCfg : GPBMessage

/** 游戏id */
@property(nonatomic, readwrite) int64_t gameId;

/** 游戏名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 设置列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3MobaTeamGameSettingCfg*> *settingsArray;
/** The number of items in @c settingsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger settingsArray_Count;

/** 游戏排序 */
@property(nonatomic, readwrite) int64_t gameSort;

/** 游戏图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameIcon;

/** 房间样式图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameIconRoom;

/** 房间样式背景图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameBgRoom;

/** 开黑广播边框图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameFrameBro;

/** 开黑广播(世界广播)背景图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameBgBro;

/** 世界广播-边框颜色 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameFrameColor;

/** 排位人数配置 */
@property(nonatomic, readwrite, strong, null_resettable) PB3MobaTeamGameMemberCfg *memberCfg;
/** Test to see if @c memberCfg has been set. */
@property(nonatomic, readwrite) BOOL hasMemberCfg;

/** 默认组队要求 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultDemandDesc;

/** pc开黑广播(世界广播)背景图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameBgBroPc;

/** 组队要求列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *demandDescListArray;
/** The number of items in @c demandDescListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger demandDescListArray_Count;

/** 游戏类型枚举 */
@property(nonatomic, readwrite) PB3MobaTeamGameType gameType;

/** 安卓打开游戏链接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *adOpenGameLink;

/** 游戏名称背景开始颜色 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameNameBgColorStart;

/** 游戏名称背景结束颜色 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameNameBgColorEnd;

@end

/**
 * Fetches the raw value of a @c PB3MobaTeamGameCfg's @c gameType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3MobaTeamGameCfg_GameType_RawValue(PB3MobaTeamGameCfg *message);
/**
 * Sets the raw value of an @c PB3MobaTeamGameCfg's @c gameType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3MobaTeamGameCfg_GameType_RawValue(PB3MobaTeamGameCfg *message, int32_t value);

#pragma mark - PB3XcmFirstPayGiftBaseCfg

typedef GPB_ENUM(PB3XcmFirstPayGiftBaseCfg_FieldNumber) {
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_MostValueDesc = 1,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_MostValueURL = 2,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_MostValueH5URL = 3,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_WindowStay = 4,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_WindowPopupTimes = 5,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_WealthLev = 6,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_CharmLev = 7,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_LevRelationship = 8,
  PB3XcmFirstPayGiftBaseCfg_FieldNumber_WindowJumpURL = 9,
};

/**
 * 首充有礼基础配置
 **/
@interface PB3XcmFirstPayGiftBaseCfg : GPBMessage

/** 最高奖励描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mostValueDesc;

/** 最高奖励url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mostValueURL;

/** H5最高奖励url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mostValueH5URL;

/** 用户在房间停留X秒后弹出提示，0则不弹出 */
@property(nonatomic, readwrite) int32_t windowStay;

/** 每日弹窗上限次数 */
@property(nonatomic, readwrite) int32_t windowPopupTimes;

/** 财富等级 */
@property(nonatomic, readwrite) int32_t wealthLev;

/** 魅力等级 */
@property(nonatomic, readwrite) int32_t charmLev;

/** 等级逻辑关系 */
@property(nonatomic, readwrite) PB3LogicRelationshipType levRelationship;

/** 房间弹窗跳转url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *windowJumpURL;

@end

/**
 * Fetches the raw value of a @c PB3XcmFirstPayGiftBaseCfg's @c levRelationship property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmFirstPayGiftBaseCfg_LevRelationship_RawValue(PB3XcmFirstPayGiftBaseCfg *message);
/**
 * Sets the raw value of an @c PB3XcmFirstPayGiftBaseCfg's @c levRelationship property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmFirstPayGiftBaseCfg_LevRelationship_RawValue(PB3XcmFirstPayGiftBaseCfg *message, int32_t value);

#pragma mark - PB3XcmFirstPayGiftRewardCfg

typedef GPB_ENUM(PB3XcmFirstPayGiftRewardCfg_FieldNumber) {
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_Id_p = 1,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_RewardId = 2,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_RewardType = 3,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_ExpiredTime = 4,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_LimitType = 5,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_LimitNum = 6,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_BoxType = 7,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_BoxSort = 8,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_RewardNum = 9,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_RewardUnit = 10,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_IsWorth = 11,
  PB3XcmFirstPayGiftRewardCfg_FieldNumber_Weight = 12,
};

/**
 * 首充有礼奖励配置
 **/
@interface PB3XcmFirstPayGiftRewardCfg : GPBMessage

/** 配置id */
@property(nonatomic, readwrite) int64_t id_p;

/** 奖励id */
@property(nonatomic, readwrite) int64_t rewardId;

/** 奖励类型 */
@property(nonatomic, readwrite) PB3FirstPayGiftRewardType rewardType;

/** 有效时长（秒） */
@property(nonatomic, readwrite) int64_t expiredTime;

/** 奖励数量限定类型 */
@property(nonatomic, readwrite) PB3FirstPayGiftRewardLimitType limitType;

/** 限定数量 */
@property(nonatomic, readwrite) int64_t limitNum;

/** 宝箱类型 */
@property(nonatomic, readwrite) PB3FirstPayGiftBoxType boxType;

/** 宝箱类型内排序 */
@property(nonatomic, readwrite) int32_t boxSort;

/** 奖励数量 */
@property(nonatomic, readwrite) int32_t rewardNum;

/** 奖励单位 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rewardUnit;

/** 是否限定奖励 */
@property(nonatomic, readwrite) BOOL isWorth;

/** 权重 */
@property(nonatomic, readwrite) int64_t weight;

@end

/**
 * Fetches the raw value of a @c PB3XcmFirstPayGiftRewardCfg's @c rewardType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmFirstPayGiftRewardCfg_RewardType_RawValue(PB3XcmFirstPayGiftRewardCfg *message);
/**
 * Sets the raw value of an @c PB3XcmFirstPayGiftRewardCfg's @c rewardType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmFirstPayGiftRewardCfg_RewardType_RawValue(PB3XcmFirstPayGiftRewardCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3XcmFirstPayGiftRewardCfg's @c limitType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmFirstPayGiftRewardCfg_LimitType_RawValue(PB3XcmFirstPayGiftRewardCfg *message);
/**
 * Sets the raw value of an @c PB3XcmFirstPayGiftRewardCfg's @c limitType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmFirstPayGiftRewardCfg_LimitType_RawValue(PB3XcmFirstPayGiftRewardCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3XcmFirstPayGiftRewardCfg's @c boxType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmFirstPayGiftRewardCfg_BoxType_RawValue(PB3XcmFirstPayGiftRewardCfg *message);
/**
 * Sets the raw value of an @c PB3XcmFirstPayGiftRewardCfg's @c boxType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmFirstPayGiftRewardCfg_BoxType_RawValue(PB3XcmFirstPayGiftRewardCfg *message, int32_t value);

#pragma mark - PB3CPTips

typedef GPB_ENUM(PB3CPTips_FieldNumber) {
  PB3CPTips_FieldNumber_TipsBossArray = 1,
  PB3CPTips_FieldNumber_TipsPwArray = 2,
};

/**
 * 处CP通话界面的tips
 **/
@interface PB3CPTips : GPBMessage

/** 提示文案-老板侧 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tipsBossArray;
/** The number of items in @c tipsBossArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tipsBossArray_Count;

/** 提示文案-陪玩侧 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tipsPwArray;
/** The number of items in @c tipsPwArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tipsPwArray_Count;

@end

#pragma mark - PB3IM1V1Tips

typedef GPB_ENUM(PB3IM1V1Tips_FieldNumber) {
  PB3IM1V1Tips_FieldNumber_TipsBossArray = 1,
  PB3IM1V1Tips_FieldNumber_TipsPwArray = 2,
};

/**
 * IM1v1通话界面的tips
 **/
@interface PB3IM1V1Tips : GPBMessage

/** 提示文案-老板侧 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tipsBossArray;
/** The number of items in @c tipsBossArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tipsBossArray_Count;

/** 提示文案-陪玩侧 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tipsPwArray;
/** The number of items in @c tipsPwArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tipsPwArray_Count;

@end

#pragma mark - PB3IMPresentPushCfg

typedef GPB_ENUM(PB3IMPresentPushCfg_FieldNumber) {
  PB3IMPresentPushCfg_FieldNumber_ShowTimeOutApp = 1,
  PB3IMPresentPushCfg_FieldNumber_ShowTimeOutPc = 2,
};

/**
 * IM限时礼物弹窗显示时间
 **/
@interface PB3IMPresentPushCfg : GPBMessage

/** APP端显示过期时间戳 */
@property(nonatomic, readwrite) int64_t showTimeOutApp;

/** PC端显示过期时间戳 */
@property(nonatomic, readwrite) int64_t showTimeOutPc;

@end

#pragma mark - PB3CouponCfg

typedef GPB_ENUM(PB3CouponCfg_FieldNumber) {
  PB3CouponCfg_FieldNumber_Id_p = 1,
  PB3CouponCfg_FieldNumber_Name = 2,
  PB3CouponCfg_FieldNumber_DiscountType = 3,
  PB3CouponCfg_FieldNumber_FullMoney = 4,
  PB3CouponCfg_FieldNumber_SubMoney = 5,
  PB3CouponCfg_FieldNumber_Discount = 6,
  PB3CouponCfg_FieldNumber_JumpType = 7,
  PB3CouponCfg_FieldNumber_JumpURL = 8,
  PB3CouponCfg_FieldNumber_UsageRemark = 9,
  PB3CouponCfg_FieldNumber_Status = 10,
  PB3CouponCfg_FieldNumber_DiscountUnit = 11,
  PB3CouponCfg_FieldNumber_OfficialSubsidyNum = 12,
};

/**
 * 优惠券配置
 **/
@interface PB3CouponCfg : GPBMessage

/** 优惠券ID */
@property(nonatomic, readwrite) int64_t id_p;

/** 优惠券名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 优惠方式 */
@property(nonatomic, readwrite) enum PB3CouponDiscountType discountType;

/** 最低满足金额(元)(-1无限制) */
@property(nonatomic, readwrite) int32_t fullMoney;

/** 减金额(元) */
@property(nonatomic, readwrite) int32_t subMoney;

/** 折扣（百分位，即放大100倍，如: 7.5折，则该数值为75，tips：显示时除以10，计算时除以100） */
@property(nonatomic, readwrite) int32_t discount;

/** 跳转场景类型 */
@property(nonatomic, readwrite) enum PB3CouponJumpType jumpType;

/** 跳转路由 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jumpURL;

/** 使用说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *usageRemark;

/** 状态 */
@property(nonatomic, readwrite) enum PB3CouponStatus status;

/** 折扣单位（元，折） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *discountUnit;

/** 官方补贴金币数 */
@property(nonatomic, readwrite) int64_t officialSubsidyNum;

@end

/**
 * Fetches the raw value of a @c PB3CouponCfg's @c discountType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3CouponCfg_DiscountType_RawValue(PB3CouponCfg *message);
/**
 * Sets the raw value of an @c PB3CouponCfg's @c discountType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3CouponCfg_DiscountType_RawValue(PB3CouponCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3CouponCfg's @c jumpType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3CouponCfg_JumpType_RawValue(PB3CouponCfg *message);
/**
 * Sets the raw value of an @c PB3CouponCfg's @c jumpType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3CouponCfg_JumpType_RawValue(PB3CouponCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3CouponCfg's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3CouponCfg_Status_RawValue(PB3CouponCfg *message);
/**
 * Sets the raw value of an @c PB3CouponCfg's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3CouponCfg_Status_RawValue(PB3CouponCfg *message, int32_t value);

#pragma mark - PB3CouponIssueRule

typedef GPB_ENUM(PB3CouponIssueRule_FieldNumber) {
  PB3CouponIssueRule_FieldNumber_CfgId = 1,
  PB3CouponIssueRule_FieldNumber_EffectType = 2,
  PB3CouponIssueRule_FieldNumber_FixBeginAt = 3,
  PB3CouponIssueRule_FieldNumber_FixEndAt = 4,
  PB3CouponIssueRule_FieldNumber_GetBeginDay = 5,
  PB3CouponIssueRule_FieldNumber_GetDayNum = 6,
  PB3CouponIssueRule_FieldNumber_CouponNum = 7,
  PB3CouponIssueRule_FieldNumber_Sort = 8,
};

/**
 * 优惠券发放规则
 **/
@interface PB3CouponIssueRule : GPBMessage

/** 优惠券id */
@property(nonatomic, readwrite) int64_t cfgId;

/** 有效期方式 */
@property(nonatomic, readwrite) PB3CouponEffectType effectType;

/** 开始时间(时间戳秒) */
@property(nonatomic, readwrite) int64_t fixBeginAt;

/** 结束时间(时间戳秒) */
@property(nonatomic, readwrite) int64_t fixEndAt;

/** 领取多少天后生效(-1当天生效) */
@property(nonatomic, readwrite) int32_t getBeginDay;

/** 有效天数 */
@property(nonatomic, readwrite) int32_t getDayNum;

/** 发放数量 */
@property(nonatomic, readwrite) int32_t couponNum;

/** 包内展示权重 */
@property(nonatomic, readwrite) int32_t sort;

@end

/**
 * Fetches the raw value of a @c PB3CouponIssueRule's @c effectType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3CouponIssueRule_EffectType_RawValue(PB3CouponIssueRule *message);
/**
 * Sets the raw value of an @c PB3CouponIssueRule's @c effectType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3CouponIssueRule_EffectType_RawValue(PB3CouponIssueRule *message, int32_t value);

#pragma mark - PB3CouponGainRule

typedef GPB_ENUM(PB3CouponGainRule_FieldNumber) {
  PB3CouponGainRule_FieldNumber_IsLimitNew = 1,
  PB3CouponGainRule_FieldNumber_LimitNewHour = 2,
  PB3CouponGainRule_FieldNumber_LimitType = 3,
  PB3CouponGainRule_FieldNumber_WealthLevMin = 4,
  PB3CouponGainRule_FieldNumber_WealthLevMax = 5,
  PB3CouponGainRule_FieldNumber_CharmLevMin = 6,
  PB3CouponGainRule_FieldNumber_CharmLevMax = 7,
  PB3CouponGainRule_FieldNumber_IsAnd = 8,
  PB3CouponGainRule_FieldNumber_IsRepeat = 9,
  PB3CouponGainRule_FieldNumber_RepeatDay = 10,
  PB3CouponGainRule_FieldNumber_RepeatNum = 11,
  PB3CouponGainRule_FieldNumber_JudgeDevice = 12,
  PB3CouponGainRule_FieldNumber_WhiteChannel = 13,
  PB3CouponGainRule_FieldNumber_ChannelType = 14,
  PB3CouponGainRule_FieldNumber_AdvendorId = 15,
  PB3CouponGainRule_FieldNumber_DeviceType = 16,
  PB3CouponGainRule_FieldNumber_AndOr = 17,
};

/**
 * 优惠券领取规则
 **/
@interface PB3CouponGainRule : GPBMessage

/** 是否限制新用户 false:否;true:是 */
@property(nonatomic, readwrite) BOOL isLimitNew;

/** 新用户限制小时 */
@property(nonatomic, readwrite) int32_t limitNewHour;

/** 限制类型 */
@property(nonatomic, readwrite) PB3CouponLimitType limitType;

/** 最低财富等级(-1无限制) */
@property(nonatomic, readwrite) int32_t wealthLevMin;

/** 最高财富等级(-1无限制) */
@property(nonatomic, readwrite) int32_t wealthLevMax;

/** 最低魅力等级(-1无限制) */
@property(nonatomic, readwrite) int32_t charmLevMin;

/** 最高魅力等级(-1无限制) */
@property(nonatomic, readwrite) int32_t charmLevMax;

/** 等级逻辑关系:false或，true */
@property(nonatomic, readwrite) BOOL isAnd;

/** 重复领取:false:否;true:是 */
@property(nonatomic, readwrite) BOOL isRepeat;

/** 重复领取天数 */
@property(nonatomic, readwrite) int32_t repeatDay;

/** 重复领取数量 */
@property(nonatomic, readwrite) int32_t repeatNum;

/** 是否判断新设备 */
@property(nonatomic, readwrite) BOOL judgeDevice;

/** 渠道白名单 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32BoolDictionary *whiteChannel;
/** The number of items in @c whiteChannel without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger whiteChannel_Count;

/** 渠道类型白名单 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64BoolDictionary *channelType;
/** The number of items in @c channelType without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger channelType_Count;

/** 渠道平台 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64BoolDictionary *advendorId;
/** The number of items in @c advendorId without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger advendorId_Count;

/** 设备类型 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32BoolDictionary *deviceType;
/** The number of items in @c deviceType without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger deviceType_Count;

/** 全且 或 全或 */
@property(nonatomic, readwrite) BOOL andOr;

@end

/**
 * Fetches the raw value of a @c PB3CouponGainRule's @c limitType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3CouponGainRule_LimitType_RawValue(PB3CouponGainRule *message);
/**
 * Sets the raw value of an @c PB3CouponGainRule's @c limitType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3CouponGainRule_LimitType_RawValue(PB3CouponGainRule *message, int32_t value);

#pragma mark - PB3CouponPackageCfg

typedef GPB_ENUM(PB3CouponPackageCfg_FieldNumber) {
  PB3CouponPackageCfg_FieldNumber_Id_p = 1,
  PB3CouponPackageCfg_FieldNumber_Name = 2,
  PB3CouponPackageCfg_FieldNumber_PackageType = 3,
  PB3CouponPackageCfg_FieldNumber_GainRule = 4,
  PB3CouponPackageCfg_FieldNumber_IssueRuleArray = 5,
};

/**
 * 优惠券礼包配置
 **/
@interface PB3CouponPackageCfg : GPBMessage

/** 礼包id */
@property(nonatomic, readwrite) int64_t id_p;

/** 礼包名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 礼包类型 */
@property(nonatomic, readwrite) enum PB3CouponPackageType packageType;

/** 领取规则 */
@property(nonatomic, readwrite, strong, null_resettable) PB3CouponGainRule *gainRule;
/** Test to see if @c gainRule has been set. */
@property(nonatomic, readwrite) BOOL hasGainRule;

/** 券发放规则 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3CouponIssueRule*> *issueRuleArray;
/** The number of items in @c issueRuleArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger issueRuleArray_Count;

@end

/**
 * Fetches the raw value of a @c PB3CouponPackageCfg's @c packageType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3CouponPackageCfg_PackageType_RawValue(PB3CouponPackageCfg *message);
/**
 * Sets the raw value of an @c PB3CouponPackageCfg's @c packageType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3CouponPackageCfg_PackageType_RawValue(PB3CouponPackageCfg *message, int32_t value);

#pragma mark - PB3IntimateFansMiddionCliCfg

typedef GPB_ENUM(PB3IntimateFansMiddionCliCfg_FieldNumber) {
  PB3IntimateFansMiddionCliCfg_FieldNumber_Id_p = 1,
  PB3IntimateFansMiddionCliCfg_FieldNumber_Type = 2,
  PB3IntimateFansMiddionCliCfg_FieldNumber_Name = 3,
  PB3IntimateFansMiddionCliCfg_FieldNumber_Desc = 4,
  PB3IntimateFansMiddionCliCfg_FieldNumber_TargetVal = 5,
  PB3IntimateFansMiddionCliCfg_FieldNumber_IntimateVal = 6,
  PB3IntimateFansMiddionCliCfg_FieldNumber_Router = 7,
  PB3IntimateFansMiddionCliCfg_FieldNumber_RouterTitle = 8,
  PB3IntimateFansMiddionCliCfg_FieldNumber_Icon = 9,
  PB3IntimateFansMiddionCliCfg_FieldNumber_Sort = 10,
};

/**
 * 个播2.0亲密粉丝客户端任务配置
 **/
@interface PB3IntimateFansMiddionCliCfg : GPBMessage

/** 任务id */
@property(nonatomic, readwrite) int64_t id_p;

/** 任务类型 */
@property(nonatomic, readwrite) enum PB3IntimateFansTargetType type;

/** 任务名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 任务描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

/** 目标值 */
@property(nonatomic, readwrite) int64_t targetVal;

/** 亲密值 */
@property(nonatomic, readwrite) int64_t intimateVal;

/** 跳转路由 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *router;

/** 路由按钮名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *routerTitle;

/** 任务图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 任务排序 */
@property(nonatomic, readwrite) int64_t sort;

@end

/**
 * Fetches the raw value of a @c PB3IntimateFansMiddionCliCfg's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3IntimateFansMiddionCliCfg_Type_RawValue(PB3IntimateFansMiddionCliCfg *message);
/**
 * Sets the raw value of an @c PB3IntimateFansMiddionCliCfg's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3IntimateFansMiddionCliCfg_Type_RawValue(PB3IntimateFansMiddionCliCfg *message, int32_t value);

#pragma mark - PB3BillSkillBaseCfg

typedef GPB_ENUM(PB3BillSkillBaseCfg_FieldNumber) {
  PB3BillSkillBaseCfg_FieldNumber_AvatarIcon = 1,
  PB3BillSkillBaseCfg_FieldNumber_AvatarLabel = 2,
};

/**
 * 点单技能基础配置
 **/
@interface PB3BillSkillBaseCfg : GPBMessage

/** 头像审核示例图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarIcon;

/** 头像审核示例说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarLabel;

@end

#pragma mark - PB3SolitaireEatPut

typedef GPB_ENUM(PB3SolitaireEatPut_FieldNumber) {
  PB3SolitaireEatPut_FieldNumber_EatPut = 1,
  PB3SolitaireEatPut_FieldNumber_Target = 2,
  PB3SolitaireEatPut_FieldNumber_Rate = 3,
  PB3SolitaireEatPut_FieldNumber_Weight = 4,
};

/**
 * 接龙奖池吃放规则
 **/
@interface PB3SolitaireEatPut : GPBMessage

/** 吃或放 1:吃 2:放 */
@property(nonatomic, readwrite) PB3SolitaireEatPutType eatPut;

/** 吃放对象 1:用户投入 2:奖池初始值 */
@property(nonatomic, readwrite) PB3SolitaireTarget target;

/** 比率，如设置成10%，那该值为10 */
@property(nonatomic, readwrite) int32_t rate;

/** 权重 */
@property(nonatomic, readwrite) int32_t weight;

@end

/**
 * Fetches the raw value of a @c PB3SolitaireEatPut's @c eatPut property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3SolitaireEatPut_EatPut_RawValue(PB3SolitaireEatPut *message);
/**
 * Sets the raw value of an @c PB3SolitaireEatPut's @c eatPut property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3SolitaireEatPut_EatPut_RawValue(PB3SolitaireEatPut *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3SolitaireEatPut's @c target property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3SolitaireEatPut_Target_RawValue(PB3SolitaireEatPut *message);
/**
 * Sets the raw value of an @c PB3SolitaireEatPut's @c target property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3SolitaireEatPut_Target_RawValue(PB3SolitaireEatPut *message, int32_t value);

#pragma mark - PB3SolitaireRate

typedef GPB_ENUM(PB3SolitaireRate_FieldNumber) {
  PB3SolitaireRate_FieldNumber_MinWeight = 1,
  PB3SolitaireRate_FieldNumber_MaxWeight = 2,
  PB3SolitaireRate_FieldNumber_UserRate = 3,
  PB3SolitaireRate_FieldNumber_PondRate = 4,
};

@interface PB3SolitaireRate : GPBMessage

/** 最低比率，如设置成10%，那该值为10 */
@property(nonatomic, readwrite) int64_t minWeight;

/** 最高比率，如设置成10%，那该值为10 */
@property(nonatomic, readwrite) int64_t maxWeight;

/** 用户比例，如设置成10%，那该值为10 */
@property(nonatomic, readwrite) int64_t userRate;

/** 总奖池比例，如设置成10%，那该值为10 */
@property(nonatomic, readwrite) int64_t pondRate;

@end

#pragma mark - PB3SolitaireScheme

typedef GPB_ENUM(PB3SolitaireScheme_FieldNumber) {
  PB3SolitaireScheme_FieldNumber_Scheme = 1,
  PB3SolitaireScheme_FieldNumber_Score = 2,
  PB3SolitaireScheme_FieldNumber_EatPutListArray = 3,
  PB3SolitaireScheme_FieldNumber_RateListArray = 4,
  PB3SolitaireScheme_FieldNumber_TotalWeight = 5,
  PB3SolitaireScheme_FieldNumber_ConfId = 6,
};

@interface PB3SolitaireScheme : GPBMessage

/** 方案类型 1:常规 2:吃分线 3:放分线 */
@property(nonatomic, readwrite) PB3SolitaireSchemeType scheme;

/** 分值 scheme=2，本轮初始值<=该值执行 scheme=3，本轮初始值>=该值执行 */
@property(nonatomic, readwrite) int64_t score;

/** 吃放规则 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3SolitaireEatPut*> *eatPutListArray;
/** The number of items in @c eatPutListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eatPutListArray_Count;

/** 比例列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3SolitaireRate*> *rateListArray;
/** The number of items in @c rateListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rateListArray_Count;

/** 总权重 */
@property(nonatomic, readwrite) int64_t totalWeight;

/** 配置ID */
@property(nonatomic, readwrite) int32_t confId;

@end

/**
 * Fetches the raw value of a @c PB3SolitaireScheme's @c scheme property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3SolitaireScheme_Scheme_RawValue(PB3SolitaireScheme *message);
/**
 * Sets the raw value of an @c PB3SolitaireScheme's @c scheme property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3SolitaireScheme_Scheme_RawValue(PB3SolitaireScheme *message, int32_t value);

#pragma mark - PB3SolitaireTips

typedef GPB_ENUM(PB3SolitaireTips_FieldNumber) {
  PB3SolitaireTips_FieldNumber_Id_p = 1,
  PB3SolitaireTips_FieldNumber_Tips = 2,
};

@interface PB3SolitaireTips : GPBMessage

/** id */
@property(nonatomic, readwrite) int32_t id_p;

/** 飘屏文案 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - PB3XcmSolitaireCfg

typedef GPB_ENUM(PB3XcmSolitaireCfg_FieldNumber) {
  PB3XcmSolitaireCfg_FieldNumber_Id_p = 1,
  PB3XcmSolitaireCfg_FieldNumber_Name = 2,
  PB3XcmSolitaireCfg_FieldNumber_IsOpen = 3,
  PB3XcmSolitaireCfg_FieldNumber_TimeType = 4,
  PB3XcmSolitaireCfg_FieldNumber_StartTime = 5,
  PB3XcmSolitaireCfg_FieldNumber_EndTime = 6,
  PB3XcmSolitaireCfg_FieldNumber_StoreId = 7,
  PB3XcmSolitaireCfg_FieldNumber_TimeLong = 8,
  PB3XcmSolitaireCfg_FieldNumber_MinJoin = 9,
  PB3XcmSolitaireCfg_FieldNumber_MaxJoin = 10,
  PB3XcmSolitaireCfg_FieldNumber_BlessingValue = 11,
  PB3XcmSolitaireCfg_FieldNumber_TipsArray = 12,
  PB3XcmSolitaireCfg_FieldNumber_RuleDesc = 13,
  PB3XcmSolitaireCfg_FieldNumber_WaitTime = 14,
  PB3XcmSolitaireCfg_FieldNumber_ListArray = 15,
  PB3XcmSolitaireCfg_FieldNumber_ExchangeId = 16,
  PB3XcmSolitaireCfg_FieldNumber_EffectId = 17,
  PB3XcmSolitaireCfg_FieldNumber_EffectRewardTimeLong = 18,
  PB3XcmSolitaireCfg_FieldNumber_ActPage = 19,
  PB3XcmSolitaireCfg_FieldNumber_ActType = 20,
  PB3XcmSolitaireCfg_FieldNumber_IncStoreId = 21,
};

/**
 * 春节福气接龙-接龙配置
 **/
@interface PB3XcmSolitaireCfg : GPBMessage

/** 配置ID */
@property(nonatomic, readwrite) int32_t id_p;

/** 配置名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 是否开启 */
@property(nonatomic, readwrite) BOOL isOpen;

/** 开启时间类型，1:持续时间段 2:每日计时 */
@property(nonatomic, readwrite) PB3SolitaireTimeType timeType;

/** 开始时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *startTime;

/** 结束时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endTime;

/** 挚友商城物品ID */
@property(nonatomic, readwrite) int64_t storeId;

/** 每局持续时长(秒) */
@property(nonatomic, readwrite) int64_t timeLong;

/** 最低参与人数，-1不限 */
@property(nonatomic, readwrite) int32_t minJoin;

/** 最高参与人数，-1不限 */
@property(nonatomic, readwrite) int32_t maxJoin;

/** 参与用户注入福气值 */
@property(nonatomic, readwrite) int64_t blessingValue;

/** 飘屏默认文案 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3SolitaireTips*> *tipsArray;
/** The number of items in @c tipsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tipsArray_Count;

/** 规则文案 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ruleDesc;

/** 开奖等待时长(秒) */
@property(nonatomic, readwrite) int32_t waitTime;

/** 奖池规则 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3SolitaireScheme*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

/** 兑换礼物ID */
@property(nonatomic, readwrite) int32_t exchangeId;

/** 奖励特效ID，可以是空 */
@property(nonatomic, readwrite) int32_t effectId;

/** 特效奖励时长 */
@property(nonatomic, readwrite) int64_t effectRewardTimeLong;

/** 页面内容 */
@property(nonatomic, readwrite, strong, null_resettable) PB3ConfActPage *actPage;
/** Test to see if @c actPage has been set. */
@property(nonatomic, readwrite) BOOL hasActPage;

/** 活动类型 */
@property(nonatomic, readwrite) enum PB3SubInfoActivityType actType;

/**  挚友商城商城ID */
@property(nonatomic, readwrite) int32_t incStoreId;

@end

/**
 * Fetches the raw value of a @c PB3XcmSolitaireCfg's @c timeType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmSolitaireCfg_TimeType_RawValue(PB3XcmSolitaireCfg *message);
/**
 * Sets the raw value of an @c PB3XcmSolitaireCfg's @c timeType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmSolitaireCfg_TimeType_RawValue(PB3XcmSolitaireCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3XcmSolitaireCfg's @c actType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmSolitaireCfg_ActType_RawValue(PB3XcmSolitaireCfg *message);
/**
 * Sets the raw value of an @c PB3XcmSolitaireCfg's @c actType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmSolitaireCfg_ActType_RawValue(PB3XcmSolitaireCfg *message, int32_t value);

#pragma mark - PB3XcmKickOutRoomCfg

typedef GPB_ENUM(PB3XcmKickOutRoomCfg_FieldNumber) {
  PB3XcmKickOutRoomCfg_FieldNumber_CfgId = 1,
  PB3XcmKickOutRoomCfg_FieldNumber_CfgName = 2,
  PB3XcmKickOutRoomCfg_FieldNumber_ExpiredTime = 3,
  PB3XcmKickOutRoomCfg_FieldNumber_UnitTime = 4,
};

/**
 * 房间踢人时间配置
 **/
@interface PB3XcmKickOutRoomCfg : GPBMessage

/** 配置ID */
@property(nonatomic, readwrite) int32_t cfgId;

/** 配置名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cfgName;

/** 过期时间 */
@property(nonatomic, readwrite) int64_t expiredTime;

/** 时间单位 */
@property(nonatomic, readwrite) PB3XcmKickOutRoomType unitTime;

@end

/**
 * Fetches the raw value of a @c PB3XcmKickOutRoomCfg's @c unitTime property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmKickOutRoomCfg_UnitTime_RawValue(PB3XcmKickOutRoomCfg *message);
/**
 * Sets the raw value of an @c PB3XcmKickOutRoomCfg's @c unitTime property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmKickOutRoomCfg_UnitTime_RawValue(PB3XcmKickOutRoomCfg *message, int32_t value);

#pragma mark - PB3XcmCfgHarassAccuse

typedef GPB_ENUM(PB3XcmCfgHarassAccuse_FieldNumber) {
  PB3XcmCfgHarassAccuse_FieldNumber_TipsText = 1,
};

/**
 * 骚扰投诉提示
 **/
@interface PB3XcmCfgHarassAccuse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tipsText;

@end

#pragma mark - PB3XcmGiftSkinCfg

typedef GPB_ENUM(PB3XcmGiftSkinCfg_FieldNumber) {
  PB3XcmGiftSkinCfg_FieldNumber_SkinId = 1,
  PB3XcmGiftSkinCfg_FieldNumber_SkinName = 2,
  PB3XcmGiftSkinCfg_FieldNumber_AppIcon = 3,
  PB3XcmGiftSkinCfg_FieldNumber_PcIcon = 4,
  PB3XcmGiftSkinCfg_FieldNumber_AppGiftWallTag = 5,
  PB3XcmGiftSkinCfg_FieldNumber_PcGiftWallTag = 6,
  PB3XcmGiftSkinCfg_FieldNumber_IsAnimation = 7,
  PB3XcmGiftSkinCfg_FieldNumber_AnimationTime = 8,
  PB3XcmGiftSkinCfg_FieldNumber_AnimationMask = 9,
  PB3XcmGiftSkinCfg_FieldNumber_AnimationRes = 10,
  PB3XcmGiftSkinCfg_FieldNumber_ShowInRoom = 11,
  PB3XcmGiftSkinCfg_FieldNumber_GiftId = 12,
  PB3XcmGiftSkinCfg_FieldNumber_SkinMsg = 13,
  PB3XcmGiftSkinCfg_FieldNumber_Weight = 14,
};

/**
 * 礼物皮肤基础配置
 **/
@interface PB3XcmGiftSkinCfg : GPBMessage

/** 皮肤id */
@property(nonatomic, readwrite) int64_t skinId;

/** 皮肤名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *skinName;

/** app图标资源 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appIcon;

/** pc图标资源 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pcIcon;

/** app礼物墙角标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appGiftWallTag;

/** pc礼物墙角标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pcGiftWallTag;

/** 皮肤动画 */
@property(nonatomic, readwrite) BOOL isAnimation;

/** 皮肤动画时长（毫秒ms） */
@property(nonatomic, readwrite) int64_t animationTime;

/** 皮肤遮罩 */
@property(nonatomic, readwrite) BOOL animationMask;

/** 动画资源 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *animationRes;

/** 是否展示礼物墙 */
@property(nonatomic, readwrite) BOOL showInRoom;

/** 礼物id */
@property(nonatomic, readwrite) int64_t giftId;

/** 皮肤赠送语句 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *skinMsg;

/** 权重 */
@property(nonatomic, readwrite) int64_t weight;

@end

#pragma mark - PB3XcmGiftSkinStoreCfg

typedef GPB_ENUM(PB3XcmGiftSkinStoreCfg_FieldNumber) {
  PB3XcmGiftSkinStoreCfg_FieldNumber_StoreId = 1,
  PB3XcmGiftSkinStoreCfg_FieldNumber_Price = 2,
  PB3XcmGiftSkinStoreCfg_FieldNumber_Name = 3,
  PB3XcmGiftSkinStoreCfg_FieldNumber_SkinId = 4,
  PB3XcmGiftSkinStoreCfg_FieldNumber_SkinDetailIcon = 5,
  PB3XcmGiftSkinStoreCfg_FieldNumber_BottomDesc = 6,
  PB3XcmGiftSkinStoreCfg_FieldNumber_IsPurchase = 7,
  PB3XcmGiftSkinStoreCfg_FieldNumber_ShowType = 8,
  PB3XcmGiftSkinStoreCfg_FieldNumber_ShowStartTime = 9,
  PB3XcmGiftSkinStoreCfg_FieldNumber_TimeType = 10,
  PB3XcmGiftSkinStoreCfg_FieldNumber_TimeVal = 11,
  PB3XcmGiftSkinStoreCfg_FieldNumber_SoldType = 12,
  PB3XcmGiftSkinStoreCfg_FieldNumber_ShowEndTime = 13,
  PB3XcmGiftSkinStoreCfg_FieldNumber_DisplayType = 14,
  PB3XcmGiftSkinStoreCfg_FieldNumber_Weight = 15,
  PB3XcmGiftSkinStoreCfg_FieldNumber_ShowMap = 16,
};

/**
 * 礼物皮肤商城配置
 **/
@interface PB3XcmGiftSkinStoreCfg : GPBMessage

/** 商城id */
@property(nonatomic, readwrite) int64_t storeId;

/** 商城价格 */
@property(nonatomic, readwrite) int64_t price;

/** 皮肤名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 皮肤id */
@property(nonatomic, readwrite) int64_t skinId;

/** 皮肤详情图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *skinDetailIcon;

/** 底部文案 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bottomDesc;

/** 是否可购买 */
@property(nonatomic, readwrite) BOOL isPurchase;

/** 展示类型 */
@property(nonatomic, readwrite) PB3GiftSkinStoreShowType showType;

/** 开始展示时间 */
@property(nonatomic, readwrite) int64_t showStartTime;

/** 单位时效 */
@property(nonatomic, readwrite) PB3GiftSkinStoreTimeType timeType;

/** 时效时间 */
@property(nonatomic, readwrite) int64_t timeVal;

/** 出售类型 */
@property(nonatomic, readwrite) PB3GiftSkinStoreSoldType soldType;

/** 结束展示时间 */
@property(nonatomic, readwrite) int64_t showEndTime;

/** 显示类型 */
@property(nonatomic, readwrite) PB3GiftSkinStoreDisplayType displayType;

/** 权重 */
@property(nonatomic, readwrite) int64_t weight;

/** 指定展示人员map */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64BoolDictionary *showMap;
/** The number of items in @c showMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger showMap_Count;

@end

/**
 * Fetches the raw value of a @c PB3XcmGiftSkinStoreCfg's @c showType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmGiftSkinStoreCfg_ShowType_RawValue(PB3XcmGiftSkinStoreCfg *message);
/**
 * Sets the raw value of an @c PB3XcmGiftSkinStoreCfg's @c showType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmGiftSkinStoreCfg_ShowType_RawValue(PB3XcmGiftSkinStoreCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3XcmGiftSkinStoreCfg's @c timeType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmGiftSkinStoreCfg_TimeType_RawValue(PB3XcmGiftSkinStoreCfg *message);
/**
 * Sets the raw value of an @c PB3XcmGiftSkinStoreCfg's @c timeType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmGiftSkinStoreCfg_TimeType_RawValue(PB3XcmGiftSkinStoreCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3XcmGiftSkinStoreCfg's @c soldType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmGiftSkinStoreCfg_SoldType_RawValue(PB3XcmGiftSkinStoreCfg *message);
/**
 * Sets the raw value of an @c PB3XcmGiftSkinStoreCfg's @c soldType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmGiftSkinStoreCfg_SoldType_RawValue(PB3XcmGiftSkinStoreCfg *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3XcmGiftSkinStoreCfg's @c displayType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmGiftSkinStoreCfg_DisplayType_RawValue(PB3XcmGiftSkinStoreCfg *message);
/**
 * Sets the raw value of an @c PB3XcmGiftSkinStoreCfg's @c displayType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmGiftSkinStoreCfg_DisplayType_RawValue(PB3XcmGiftSkinStoreCfg *message, int32_t value);

#pragma mark - PB3XcmGiftSkinRule

typedef GPB_ENUM(PB3XcmGiftSkinRule_FieldNumber) {
  PB3XcmGiftSkinRule_FieldNumber_Rule = 1,
};

/**
 * 礼物皮肤规则
 **/
@interface PB3XcmGiftSkinRule : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *rule;

@end

#pragma mark - PB3XcmGiftSkinCfgData

typedef GPB_ENUM(PB3XcmGiftSkinCfgData_FieldNumber) {
  PB3XcmGiftSkinCfgData_FieldNumber_SkinMap = 1,
};

/**
 * 礼物皮肤基础配置
 **/
@interface PB3XcmGiftSkinCfgData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64ObjectDictionary<PB3XcmGiftSkinCfg*> *skinMap;
/** The number of items in @c skinMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger skinMap_Count;

@end

#pragma mark - PB3XcmGiftSkinStoreCfgData

typedef GPB_ENUM(PB3XcmGiftSkinStoreCfgData_FieldNumber) {
  PB3XcmGiftSkinStoreCfgData_FieldNumber_StoreMap = 1,
};

/**
 * 礼物皮肤商店配置
 **/
@interface PB3XcmGiftSkinStoreCfgData : GPBMessage

/** 礼物皮肤商店配置 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64ObjectDictionary<PB3XcmGiftSkinStoreCfg*> *storeMap;
/** The number of items in @c storeMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger storeMap_Count;

@end

#pragma mark - PB3XcmTextContentCfg

typedef GPB_ENUM(PB3XcmTextContentCfg_FieldNumber) {
  PB3XcmTextContentCfg_FieldNumber_TextContentMap = 1,
};

/**
 * 富文本内容配置
 **/
@interface PB3XcmTextContentCfg : GPBMessage

/** 富文本内容配置 key对应system.ext.proto TextContentType */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32ObjectDictionary<NSString*> *textContentMap;
/** The number of items in @c textContentMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger textContentMap_Count;

@end

#pragma mark - PB3CfgUserId2RandomScheme

typedef GPB_ENUM(PB3CfgUserId2RandomScheme_FieldNumber) {
  PB3CfgUserId2RandomScheme_FieldNumber_Id_p = 1,
  PB3CfgUserId2RandomScheme_FieldNumber_Id2Type = 2,
  PB3CfgUserId2RandomScheme_FieldNumber_Id2GiftId = 3,
  PB3CfgUserId2RandomScheme_FieldNumber_FirstConsumeNum = 4,
  PB3CfgUserId2RandomScheme_FieldNumber_FirstChangeConsumeNum = 5,
  PB3CfgUserId2RandomScheme_FieldNumber_ChangeTimes = 6,
};

@interface PB3CfgUserId2RandomScheme : GPBMessage

@property(nonatomic, readwrite) int32_t id_p;

@property(nonatomic, readwrite) int32_t id2Type;

@property(nonatomic, readwrite) int32_t id2GiftId;

@property(nonatomic, readwrite) int32_t firstConsumeNum;

@property(nonatomic, readwrite) int32_t firstChangeConsumeNum;

@property(nonatomic, readwrite) int32_t changeTimes;

@end

#pragma mark - PB3XcmCfgUserId2Random

typedef GPB_ENUM(PB3XcmCfgUserId2Random_FieldNumber) {
  PB3XcmCfgUserId2Random_FieldNumber_CfgListArray = 1,
  PB3XcmCfgUserId2Random_FieldNumber_ActPage = 2,
};

@interface PB3XcmCfgUserId2Random : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3CfgUserId2RandomScheme*> *cfgListArray;
/** The number of items in @c cfgListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cfgListArray_Count;

/** 页面内容 */
@property(nonatomic, readwrite, strong, null_resettable) PB3ConfActPage *actPage;
/** Test to see if @c actPage has been set. */
@property(nonatomic, readwrite) BOOL hasActPage;

@end

#pragma mark - PB3XcmRoomPatternCliCfg

typedef GPB_ENUM(PB3XcmRoomPatternCliCfg_FieldNumber) {
  PB3XcmRoomPatternCliCfg_FieldNumber_Pattern = 1,
  PB3XcmRoomPatternCliCfg_FieldNumber_DefaultDecorateId = 2,
};

/**
 * room.ext.proto，cmdId=100224 房间模式客户端配置
 **/
@interface PB3XcmRoomPatternCliCfg : GPBMessage

/** 房间模式 */
@property(nonatomic, readwrite) enum PB3NewRoomPattern pattern;

/** 房间模式默认背景（若为0，表示房间没有默认背景） */
@property(nonatomic, readwrite) int64_t defaultDecorateId;

@end

/**
 * Fetches the raw value of a @c PB3XcmRoomPatternCliCfg's @c pattern property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3XcmRoomPatternCliCfg_Pattern_RawValue(PB3XcmRoomPatternCliCfg *message);
/**
 * Sets the raw value of an @c PB3XcmRoomPatternCliCfg's @c pattern property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3XcmRoomPatternCliCfg_Pattern_RawValue(PB3XcmRoomPatternCliCfg *message, int32_t value);

#pragma mark - PB3XcmRoomPatternCliCfgData

typedef GPB_ENUM(PB3XcmRoomPatternCliCfgData_FieldNumber) {
  PB3XcmRoomPatternCliCfgData_FieldNumber_CliCfgListArray = 1,
  PB3XcmRoomPatternCliCfgData_FieldNumber_UnixTimestamp = 2,
};

/**
 * 房间模式客户端配置数据
 **/
@interface PB3XcmRoomPatternCliCfgData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3XcmRoomPatternCliCfg*> *cliCfgListArray;
/** The number of items in @c cliCfgListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cliCfgListArray_Count;

/** 更新时间，unix时间戳，单位: 秒 */
@property(nonatomic, readwrite) int64_t unixTimestamp;

@end

#pragma mark - PB3XcmRoomPatternCfgData

typedef GPB_ENUM(PB3XcmRoomPatternCfgData_FieldNumber) {
  PB3XcmRoomPatternCfgData_FieldNumber_CliCfgListArray = 1,
};

/**
 * 房间模式配置
 **/
@interface PB3XcmRoomPatternCfgData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3XcmRoomPatternCliCfg*> *cliCfgListArray;
/** The number of items in @c cliCfgListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cliCfgListArray_Count;

@end

#pragma mark - PB3XcmOfficialExamPassMemberCfg

typedef GPB_ENUM(PB3XcmOfficialExamPassMemberCfg_FieldNumber) {
  PB3XcmOfficialExamPassMemberCfg_FieldNumber_PlayerId = 1,
  PB3XcmOfficialExamPassMemberCfg_FieldNumber_ClanId = 2,
  PB3XcmOfficialExamPassMemberCfg_FieldNumber_ExaminationResult = 3,
};

@interface PB3XcmOfficialExamPassMemberCfg : GPBMessage

/** 用户ID */
@property(nonatomic, readwrite) int64_t playerId;

/** 公会ID */
@property(nonatomic, readwrite) int64_t clanId;

/** 考核结果 1-考核不通过,2-考核通过,3-待考核 */
@property(nonatomic, readwrite) int32_t examinationResult;

@end

#pragma mark - PB3XcmOfficialExamPassMemberCfgData

typedef GPB_ENUM(PB3XcmOfficialExamPassMemberCfgData_FieldNumber) {
  PB3XcmOfficialExamPassMemberCfgData_FieldNumber_CfgMap = 1,
};

@interface PB3XcmOfficialExamPassMemberCfgData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64ObjectDictionary<PB3XcmOfficialExamPassMemberCfg*> *cfgMap;
/** The number of items in @c cfgMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cfgMap_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
