 
 

 
 
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3AlbumCoverInfo;
@class PB3MusicAlbumInfo;
@class PB3MusicBaseInfo;
@class PB3MusicChorusClip;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB3MusicRightFilterType

 
typedef GPB_ENUM(PB3MusicRightFilterType) {
   
  PB3MusicRightFilterType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PB3MusicRightFilterType_PrftNone = 0,

   
  PB3MusicRightFilterType_PrftPlay = 1,

   
  PB3MusicRightFilterType_PrftSing = 2,
};

GPBEnumDescriptor *PB3MusicRightFilterType_EnumDescriptor(void);

 
BOOL PB3MusicRightFilterType_IsValidValue(int32_t value);

#pragma mark - Enum PB3MusicRecommendType

 
typedef GPB_ENUM(PB3MusicRecommendType) {
   
  PB3MusicRecommendType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PB3MusicRecommendType_MrtNone = 0,

   
  PB3MusicRecommendType_MrtFeatured = 1,

   
  PB3MusicRecommendType_MrtOther = 2,
};

GPBEnumDescriptor *PB3MusicRecommendType_EnumDescriptor(void);

 
BOOL PB3MusicRecommendType_IsValidValue(int32_t value);

#pragma mark - Enum PB3AlbumCoverInfoDimension

 
typedef GPB_ENUM(PB3AlbumCoverInfoDimension) {
   
  PB3AlbumCoverInfoDimension_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PB3AlbumCoverInfoDimension_AcidNone = 0,

   
  PB3AlbumCoverInfoDimension_AcidMini = 1,

   
  PB3AlbumCoverInfoDimension_AcidSmall = 2,

   
  PB3AlbumCoverInfoDimension_AcidMedium = 3,
};

GPBEnumDescriptor *PB3AlbumCoverInfoDimension_EnumDescriptor(void);

 
BOOL PB3AlbumCoverInfoDimension_IsValidValue(int32_t value);

#pragma mark - Enum PB3MusicPlaySourceType

 
typedef GPB_ENUM(PB3MusicPlaySourceType) {
   
  PB3MusicPlaySourceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PB3MusicPlaySourceType_MpstNone = 0,

   
  PB3MusicPlaySourceType_MpstLib = 1,

   
  PB3MusicPlaySourceType_MpstYsd = 2,
};

GPBEnumDescriptor *PB3MusicPlaySourceType_EnumDescriptor(void);

 
BOOL PB3MusicPlaySourceType_IsValidValue(int32_t value);

#pragma mark - Enum PB3MusicOriginType

 
typedef GPB_ENUM(PB3MusicOriginType) {
   
  PB3MusicOriginType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PB3MusicOriginType_MotNone = 0,

   
  PB3MusicOriginType_MotLib = 1,

   
  PB3MusicOriginType_MotYsd = 2,
};

GPBEnumDescriptor *PB3MusicOriginType_EnumDescriptor(void);

 
BOOL PB3MusicOriginType_IsValidValue(int32_t value);

#pragma mark - PB3KtvBaseExtRoot

 
@interface PB3KtvBaseExtRoot : GPBRootObject
@end

#pragma mark - PB3PlaylistBaseInfo

typedef GPB_ENUM(PB3PlaylistBaseInfo_FieldNumber) {
  PB3PlaylistBaseInfo_FieldNumber_PlaylistId = 1,
  PB3PlaylistBaseInfo_FieldNumber_Title = 2,
};

 
@interface PB3PlaylistBaseInfo : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *playlistId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@end

#pragma mark - PB3AlbumCoverInfo

typedef GPB_ENUM(PB3AlbumCoverInfo_FieldNumber) {
  PB3AlbumCoverInfo_FieldNumber_Dimension = 1,
  PB3AlbumCoverInfo_FieldNumber_URL = 2,
};

 
@interface PB3AlbumCoverInfo : GPBMessage

 
@property(nonatomic, readwrite) PB3AlbumCoverInfoDimension dimension;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

 
int32_t PB3AlbumCoverInfo_Dimension_RawValue(PB3AlbumCoverInfo *message);
 
void SetPB3AlbumCoverInfo_Dimension_RawValue(PB3AlbumCoverInfo *message, int32_t value);

#pragma mark - PB3MusicAlbumInfo

typedef GPB_ENUM(PB3MusicAlbumInfo_FieldNumber) {
  PB3MusicAlbumInfo_FieldNumber_Name = 1,
  PB3MusicAlbumInfo_FieldNumber_CoverInfoListArray = 2,
};

 
@interface PB3MusicAlbumInfo : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3AlbumCoverInfo*> *coverInfoListArray;
 
@property(nonatomic, readonly) NSUInteger coverInfoListArray_Count;

@end

#pragma mark - PB3MusicBaseInfo

typedef GPB_ENUM(PB3MusicBaseInfo_FieldNumber) {
  PB3MusicBaseInfo_FieldNumber_MusicBaseId = 1,
  PB3MusicBaseInfo_FieldNumber_MusicId = 2,
  PB3MusicBaseInfo_FieldNumber_Name = 3,
  PB3MusicBaseInfo_FieldNumber_SingersArray = 4,
  PB3MusicBaseInfo_FieldNumber_Duration = 5,
  PB3MusicBaseInfo_FieldNumber_SingerImageURL = 6,
  PB3MusicBaseInfo_FieldNumber_AlbumInfo = 7,
  PB3MusicBaseInfo_FieldNumber_RightListArray = 8,
  PB3MusicBaseInfo_FieldNumber_RecommendType = 9,
};

 
@interface PB3MusicBaseInfo : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *musicBaseId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *musicId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *singersArray;
 
@property(nonatomic, readonly) NSUInteger singersArray_Count;

 
@property(nonatomic, readwrite) int32_t duration;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *singerImageURL;

 
@property(nonatomic, readwrite, strong, null_resettable) PB3MusicAlbumInfo *albumInfo;
 
@property(nonatomic, readwrite) BOOL hasAlbumInfo;

 
 
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *rightListArray;
 
@property(nonatomic, readonly) NSUInteger rightListArray_Count;

 
@property(nonatomic, readwrite) PB3MusicRecommendType recommendType;

@end

 
int32_t PB3MusicBaseInfo_RecommendType_RawValue(PB3MusicBaseInfo *message);
 
void SetPB3MusicBaseInfo_RecommendType_RawValue(PB3MusicBaseInfo *message, int32_t value);

#pragma mark - PB3MusicChorusClip

typedef GPB_ENUM(PB3MusicChorusClip_FieldNumber) {
  PB3MusicChorusClip_FieldNumber_StartTime = 1,
  PB3MusicChorusClip_FieldNumber_EndTime = 2,
};

 
@interface PB3MusicChorusClip : GPBMessage

 
@property(nonatomic, readwrite) int64_t startTime;

 
@property(nonatomic, readwrite) int64_t endTime;

@end

#pragma mark - PB3MusicDetailInfo

typedef GPB_ENUM(PB3MusicDetailInfo_FieldNumber) {
  PB3MusicDetailInfo_FieldNumber_MusicBaseInfo = 1,
  PB3MusicDetailInfo_FieldNumber_PlayToken = 2,
  PB3MusicDetailInfo_FieldNumber_LyricsURL = 3,
  PB3MusicDetailInfo_FieldNumber_MidiURL = 4,
  PB3MusicDetailInfo_FieldNumber_ChorusClipListArray = 5,
  PB3MusicDetailInfo_FieldNumber_PreludeInterval = 6,
  PB3MusicDetailInfo_FieldNumber_GenreListArray = 7,
  PB3MusicDetailInfo_FieldNumber_PlaySource = 8,
};

 
@interface PB3MusicDetailInfo : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) PB3MusicBaseInfo *musicBaseInfo;
 
@property(nonatomic, readwrite) BOOL hasMusicBaseInfo;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *playToken;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *lyricsURL;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *midiURL;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3MusicChorusClip*> *chorusClipListArray;
 
@property(nonatomic, readonly) NSUInteger chorusClipListArray_Count;

 
@property(nonatomic, readwrite) int64_t preludeInterval;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *genreListArray;
 
@property(nonatomic, readonly) NSUInteger genreListArray_Count;

 
@property(nonatomic, readwrite) PB3MusicPlaySourceType playSource;

@end

 
int32_t PB3MusicDetailInfo_PlaySource_RawValue(PB3MusicDetailInfo *message);
 
void SetPB3MusicDetailInfo_PlaySource_RawValue(PB3MusicDetailInfo *message, int32_t value);

#pragma mark - PB3MusicSuggestionInfo

typedef GPB_ENUM(PB3MusicSuggestionInfo_FieldNumber) {
  PB3MusicSuggestionInfo_FieldNumber_Suggestion = 1,
};

 
@interface PB3MusicSuggestionInfo : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *suggestion;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

 
