 
 

 
 
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3GetVoiceIdentifyConfRes_Prompt;
@class PB3LiveChannelPush;
@class PB3LiveCharacter;
@class PB3LiveIMPush;
@class PB3LiveMatchRes_LiveRecommend;
@class PB3LiveModel;
@class PB3LiveSnapshot;
@class PB3LiveSticker;
@class PB3PlayerInfo;
@class PB3VoiceFeature;
GPB_ENUM_FWD_DECLARE(PB3SexType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB3LiveCmdId

typedef GPB_ENUM(PB3LiveCmdId) {
   
  PB3LiveCmdId_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveCmdId_LcNone = 0,

   
  PB3LiveCmdId_LcLiveChannel = 702001,

   
  PB3LiveCmdId_LcLiveImCall = 702002,

   
  PB3LiveCmdId_LcLiveTalk = 702003,

   
  PB3LiveCmdId_LcPlayerLiveDataUpdate = 702004,

   
  PB3LiveCmdId_LcPlayerMatchTelepathy = 702005,
};

GPBEnumDescriptor *PB3LiveCmdId_EnumDescriptor(void);

 
BOOL PB3LiveCmdId_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveStickerType

typedef GPB_ENUM(PB3LiveStickerType) {
   
  PB3LiveStickerType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveStickerType_LstNone = 0,

   
  PB3LiveStickerType_LstCloth = 1,
  PB3LiveStickerType_LstAll = 1000,
};

GPBEnumDescriptor *PB3LiveStickerType_EnumDescriptor(void);

 
BOOL PB3LiveStickerType_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveSnapshotLayer

typedef GPB_ENUM(PB3LiveSnapshotLayer) {
   
  PB3LiveSnapshotLayer_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveSnapshotLayer_LslNone = 0,

   
  PB3LiveSnapshotLayer_LslFrontHair = 1,

   
  PB3LiveSnapshotLayer_LslNakedModel = 2,

   
  PB3LiveSnapshotLayer_LslBackHair = 3,

   
  PB3LiveSnapshotLayer_LslCloth = 4,
};

GPBEnumDescriptor *PB3LiveSnapshotLayer_EnumDescriptor(void);

 
BOOL PB3LiveSnapshotLayer_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveChannelScene

typedef GPB_ENUM(PB3LiveChannelScene) {
   
  PB3LiveChannelScene_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveChannelScene_ScNone = 0,

   
  PB3LiveChannelScene_ScImCall = 1,

   
  PB3LiveChannelScene_ScMatch = 2,
};

GPBEnumDescriptor *PB3LiveChannelScene_EnumDescriptor(void);

 
BOOL PB3LiveChannelScene_IsValidValue(int32_t value);

#pragma mark - Enum PB3PlayerLiveDataPush_PushType

typedef GPB_ENUM(PB3PlayerLiveDataPush_PushType) {
   
  PB3PlayerLiveDataPush_PushType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3PlayerLiveDataPush_PushType_None = 0,
  PB3PlayerLiveDataPush_PushType_Hearts = 1,
  PB3PlayerLiveDataPush_PushType_FreeMatchTimes = 2,
};

GPBEnumDescriptor *PB3PlayerLiveDataPush_PushType_EnumDescriptor(void);

 
BOOL PB3PlayerLiveDataPush_PushType_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveMatchReq_MatchOper

typedef GPB_ENUM(PB3LiveMatchReq_MatchOper) {
   
  PB3LiveMatchReq_MatchOper_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveMatchReq_MatchOper_None = 0,

   
  PB3LiveMatchReq_MatchOper_Apply = 1,
  PB3LiveMatchReq_MatchOper_Cancel = 2,
};

GPBEnumDescriptor *PB3LiveMatchReq_MatchOper_EnumDescriptor(void);

 
BOOL PB3LiveMatchReq_MatchOper_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveCallInviteReq_InviteOper

typedef GPB_ENUM(PB3LiveCallInviteReq_InviteOper) {
   
  PB3LiveCallInviteReq_InviteOper_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveCallInviteReq_InviteOper_None = 0,

   
  PB3LiveCallInviteReq_InviteOper_Apply = 1,
  PB3LiveCallInviteReq_InviteOper_Cancel = 2,
};

GPBEnumDescriptor *PB3LiveCallInviteReq_InviteOper_EnumDescriptor(void);

 
BOOL PB3LiveCallInviteReq_InviteOper_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveCallReplyReq_ReplyOper

typedef GPB_ENUM(PB3LiveCallReplyReq_ReplyOper) {
   
  PB3LiveCallReplyReq_ReplyOper_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveCallReplyReq_ReplyOper_None = 0,
  PB3LiveCallReplyReq_ReplyOper_Receive = 1,
  PB3LiveCallReplyReq_ReplyOper_Deny = 2,
  PB3LiveCallReplyReq_ReplyOper_Ignore = 3,
};

GPBEnumDescriptor *PB3LiveCallReplyReq_ReplyOper_EnumDescriptor(void);

 
BOOL PB3LiveCallReplyReq_ReplyOper_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveTalkSyncReq_SyncOper

typedef GPB_ENUM(PB3LiveTalkSyncReq_SyncOper) {
   
  PB3LiveTalkSyncReq_SyncOper_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveTalkSyncReq_SyncOper_None = 0,

   
  PB3LiveTalkSyncReq_SyncOper_Like = 1,

   
  PB3LiveTalkSyncReq_SyncOper_InviteShow = 2,

   
  PB3LiveTalkSyncReq_SyncOper_ShowSelf = 3,

   
  PB3LiveTalkSyncReq_SyncOper_Hangup = 4,

   
  PB3LiveTalkSyncReq_SyncOper_TouchSelfHead = 5,
  PB3LiveTalkSyncReq_SyncOper_TouchTargetHead = 6,

   
  PB3LiveTalkSyncReq_SyncOper_TouchSelfBody = 7,
  PB3LiveTalkSyncReq_SyncOper_TouchTargetBody = 8,
};

GPBEnumDescriptor *PB3LiveTalkSyncReq_SyncOper_EnumDescriptor(void);

 
BOOL PB3LiveTalkSyncReq_SyncOper_IsValidValue(int32_t value);

#pragma mark - Enum PB3ReportFeedbackReq_Feedback

typedef GPB_ENUM(PB3ReportFeedbackReq_Feedback) {
   
  PB3ReportFeedbackReq_Feedback_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3ReportFeedbackReq_Feedback_None = 0,
  PB3ReportFeedbackReq_Feedback_Satisfy = 1,
  PB3ReportFeedbackReq_Feedback_UnSatisfy = 2,
};

GPBEnumDescriptor *PB3ReportFeedbackReq_Feedback_EnumDescriptor(void);

 
BOOL PB3ReportFeedbackReq_Feedback_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveIMPush_PushType

typedef GPB_ENUM(PB3LiveIMPush_PushType) {
   
  PB3LiveIMPush_PushType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveIMPush_PushType_None = 0,

   
  PB3LiveIMPush_PushType_SomeoneCallMe = 1,

   
  PB3LiveIMPush_PushType_TargetCancel = 2,

   
  PB3LiveIMPush_PushType_TargetReceive = 3,

   
  PB3LiveIMPush_PushType_TargetDeny = 4,
};

GPBEnumDescriptor *PB3LiveIMPush_PushType_EnumDescriptor(void);

 
BOOL PB3LiveIMPush_PushType_IsValidValue(int32_t value);

#pragma mark - Enum PB3LiveTalkPush_PushType

typedef GPB_ENUM(PB3LiveTalkPush_PushType) {
   
  PB3LiveTalkPush_PushType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3LiveTalkPush_PushType_None = 0,

   
  PB3LiveTalkPush_PushType_TargetConnSucc = 1,

   
  PB3LiveTalkPush_PushType_TargetConnFail = 2,

   
  PB3LiveTalkPush_PushType_TargetExposed = 3,

   
  PB3LiveTalkPush_PushType_TargetLikeYou = 4,

   
  PB3LiveTalkPush_PushType_TargetHangup = 5,

   
  PB3LiveTalkPush_PushType_Timeout = 6,

   
  PB3LiveTalkPush_PushType_TargetHeadTouched = 7,
  PB3LiveTalkPush_PushType_TargetBodyTouched = 8,

   
  PB3LiveTalkPush_PushType_SelfHeadTouched = 9,
  PB3LiveTalkPush_PushType_SelfBodyTouched = 10,

   
  PB3LiveTalkPush_PushType_DualExposed = 11,

   
  PB3LiveTalkPush_PushType_TargetInviteShow = 12,

   
  PB3LiveTalkPush_PushType_TimeoutDelayed = 13,
};

GPBEnumDescriptor *PB3LiveTalkPush_PushType_EnumDescriptor(void);

 
BOOL PB3LiveTalkPush_PushType_IsValidValue(int32_t value);

#pragma mark - PB3LiveExtRoot

 
@interface PB3LiveExtRoot : GPBRootObject
@end

#pragma mark - PB3PlayerLiveDataPush

typedef GPB_ENUM(PB3PlayerLiveDataPush_FieldNumber) {
  PB3PlayerLiveDataPush_FieldNumber_Type = 1,
  PB3PlayerLiveDataPush_FieldNumber_Hearts = 2,
  PB3PlayerLiveDataPush_FieldNumber_FreeMatchTimes = 3,
};

 
@interface PB3PlayerLiveDataPush : GPBMessage

@property(nonatomic, readwrite) PB3PlayerLiveDataPush_PushType type;

 
@property(nonatomic, readwrite) int64_t hearts;

 
@property(nonatomic, readwrite) int64_t freeMatchTimes;

@end

 
int32_t PB3PlayerLiveDataPush_Type_RawValue(PB3PlayerLiveDataPush *message);
 
void SetPB3PlayerLiveDataPush_Type_RawValue(PB3PlayerLiveDataPush *message, int32_t value);

#pragma mark - PB3LiveSnapshot

typedef GPB_ENUM(PB3LiveSnapshot_FieldNumber) {
  PB3LiveSnapshot_FieldNumber_URL = 1,
  PB3LiveSnapshot_FieldNumber_Layer = 2,
};

@interface PB3LiveSnapshot : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) PB3LiveSnapshotLayer layer;

@end

 
int32_t PB3LiveSnapshot_Layer_RawValue(PB3LiveSnapshot *message);
 
void SetPB3LiveSnapshot_Layer_RawValue(PB3LiveSnapshot *message, int32_t value);

#pragma mark - PB3LiveModel

typedef GPB_ENUM(PB3LiveModel_FieldNumber) {
  PB3LiveModel_FieldNumber_ModelId = 1,
  PB3LiveModel_FieldNumber_ModelName = 2,
  PB3LiveModel_FieldNumber_ZipName = 3,
  PB3LiveModel_FieldNumber_ResURL = 4,
  PB3LiveModel_FieldNumber_Md5Sum = 6,
  PB3LiveModel_FieldNumber_SnapshotsArray = 7,
};

 
@interface PB3LiveModel : GPBMessage

@property(nonatomic, readwrite) int64_t modelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *modelName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *zipName;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *resURL;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *md5Sum;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3LiveSnapshot*> *snapshotsArray;
 
@property(nonatomic, readonly) NSUInteger snapshotsArray_Count;

@end

#pragma mark - PB3LiveSticker

typedef GPB_ENUM(PB3LiveSticker_FieldNumber) {
  PB3LiveSticker_FieldNumber_StickerId = 1,
  PB3LiveSticker_FieldNumber_Name = 2,
  PB3LiveSticker_FieldNumber_StickerType = 3,
  PB3LiveSticker_FieldNumber_ResURL = 4,
  PB3LiveSticker_FieldNumber_Snapshot = 5,
};

 
@interface PB3LiveSticker : GPBMessage

@property(nonatomic, readwrite) int64_t stickerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) PB3LiveStickerType stickerType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *resURL;

 
@property(nonatomic, readwrite, strong, null_resettable) PB3LiveSnapshot *snapshot;
 
@property(nonatomic, readwrite) BOOL hasSnapshot;

@end

 
int32_t PB3LiveSticker_StickerType_RawValue(PB3LiveSticker *message);
 
void SetPB3LiveSticker_StickerType_RawValue(PB3LiveSticker *message, int32_t value);

#pragma mark - PB3LiveTalkReq

typedef GPB_ENUM(PB3LiveTalkReq_FieldNumber) {
  PB3LiveTalkReq_FieldNumber_ChannelId = 1,
};

 
@interface PB3LiveTalkReq : GPBMessage

@property(nonatomic, readwrite) int64_t channelId;

@end

#pragma mark - PB3LiveTalkRes

typedef GPB_ENUM(PB3LiveTalkRes_FieldNumber) {
  PB3LiveTalkRes_FieldNumber_TargetPlayer = 1,
  PB3LiveTalkRes_FieldNumber_SelfShowCodeName = 2,
  PB3LiveTalkRes_FieldNumber_TargetShowCodeName = 3,
  PB3LiveTalkRes_FieldNumber_TimeOut = 4,
  PB3LiveTalkRes_FieldNumber_Scene = 5,
  PB3LiveTalkRes_FieldNumber_MatchTipsArray = 6,
  PB3LiveTalkRes_FieldNumber_LikeTarget = 9,
  PB3LiveTalkRes_FieldNumber_TalkTime = 10,
};

@interface PB3LiveTalkRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) PB3PlayerInfo *targetPlayer;
 
@property(nonatomic, readwrite) BOOL hasTargetPlayer;

 
@property(nonatomic, readwrite) BOOL selfShowCodeName;

 
@property(nonatomic, readwrite) BOOL targetShowCodeName;

 
@property(nonatomic, readwrite) int64_t timeOut;

@property(nonatomic, readwrite) PB3LiveChannelScene scene;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *matchTipsArray;
 
@property(nonatomic, readonly) NSUInteger matchTipsArray_Count;

 
@property(nonatomic, readwrite) BOOL likeTarget;

 
@property(nonatomic, readwrite) int64_t talkTime;

@end

 
int32_t PB3LiveTalkRes_Scene_RawValue(PB3LiveTalkRes *message);
 
void SetPB3LiveTalkRes_Scene_RawValue(PB3LiveTalkRes *message, int32_t value);

#pragma mark - PB3GetVoiceIdentifyConfReq

 
@interface PB3GetVoiceIdentifyConfReq : GPBMessage

@end

#pragma mark - PB3GetVoiceIdentifyConfRes

typedef GPB_ENUM(PB3GetVoiceIdentifyConfRes_FieldNumber) {
  PB3GetVoiceIdentifyConfRes_FieldNumber_CostGold = 1,
  PB3GetVoiceIdentifyConfRes_FieldNumber_DescURL = 2,
  PB3GetVoiceIdentifyConfRes_FieldNumber_FreeTimes = 3,
  PB3GetVoiceIdentifyConfRes_FieldNumber_PromptsArray = 4,
  PB3GetVoiceIdentifyConfRes_FieldNumber_QrCodeURL = 5,
};

@interface PB3GetVoiceIdentifyConfRes : GPBMessage

 
@property(nonatomic, readwrite) int64_t costGold;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *descURL;

 
@property(nonatomic, readwrite) int64_t freeTimes;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3GetVoiceIdentifyConfRes_Prompt*> *promptsArray;
 
@property(nonatomic, readonly) NSUInteger promptsArray_Count;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *qrCodeURL;

@end

#pragma mark - PB3GetVoiceIdentifyConfRes_Prompt

typedef GPB_ENUM(PB3GetVoiceIdentifyConfRes_Prompt_FieldNumber) {
  PB3GetVoiceIdentifyConfRes_Prompt_FieldNumber_Title = 1,
  PB3GetVoiceIdentifyConfRes_Prompt_FieldNumber_Text = 2,
};

@interface PB3GetVoiceIdentifyConfRes_Prompt : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

#pragma mark - PB3VoiceIdentifyReq

typedef GPB_ENUM(PB3VoiceIdentifyReq_FieldNumber) {
  PB3VoiceIdentifyReq_FieldNumber_Gender = 1,
  PB3VoiceIdentifyReq_FieldNumber_VoiceURL = 2,
};

 
@interface PB3VoiceIdentifyReq : GPBMessage

 
@property(nonatomic, readwrite) enum PB3SexType gender;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *voiceURL;

@end

 
int32_t PB3VoiceIdentifyReq_Gender_RawValue(PB3VoiceIdentifyReq *message);
 
void SetPB3VoiceIdentifyReq_Gender_RawValue(PB3VoiceIdentifyReq *message, int32_t value);

#pragma mark - PB3VoiceIdentifyRes

typedef GPB_ENUM(PB3VoiceIdentifyRes_FieldNumber) {
  PB3VoiceIdentifyRes_FieldNumber_VoiceFeature = 1,
  PB3VoiceIdentifyRes_FieldNumber_Character = 2,
  PB3VoiceIdentifyRes_FieldNumber_FreeTimes = 3,
  PB3VoiceIdentifyRes_FieldNumber_CostGold = 4,
};

@interface PB3VoiceIdentifyRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) PB3VoiceFeature *voiceFeature;
 
@property(nonatomic, readwrite) BOOL hasVoiceFeature;

 
@property(nonatomic, readwrite, strong, null_resettable) PB3LiveCharacter *character;
 
@property(nonatomic, readwrite) BOOL hasCharacter;

 
@property(nonatomic, readwrite) int64_t freeTimes;

 
@property(nonatomic, readwrite) int64_t costGold;

@end

#pragma mark - PB3GetLiveMatchConfReq

 
@interface PB3GetLiveMatchConfReq : GPBMessage

@end

#pragma mark - PB3GetLiveMatchConfRes

typedef GPB_ENUM(PB3GetLiveMatchConfRes_FieldNumber) {
  PB3GetLiveMatchConfRes_FieldNumber_FreeTimes = 2,
  PB3GetLiveMatchConfRes_FieldNumber_MatchCostGold = 3,
  PB3GetLiveMatchConfRes_FieldNumber_DelayCostGold = 4,
  PB3GetLiveMatchConfRes_FieldNumber_TimeOut = 5,
  PB3GetLiveMatchConfRes_FieldNumber_DelayCostGift = 6,
  PB3GetLiveMatchConfRes_FieldNumber_GoldDelayTime = 7,
  PB3GetLiveMatchConfRes_FieldNumber_GiftDelayTime = 8,
};

@interface PB3GetLiveMatchConfRes : GPBMessage

 
@property(nonatomic, readwrite) int64_t freeTimes;

 
@property(nonatomic, readwrite) int64_t matchCostGold;

 
@property(nonatomic, readwrite) int64_t delayCostGold;

 
@property(nonatomic, readwrite) int64_t timeOut;

 
@property(nonatomic, readwrite) int64_t delayCostGift;

 
@property(nonatomic, readwrite) int64_t goldDelayTime;

 
@property(nonatomic, readwrite) int64_t giftDelayTime;

@end

#pragma mark - PB3LiveMatchReq

typedef GPB_ENUM(PB3LiveMatchReq_FieldNumber) {
  PB3LiveMatchReq_FieldNumber_Oper = 2,
};

 
@interface PB3LiveMatchReq : GPBMessage

 
@property(nonatomic, readwrite) PB3LiveMatchReq_MatchOper oper;

@end

 
int32_t PB3LiveMatchReq_Oper_RawValue(PB3LiveMatchReq *message);
 
void SetPB3LiveMatchReq_Oper_RawValue(PB3LiveMatchReq *message, int32_t value);

#pragma mark - PB3LiveMatchRes

typedef GPB_ENUM(PB3LiveMatchRes_FieldNumber) {
  PB3LiveMatchRes_FieldNumber_FeedbackTipsArray = 1,
  PB3LiveMatchRes_FieldNumber_RecommendArray = 9,
};

 
@interface PB3LiveMatchRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *feedbackTipsArray;
 
@property(nonatomic, readonly) NSUInteger feedbackTipsArray_Count;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3LiveMatchRes_LiveRecommend*> *recommendArray;
 
@property(nonatomic, readonly) NSUInteger recommendArray_Count;

@end

#pragma mark - PB3LiveMatchRes_LiveRecommend

typedef GPB_ENUM(PB3LiveMatchRes_LiveRecommend_FieldNumber) {
  PB3LiveMatchRes_LiveRecommend_FieldNumber_PlayerId = 1,
  PB3LiveMatchRes_LiveRecommend_FieldNumber_Icon = 2,
  PB3LiveMatchRes_LiveRecommend_FieldNumber_Router = 3,
};

@interface PB3LiveMatchRes_LiveRecommend : GPBMessage

@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

@property(nonatomic, readwrite, copy, null_resettable) NSString *router;

@end

#pragma mark - PB3LiveCallInviteReq

typedef GPB_ENUM(PB3LiveCallInviteReq_FieldNumber) {
  PB3LiveCallInviteReq_FieldNumber_TargetPlayerId = 1,
  PB3LiveCallInviteReq_FieldNumber_Oper = 2,
};

 
@interface PB3LiveCallInviteReq : GPBMessage

@property(nonatomic, readwrite) int64_t targetPlayerId;

@property(nonatomic, readwrite) PB3LiveCallInviteReq_InviteOper oper;

@end

 
int32_t PB3LiveCallInviteReq_Oper_RawValue(PB3LiveCallInviteReq *message);
 
void SetPB3LiveCallInviteReq_Oper_RawValue(PB3LiveCallInviteReq *message, int32_t value);

#pragma mark - PB3LiveCallInviteRes

typedef GPB_ENUM(PB3LiveCallInviteRes_FieldNumber) {
  PB3LiveCallInviteRes_FieldNumber_TargetPlayerInfo = 1,
};

@interface PB3LiveCallInviteRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) PB3PlayerInfo *targetPlayerInfo;
 
@property(nonatomic, readwrite) BOOL hasTargetPlayerInfo;

@end

#pragma mark - PB3LiveCallReplyReq

typedef GPB_ENUM(PB3LiveCallReplyReq_FieldNumber) {
  PB3LiveCallReplyReq_FieldNumber_Oper = 1,
  PB3LiveCallReplyReq_FieldNumber_TargetPlayerId = 2,
};

 
@interface PB3LiveCallReplyReq : GPBMessage

@property(nonatomic, readwrite) PB3LiveCallReplyReq_ReplyOper oper;

@property(nonatomic, readwrite) int64_t targetPlayerId;

@end

 
int32_t PB3LiveCallReplyReq_Oper_RawValue(PB3LiveCallReplyReq *message);
 
void SetPB3LiveCallReplyReq_Oper_RawValue(PB3LiveCallReplyReq *message, int32_t value);

#pragma mark - PB3LiveCallReplyRes

@interface PB3LiveCallReplyRes : GPBMessage

@end

#pragma mark - PB3LiveTalkSyncReq

typedef GPB_ENUM(PB3LiveTalkSyncReq_FieldNumber) {
  PB3LiveTalkSyncReq_FieldNumber_Oper = 1,
  PB3LiveTalkSyncReq_FieldNumber_ActionIdx = 2,
};

 
@interface PB3LiveTalkSyncReq : GPBMessage

@property(nonatomic, readwrite) PB3LiveTalkSyncReq_SyncOper oper;

 
@property(nonatomic, readwrite) int64_t actionIdx;

@end

 
int32_t PB3LiveTalkSyncReq_Oper_RawValue(PB3LiveTalkSyncReq *message);
 
void SetPB3LiveTalkSyncReq_Oper_RawValue(PB3LiveTalkSyncReq *message, int32_t value);

#pragma mark - PB3LiveTalkSyncRes

typedef GPB_ENUM(PB3LiveTalkSyncRes_FieldNumber) {
  PB3LiveTalkSyncRes_FieldNumber_TalkTime = 1,
};

@interface PB3LiveTalkSyncRes : GPBMessage

 
@property(nonatomic, readwrite) int64_t talkTime;

@end

#pragma mark - PB3LiveTalkDelayReq

 
@interface PB3LiveTalkDelayReq : GPBMessage

@end

#pragma mark - PB3LiveTalkDelayRes

typedef GPB_ENUM(PB3LiveTalkDelayRes_FieldNumber) {
  PB3LiveTalkDelayRes_FieldNumber_TimeOut = 1,
  PB3LiveTalkDelayRes_FieldNumber_CostGold = 2,
};

@interface PB3LiveTalkDelayRes : GPBMessage

@property(nonatomic, readwrite) int64_t timeOut;

 
@property(nonatomic, readwrite) int64_t costGold;

@end

#pragma mark - PB3ReportFeedbackReq

typedef GPB_ENUM(PB3ReportFeedbackReq_FieldNumber) {
  PB3ReportFeedbackReq_FieldNumber_Content = 1,
  PB3ReportFeedbackReq_FieldNumber_TipsArray = 2,
  PB3ReportFeedbackReq_FieldNumber_TargetId = 3,
  PB3ReportFeedbackReq_FieldNumber_FeedBack = 4,
};

 
@interface PB3ReportFeedbackReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tipsArray;
 
@property(nonatomic, readonly) NSUInteger tipsArray_Count;

 
@property(nonatomic, readwrite) int64_t targetId;

 
@property(nonatomic, readwrite) PB3ReportFeedbackReq_Feedback feedBack;

@end

 
int32_t PB3ReportFeedbackReq_FeedBack_RawValue(PB3ReportFeedbackReq *message);
 
void SetPB3ReportFeedbackReq_FeedBack_RawValue(PB3ReportFeedbackReq *message, int32_t value);

#pragma mark - PB3ReportFeedbackRes

@interface PB3ReportFeedbackRes : GPBMessage

@end

#pragma mark - PB3ClearCharacterReq

 
@interface PB3ClearCharacterReq : GPBMessage

@end

#pragma mark - PB3ClearCharacterRes

@interface PB3ClearCharacterRes : GPBMessage

@end

#pragma mark - PB3ResetCodenameReq

 
@interface PB3ResetCodenameReq : GPBMessage

@end

#pragma mark - PB3ResetCodenameRes

typedef GPB_ENUM(PB3ResetCodenameRes_FieldNumber) {
  PB3ResetCodenameRes_FieldNumber_CodeName = 1,
};

@interface PB3ResetCodenameRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *codeName;

@end

#pragma mark - PB3GetVoiceFeatureReq

 
@interface PB3GetVoiceFeatureReq : GPBMessage

@end

#pragma mark - PB3GetVoiceFeatureRes

typedef GPB_ENUM(PB3GetVoiceFeatureRes_FieldNumber) {
  PB3GetVoiceFeatureRes_FieldNumber_Feature = 1,
  PB3GetVoiceFeatureRes_FieldNumber_FreeClearTimes = 2,
  PB3GetVoiceFeatureRes_FieldNumber_ClearCostGold = 3,
  PB3GetVoiceFeatureRes_FieldNumber_QrCodeURL = 5,
};

@interface PB3GetVoiceFeatureRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PB3VoiceFeature *feature;
 
@property(nonatomic, readwrite) BOOL hasFeature;

 
@property(nonatomic, readwrite) int64_t freeClearTimes;

 
@property(nonatomic, readwrite) int64_t clearCostGold;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *qrCodeURL;

@end

#pragma mark - PB3CanLiveCallInviteReq

typedef GPB_ENUM(PB3CanLiveCallInviteReq_FieldNumber) {
  PB3CanLiveCallInviteReq_FieldNumber_TargetId = 1,
};

 
@interface PB3CanLiveCallInviteReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t targetId;

@end

#pragma mark - PB3CanLiveCallInviteRes

 
@interface PB3CanLiveCallInviteRes : GPBMessage

@end

#pragma mark - PB3LiveChannelPush

typedef GPB_ENUM(PB3LiveChannelPush_FieldNumber) {
  PB3LiveChannelPush_FieldNumber_ChannelId = 1,
  PB3LiveChannelPush_FieldNumber_Token = 2,
  PB3LiveChannelPush_FieldNumber_Scene = 3,
  PB3LiveChannelPush_FieldNumber_Caller = 4,
};

 
@interface PB3LiveChannelPush : GPBMessage

@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite) PB3LiveChannelScene scene;

 
@property(nonatomic, readwrite) int64_t caller;

@end

 
int32_t PB3LiveChannelPush_Scene_RawValue(PB3LiveChannelPush *message);
 
void SetPB3LiveChannelPush_Scene_RawValue(PB3LiveChannelPush *message, int32_t value);

#pragma mark - PB3LiveIMPush

typedef GPB_ENUM(PB3LiveIMPush_FieldNumber) {
  PB3LiveIMPush_FieldNumber_Type = 1,
  PB3LiveIMPush_FieldNumber_TargetPlayerInfo = 2,
  PB3LiveIMPush_FieldNumber_Caller = 4,
};

 
@interface PB3LiveIMPush : GPBMessage

@property(nonatomic, readwrite) PB3LiveIMPush_PushType type;

 
@property(nonatomic, readwrite, strong, null_resettable) PB3PlayerInfo *targetPlayerInfo;
 
@property(nonatomic, readwrite) BOOL hasTargetPlayerInfo;

 
@property(nonatomic, readwrite) int64_t caller;

@end

 
int32_t PB3LiveIMPush_Type_RawValue(PB3LiveIMPush *message);
 
void SetPB3LiveIMPush_Type_RawValue(PB3LiveIMPush *message, int32_t value);

#pragma mark - PB3LiveTalkPush

typedef GPB_ENUM(PB3LiveTalkPush_FieldNumber) {
  PB3LiveTalkPush_FieldNumber_Type = 1,
  PB3LiveTalkPush_FieldNumber_TimeOut = 2,
  PB3LiveTalkPush_FieldNumber_ActionIdx = 3,
  PB3LiveTalkPush_FieldNumber_TalkTime = 4,
  PB3LiveTalkPush_FieldNumber_TargetPlayer = 5,
};

 
@interface PB3LiveTalkPush : GPBMessage

@property(nonatomic, readwrite) PB3LiveTalkPush_PushType type;

 
@property(nonatomic, readwrite) int64_t timeOut;

 
@property(nonatomic, readwrite) int64_t actionIdx;

 
@property(nonatomic, readwrite) int64_t talkTime;

 
@property(nonatomic, readwrite, strong, null_resettable) PB3PlayerInfo *targetPlayer;
 
@property(nonatomic, readwrite) BOOL hasTargetPlayer;

@end

 
int32_t PB3LiveTalkPush_Type_RawValue(PB3LiveTalkPush *message);
 
void SetPB3LiveTalkPush_Type_RawValue(PB3LiveTalkPush *message, int32_t value);

#pragma mark - PB3GetLiveAssetsConfReq

 
@interface PB3GetLiveAssetsConfReq : GPBMessage

@end

#pragma mark - PB3GetLiveAssetsConfRes

typedef GPB_ENUM(PB3GetLiveAssetsConfRes_FieldNumber) {
  PB3GetLiveAssetsConfRes_FieldNumber_Models = 1,
  PB3GetLiveAssetsConfRes_FieldNumber_Stickers = 2,
};

@interface PB3GetLiveAssetsConfRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64ObjectDictionary<PB3LiveModel*> *models;
 
@property(nonatomic, readonly) NSUInteger models_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64ObjectDictionary<PB3LiveSticker*> *stickers;
 
@property(nonatomic, readonly) NSUInteger stickers_Count;

@end

#pragma mark - PB3RestoreLiveStatusReq

@interface PB3RestoreLiveStatusReq : GPBMessage

@end

#pragma mark - PB3RestoreLiveStatusRes

typedef GPB_ENUM(PB3RestoreLiveStatusRes_FieldNumber) {
  PB3RestoreLiveStatusRes_FieldNumber_Talk = 1,
  PB3RestoreLiveStatusRes_FieldNumber_Im = 2,
};

@interface PB3RestoreLiveStatusRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) PB3LiveChannelPush *talk;
 
@property(nonatomic, readwrite) BOOL hasTalk;

 
@property(nonatomic, readwrite, strong, null_resettable) PB3LiveIMPush *im;
 
@property(nonatomic, readwrite) BOOL hasIm;

@end

#pragma mark - PB3SwitchTelepathyReq

typedef GPB_ENUM(PB3SwitchTelepathyReq_FieldNumber) {
  PB3SwitchTelepathyReq_FieldNumber_Telepathic = 1,
};

 
@interface PB3SwitchTelepathyReq : GPBMessage

 
@property(nonatomic, readwrite) BOOL telepathic;

@end

#pragma mark - PB3SwitchTelepathyRes

@interface PB3SwitchTelepathyRes : GPBMessage

@end

#pragma mark - PB3ReportClickChatTelepathyReq

typedef GPB_ENUM(PB3ReportClickChatTelepathyReq_FieldNumber) {
  PB3ReportClickChatTelepathyReq_FieldNumber_TelepathyId = 1,
};

 
@interface PB3ReportClickChatTelepathyReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t telepathyId;

@end

#pragma mark - PB3ReportClickChatTelepathyRes

@interface PB3ReportClickChatTelepathyRes : GPBMessage

@end

#pragma mark - PB3PushTelepathyPopupData

typedef GPB_ENUM(PB3PushTelepathyPopupData_FieldNumber) {
  PB3PushTelepathyPopupData_FieldNumber_PlayerId = 1,
  PB3PushTelepathyPopupData_FieldNumber_Icon = 2,
  PB3PushTelepathyPopupData_FieldNumber_Nickname = 3,
  PB3PushTelepathyPopupData_FieldNumber_Constellation = 4,
  PB3PushTelepathyPopupData_FieldNumber_MatchingDegree = 5,
  PB3PushTelepathyPopupData_FieldNumber_TelepathyId = 6,
  PB3PushTelepathyPopupData_FieldNumber_Gender = 7,
  PB3PushTelepathyPopupData_FieldNumber_Switch_p = 8,
  PB3PushTelepathyPopupData_FieldNumber_GreetingsId = 9,
  PB3PushTelepathyPopupData_FieldNumber_Greetings = 10,
  PB3PushTelepathyPopupData_FieldNumber_LabelArray = 11,
};

@interface PB3PushTelepathyPopupData : GPBMessage

 
@property(nonatomic, readwrite) int64_t playerId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *constellation;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *matchingDegree;

 
@property(nonatomic, readwrite) int64_t telepathyId;

 
@property(nonatomic, readwrite) enum PB3SexType gender;

 
@property(nonatomic, readwrite) BOOL switch_p;

 
@property(nonatomic, readwrite) int64_t greetingsId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *greetings;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *labelArray;
 
@property(nonatomic, readonly) NSUInteger labelArray_Count;

@end

 
int32_t PB3PushTelepathyPopupData_Gender_RawValue(PB3PushTelepathyPopupData *message);
 
void SetPB3PushTelepathyPopupData_Gender_RawValue(PB3PushTelepathyPopupData *message, int32_t value);

#pragma mark - PB3ReportGreetingsUsedReq

typedef GPB_ENUM(PB3ReportGreetingsUsedReq_FieldNumber) {
  PB3ReportGreetingsUsedReq_FieldNumber_GreetingsId = 1,
};

 
@interface PB3ReportGreetingsUsedReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t greetingsId;

@end

#pragma mark - PB3ReportGreetingsUsedRes

@interface PB3ReportGreetingsUsedRes : GPBMessage

@end

#pragma mark - PB3GetPlayerLiveCharacterReq

typedef GPB_ENUM(PB3GetPlayerLiveCharacterReq_FieldNumber) {
  PB3GetPlayerLiveCharacterReq_FieldNumber_PlayerId = 1,
};

@interface PB3GetPlayerLiveCharacterReq : GPBMessage

@property(nonatomic, readwrite) int64_t playerId;

@end

#pragma mark - PB3GetPlayerLiveCharacterRes

typedef GPB_ENUM(PB3GetPlayerLiveCharacterRes_FieldNumber) {
  PB3GetPlayerLiveCharacterRes_FieldNumber_Character = 1,
};

@interface PB3GetPlayerLiveCharacterRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PB3LiveCharacter *character;
 
@property(nonatomic, readwrite) BOOL hasCharacter;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

 
