 
 

 
 
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3BarIndexEntry;
@class PB3IndexBannerV2;
@class PB3IndexEntry;
@class PB3ModIndexEntry;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB3NavPosition

 
typedef GPB_ENUM(PB3NavPosition) {
   
  PB3NavPosition_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PB3NavPosition_NpIndexDefault = 0,

   
  PB3NavPosition_NpIndexSubWin = 1,
};

GPBEnumDescriptor *PB3NavPosition_EnumDescriptor(void);

 
BOOL PB3NavPosition_IsValidValue(int32_t value);

#pragma mark - PB3PcindexExtRoot

 
@interface PB3PcindexExtRoot : GPBRootObject
@end

#pragma mark - PB3ModIndexEntry

typedef GPB_ENUM(PB3ModIndexEntry_FieldNumber) {
  PB3ModIndexEntry_FieldNumber_Index = 1,
  PB3ModIndexEntry_FieldNumber_Name = 2,
  PB3ModIndexEntry_FieldNumber_ExpandWeight = 3,
  PB3ModIndexEntry_FieldNumber_DataSourceAttribute = 4,
  PB3ModIndexEntry_FieldNumber_LinkAppModId = 5,
  PB3ModIndexEntry_FieldNumber_SortIcon = 6,
  PB3ModIndexEntry_FieldNumber_NameIsVisible = 7,
};

 
@interface PB3ModIndexEntry : GPBMessage

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite) int32_t expandWeight;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *dataSourceAttribute;

 
@property(nonatomic, readwrite) int32_t linkAppModId;

 
@property(nonatomic, readwrite) BOOL sortIcon;

 
@property(nonatomic, readwrite) BOOL nameIsVisible;

@end

#pragma mark - PB3BarIndexEntry

typedef GPB_ENUM(PB3BarIndexEntry_FieldNumber) {
  PB3BarIndexEntry_FieldNumber_ModsArray = 1,
  PB3BarIndexEntry_FieldNumber_Index = 2,
  PB3BarIndexEntry_FieldNumber_Name = 3,
  PB3BarIndexEntry_FieldNumber_Attribute = 4,
  PB3BarIndexEntry_FieldNumber_IsSelected = 5,
  PB3BarIndexEntry_FieldNumber_Position = 6,
};

 
@interface PB3BarIndexEntry : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3ModIndexEntry*> *modsArray;
 
@property(nonatomic, readonly) NSUInteger modsArray_Count;

 
@property(nonatomic, readwrite) int32_t index;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite) int32_t attribute;

 
@property(nonatomic, readwrite) BOOL isSelected;

 
@property(nonatomic, readwrite) PB3NavPosition position;

@end

 
int32_t PB3BarIndexEntry_Position_RawValue(PB3BarIndexEntry *message);
 
void SetPB3BarIndexEntry_Position_RawValue(PB3BarIndexEntry *message, int32_t value);

#pragma mark - PB3NavigationBarV2Req

 
@interface PB3NavigationBarV2Req : GPBMessage

@end

#pragma mark - PB3NavigationBarV2Res

typedef GPB_ENUM(PB3NavigationBarV2Res_FieldNumber) {
  PB3NavigationBarV2Res_FieldNumber_TabsArray = 1,
};

 
@interface PB3NavigationBarV2Res : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3BarIndexEntry*> *tabsArray;
 
@property(nonatomic, readonly) NSUInteger tabsArray_Count;

@end

#pragma mark - PB3BarListV2Req

typedef GPB_ENUM(PB3BarListV2Req_FieldNumber) {
  PB3BarListV2Req_FieldNumber_BarIndex = 1,
  PB3BarListV2Req_FieldNumber_ModIndex = 2,
  PB3BarListV2Req_FieldNumber_Page = 3,
};

 
@interface PB3BarListV2Req : GPBMessage

 
@property(nonatomic, readwrite) int32_t barIndex;

 
@property(nonatomic, readwrite) int32_t modIndex;

 
@property(nonatomic, readwrite) int32_t page;

@end

#pragma mark - PB3BarListV2Res

typedef GPB_ENUM(PB3BarListV2Res_FieldNumber) {
  PB3BarListV2Res_FieldNumber_BarsArray = 1,
  PB3BarListV2Res_FieldNumber_SortIcon = 2,
  PB3BarListV2Res_FieldNumber_IsVisible = 3,
  PB3BarListV2Res_FieldNumber_NameIsVisible = 4,
};

 
@interface PB3BarListV2Res : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3IndexEntry*> *barsArray;
 
@property(nonatomic, readonly) NSUInteger barsArray_Count;

 
@property(nonatomic, readwrite) BOOL sortIcon;

 
@property(nonatomic, readwrite) BOOL isVisible;

 
@property(nonatomic, readwrite) BOOL nameIsVisible;

@end

#pragma mark - PB3UpgradeVersionReq

typedef GPB_ENUM(PB3UpgradeVersionReq_FieldNumber) {
  PB3UpgradeVersionReq_FieldNumber_Uid = 1,
  PB3UpgradeVersionReq_FieldNumber_SourceVersion = 2,
  PB3UpgradeVersionReq_FieldNumber_Channel = 3,
};

 
@interface PB3UpgradeVersionReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t uid;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceVersion;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

@end

#pragma mark - PB3UpgradeVersionRes

typedef GPB_ENUM(PB3UpgradeVersionRes_FieldNumber) {
  PB3UpgradeVersionRes_FieldNumber_Vid = 1,
  PB3UpgradeVersionRes_FieldNumber_TargetVersion = 2,
  PB3UpgradeVersionRes_FieldNumber_Type = 3,
  PB3UpgradeVersionRes_FieldNumber_Description_p = 4,
  PB3UpgradeVersionRes_FieldNumber_Pkg = 5,
};

@interface PB3UpgradeVersionRes : GPBMessage

 
@property(nonatomic, readwrite) int32_t vid;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetVersion;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *pkg;

@end

#pragma mark - PB3UpgradeCountReq

typedef GPB_ENUM(PB3UpgradeCountReq_FieldNumber) {
  PB3UpgradeCountReq_FieldNumber_Uid = 1,
  PB3UpgradeCountReq_FieldNumber_Vid = 2,
  PB3UpgradeCountReq_FieldNumber_TargetVersion = 3,
};

 
@interface PB3UpgradeCountReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t uid;

 
@property(nonatomic, readwrite) int32_t vid;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetVersion;

@end

#pragma mark - PB3UpgradeCountRes

@interface PB3UpgradeCountRes : GPBMessage

@end

#pragma mark - PB3IndexBannerV2Req

typedef GPB_ENUM(PB3IndexBannerV2Req_FieldNumber) {
  PB3IndexBannerV2Req_FieldNumber_ModIndex = 1,
};

 
@interface PB3IndexBannerV2Req : GPBMessage

 
@property(nonatomic, readwrite) int32_t modIndex;

@end

#pragma mark - PB3IndexBannerV2

typedef GPB_ENUM(PB3IndexBannerV2_FieldNumber) {
  PB3IndexBannerV2_FieldNumber_Name = 1,
  PB3IndexBannerV2_FieldNumber_BannerURL = 2,
  PB3IndexBannerV2_FieldNumber_TranURL = 3,
};

 
@interface PB3IndexBannerV2 : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bannerURL;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *tranURL;

@end

#pragma mark - PB3IndexBannerV2Res

typedef GPB_ENUM(PB3IndexBannerV2Res_FieldNumber) {
  PB3IndexBannerV2Res_FieldNumber_ListArray = 1,
};

 
@interface PB3IndexBannerV2Res : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB3IndexBannerV2*> *listArray;
 
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

 
