 
 

 
 
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PROTOCommonSignInRes;
@class PROTODeviceMessage;
@class PROTOGoldCard;
@class PROTOGoogleIABNotifyReq_BuyIntent;
@class PROTOGoogleIABProductItem;
@class PROTOThirdAccountBindInfo;
@class PROTOThirdAccountBindInfoData;
@class PROTOThirdAccountBindQqInfo;
@class PROTOThirdAccountBindWeChatInfo;
@class PROTOUserInfo;
@class PROTOVIPChargeItem;
@class PROTOVIPChargeLogs;
GPB_ENUM_FWD_DECLARE(PROTOUauthLoginType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PROTOErrorUAuthCode

typedef GPB_ENUM(PROTOErrorUAuthCode) {
   
  PROTOErrorUAuthCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PROTOErrorUAuthCode_ErrorUauthZero = 0,

   
  PROTOErrorUAuthCode_ErrorUauthRegisterParam = 39001,

   
  PROTOErrorUAuthCode_ErrorUauthAccountExist = 39002,

   
  PROTOErrorUAuthCode_ErrorUauthSessionTimeOut = 39003,

   
  PROTOErrorUAuthCode_ErrorUauthSessionNotFound = 39004,

   
  PROTOErrorUAuthCode_ErrorUauthUserNotFound = 39005,

   
  PROTOErrorUAuthCode_ErrorUauthAccountNotExist = 39006,

   
  PROTOErrorUAuthCode_ErrorUauthPassWordNoCorrect = 39007,

   
  PROTOErrorUAuthCode_ErrorUauthCodeIncorrect = 39008,

   
  PROTOErrorUAuthCode_ErrorUauthPhoneNotExist = 39009,

   
  PROTOErrorUAuthCode_ErrorUauthUserNoRight = 39010,

   
  PROTOErrorUAuthCode_ErrorUauthInvalidWay = 39011,

   
  PROTOErrorUAuthCode_ErrorUauthNeedLogin = 39012,

   
  PROTOErrorUAuthCode_ErrorUauthGetToken = 39013,

   
  PROTOErrorUAuthCode_ErrorUauthAccessToken = 39014,

   
  PROTOErrorUAuthCode_ErrorUauthWrongPhoneNum = 39015,

   
  PROTOErrorUAuthCode_ErrorUauthServerOffLine = 39016,

   
  PROTOErrorUAuthCode_ErrorUauthPhoneAlreadyExist = 39017,

   
  PROTOErrorUAuthCode_ErrorIaphasNoOrder = 239018,

   
  PROTOErrorUAuthCode_ErrorCheckIaporder = 239019,

   
  PROTOErrorUAuthCode_ErrorCheckIapbundleId = 239020,

   
  PROTOErrorUAuthCode_ErrorTooFrequent = 239030,

   
  PROTOErrorUAuthCode_Error3Rd = 239031,

   
  PROTOErrorUAuthCode_ErrorPasswordInvalid = 239032,

   
  PROTOErrorUAuthCode_ErrorWrongOldPassword = 239033,

   
  PROTOErrorUAuthCode_ErrorLoginBlack = 239034,

   
  PROTOErrorUAuthCode_ErrorHasAccount = 239035,

   
  PROTOErrorUAuthCode_ErrorUauthPswNoCorrect = 239036,

   
  PROTOErrorUAuthCode_ErrorUauthPhoneNoCorrect = 239037,

   
  PROTOErrorUAuthCode_ErrorUserLimitLogin = 239058,
};

GPBEnumDescriptor *PROTOErrorUAuthCode_EnumDescriptor(void);

 
BOOL PROTOErrorUAuthCode_IsValidValue(int32_t value);

#pragma mark - Enum PROTOIAPStatusType

typedef GPB_ENUM(PROTOIAPStatusType) {
   
  PROTOIAPStatusType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PROTOIAPStatusType_IapNone = 0,

   
  PROTOIAPStatusType_IapStatusFail = 1,

   
  PROTOIAPStatusType_IapStatusCancel = 2,
};

GPBEnumDescriptor *PROTOIAPStatusType_EnumDescriptor(void);

 
BOOL PROTOIAPStatusType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOChargeStatus

typedef GPB_ENUM(PROTOChargeStatus) {
   
  PROTOChargeStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOChargeStatus_CsCharging = 0,

   
  PROTOChargeStatus_CsFinish = 1,

   
  PROTOChargeStatus_CsRefund = 2,
};

GPBEnumDescriptor *PROTOChargeStatus_EnumDescriptor(void);

 
BOOL PROTOChargeStatus_IsValidValue(int32_t value);

#pragma mark - Enum PROTOReportDataType

typedef GPB_ENUM(PROTOReportDataType) {
   
  PROTOReportDataType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOReportDataType_RdtNull = 0,

   
  PROTOReportDataType_RdtCmbVipExpedited = 1,
};

GPBEnumDescriptor *PROTOReportDataType_EnumDescriptor(void);

 
BOOL PROTOReportDataType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOVerifyType

typedef GPB_ENUM(PROTOVerifyType) {
   
  PROTOVerifyType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOVerifyType_VtNull = 0,

   
  PROTOVerifyType_VtRemoteLogin = 1,

   
  PROTOVerifyType_VtProtect = 2,

   
  PROTOVerifyType_VtAnomalyLogin = 3,
};

GPBEnumDescriptor *PROTOVerifyType_EnumDescriptor(void);

 
BOOL PROTOVerifyType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOSMSCodeTpl

typedef GPB_ENUM(PROTOSMSCodeTpl) {
   
  PROTOSMSCodeTpl_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOSMSCodeTpl_SmscodeTplZero = 0,

   
  PROTOSMSCodeTpl_SmscodeTplLogin = 1,

   
  PROTOSMSCodeTpl_SmscodeTplResetPwd = 2,

   
  PROTOSMSCodeTpl_SmscodeTplVerifyCode = 3,
};

GPBEnumDescriptor *PROTOSMSCodeTpl_EnumDescriptor(void);

 
BOOL PROTOSMSCodeTpl_IsValidValue(int32_t value);

#pragma mark - Enum PROTOCertifyType

 
typedef GPB_ENUM(PROTOCertifyType) {
   
  PROTOCertifyType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOCertifyType_CtNone = 0,

   
  PROTOCertifyType_CtIdCard = 1,
};

GPBEnumDescriptor *PROTOCertifyType_EnumDescriptor(void);

 
BOOL PROTOCertifyType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOThirdAccountBindType

 
typedef GPB_ENUM(PROTOThirdAccountBindType) {
   
  PROTOThirdAccountBindType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOThirdAccountBindType_TabtNone = 0,

   
  PROTOThirdAccountBindType_TabtWeixin = 1,

   
  PROTOThirdAccountBindType_TabtQq = 2,
};

GPBEnumDescriptor *PROTOThirdAccountBindType_EnumDescriptor(void);

 
BOOL PROTOThirdAccountBindType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOUnbindThirdAccountOptType

 
typedef GPB_ENUM(PROTOUnbindThirdAccountOptType) {
   
  PROTOUnbindThirdAccountOptType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
   
  PROTOUnbindThirdAccountOptType_UtaotSend = 0,

   
  PROTOUnbindThirdAccountOptType_UtaotVerify = 1,
};

GPBEnumDescriptor *PROTOUnbindThirdAccountOptType_EnumDescriptor(void);

 
BOOL PROTOUnbindThirdAccountOptType_IsValidValue(int32_t value);

#pragma mark - PROTOUauthExtRoot

 
@interface PROTOUauthExtRoot : GPBRootObject
@end

#pragma mark - PROTOVerifyIAPReq

typedef GPB_ENUM(PROTOVerifyIAPReq_FieldNumber) {
  PROTOVerifyIAPReq_FieldNumber_AccountId = 1,
  PROTOVerifyIAPReq_FieldNumber_Receipt = 2,
  PROTOVerifyIAPReq_FieldNumber_TransactionId = 3,
  PROTOVerifyIAPReq_FieldNumber_OrderNo = 4,
  PROTOVerifyIAPReq_FieldNumber_GoodsId = 5,
};

@interface PROTOVerifyIAPReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t accountId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *receipt;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNo;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *goodsId;

@end

#pragma mark - PROTOVerifyIAPRes

@interface PROTOVerifyIAPRes : GPBMessage

@end

#pragma mark - PROTOGoldCard

typedef GPB_ENUM(PROTOGoldCard_FieldNumber) {
  PROTOGoldCard_FieldNumber_Id_p = 1,
  PROTOGoldCard_FieldNumber_Amount = 2,
  PROTOGoldCard_FieldNumber_Golds = 3,
  PROTOGoldCard_FieldNumber_GiveawayGolds = 4,
  PROTOGoldCard_FieldNumber_Identifier = 5,
};

@interface PROTOGoldCard : GPBMessage

 
@property(nonatomic, readwrite) int32_t id_p;

 
@property(nonatomic, readwrite) int32_t amount;

 
@property(nonatomic, readwrite) int32_t golds;

 
@property(nonatomic, readwrite) int32_t giveawayGolds;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *identifier;

@end

#pragma mark - PROTOGetGoodListReq

 
@interface PROTOGetGoodListReq : GPBMessage

@end

#pragma mark - PROTOGetGoodListRes

typedef GPB_ENUM(PROTOGetGoodListRes_FieldNumber) {
  PROTOGetGoodListRes_FieldNumber_GoodListArray = 1,
  PROTOGetGoodListRes_FieldNumber_Version = 2,
};

@interface PROTOGetGoodListRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PROTOGoldCard*> *goodListArray;
 
@property(nonatomic, readonly) NSUInteger goodListArray_Count;

 
@property(nonatomic, readwrite) int32_t version;

@end

#pragma mark - PROTOOrderIAPReq

typedef GPB_ENUM(PROTOOrderIAPReq_FieldNumber) {
  PROTOOrderIAPReq_FieldNumber_Id_p = 1,
  PROTOOrderIAPReq_FieldNumber_AccountId = 2,
};

 
@interface PROTOOrderIAPReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t id_p;

 
@property(nonatomic, readwrite) int64_t accountId;

@end

#pragma mark - PROTOOrderIAPRes

typedef GPB_ENUM(PROTOOrderIAPRes_FieldNumber) {
  PROTOOrderIAPRes_FieldNumber_OrderNo = 1,
};

@interface PROTOOrderIAPRes : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNo;

@end

#pragma mark - PROTOCloseOrderIAPReq

typedef GPB_ENUM(PROTOCloseOrderIAPReq_FieldNumber) {
  PROTOCloseOrderIAPReq_FieldNumber_OrderNo = 1,
  PROTOCloseOrderIAPReq_FieldNumber_Status = 2,
};

@interface PROTOCloseOrderIAPReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNo;

 
@property(nonatomic, readwrite) PROTOIAPStatusType status;

@end

 
int32_t PROTOCloseOrderIAPReq_Status_RawValue(PROTOCloseOrderIAPReq *message);
 
void SetPROTOCloseOrderIAPReq_Status_RawValue(PROTOCloseOrderIAPReq *message, int32_t value);

#pragma mark - PROTOCloseOrderIAPRes

@interface PROTOCloseOrderIAPRes : GPBMessage

@end

#pragma mark - PROTOVIPChargeAccountInfoReq

typedef GPB_ENUM(PROTOVIPChargeAccountInfoReq_FieldNumber) {
  PROTOVIPChargeAccountInfoReq_FieldNumber_Id_p = 1,
};

@interface PROTOVIPChargeAccountInfoReq : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@end

#pragma mark - PROTOVIPChargeAccountInfoRes

typedef GPB_ENUM(PROTOVIPChargeAccountInfoRes_FieldNumber) {
  PROTOVIPChargeAccountInfoRes_FieldNumber_DueBank = 1,
  PROTOVIPChargeAccountInfoRes_FieldNumber_Payee = 2,
  PROTOVIPChargeAccountInfoRes_FieldNumber_AccountNumber = 3,
  PROTOVIPChargeAccountInfoRes_FieldNumber_DepositBank = 4,
  PROTOVIPChargeAccountInfoRes_FieldNumber_Nickname = 5,
  PROTOVIPChargeAccountInfoRes_FieldNumber_PlayerId = 6,
};

@interface PROTOVIPChargeAccountInfoRes : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *dueBank;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *payee;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountNumber;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *depositBank;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

 
@property(nonatomic, readwrite) int64_t playerId;

@end

#pragma mark - PROTOVIPChargeLogReq

@interface PROTOVIPChargeLogReq : GPBMessage

@end

#pragma mark - PROTOVIPChargeLogRes

typedef GPB_ENUM(PROTOVIPChargeLogRes_FieldNumber) {
  PROTOVIPChargeLogRes_FieldNumber_ListArray = 1,
};

@interface PROTOVIPChargeLogRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PROTOVIPChargeLogs*> *listArray;
 
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PROTOVIPChargeLogs

typedef GPB_ENUM(PROTOVIPChargeLogs_FieldNumber) {
  PROTOVIPChargeLogs_FieldNumber_Day = 1,
  PROTOVIPChargeLogs_FieldNumber_ListArray = 2,
};

@interface PROTOVIPChargeLogs : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *day;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PROTOVIPChargeItem*> *listArray;
 
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PROTOVIPChargeItem

typedef GPB_ENUM(PROTOVIPChargeItem_FieldNumber) {
  PROTOVIPChargeItem_FieldNumber_ChargeAt = 1,
  PROTOVIPChargeItem_FieldNumber_FinishAt = 2,
  PROTOVIPChargeItem_FieldNumber_Rmb = 3,
  PROTOVIPChargeItem_FieldNumber_Gold = 4,
  PROTOVIPChargeItem_FieldNumber_Status = 5,
};

@interface PROTOVIPChargeItem : GPBMessage

 
@property(nonatomic, readwrite) int64_t chargeAt;

 
@property(nonatomic, readwrite) int64_t finishAt;

 
@property(nonatomic, readwrite) int64_t rmb;

 
@property(nonatomic, readwrite) int64_t gold;

 
@property(nonatomic, readwrite) PROTOChargeStatus status;

@end

 
int32_t PROTOVIPChargeItem_Status_RawValue(PROTOVIPChargeItem *message);
 
void SetPROTOVIPChargeItem_Status_RawValue(PROTOVIPChargeItem *message, int32_t value);

#pragma mark - PROTOReportDataReq

typedef GPB_ENUM(PROTOReportDataReq_FieldNumber) {
  PROTOReportDataReq_FieldNumber_Type = 1,
  PROTOReportDataReq_FieldNumber_Data_p = 2,
};

@interface PROTOReportDataReq : GPBMessage

@property(nonatomic, readwrite) PROTOReportDataType type;

 
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

 
int32_t PROTOReportDataReq_Type_RawValue(PROTOReportDataReq *message);
 
void SetPROTOReportDataReq_Type_RawValue(PROTOReportDataReq *message, int32_t value);

#pragma mark - PROTOReportDataRes

@interface PROTOReportDataRes : GPBMessage

@end

#pragma mark - PROTOGetChargeReq

typedef GPB_ENUM(PROTOGetChargeReq_FieldNumber) {
  PROTOGetChargeReq_FieldNumber_OrderId = 1,
  PROTOGetChargeReq_FieldNumber_AccountId = 2,
  PROTOGetChargeReq_FieldNumber_Gold = 4,
  PROTOGetChargeReq_FieldNumber_Remark = 5,
  PROTOGetChargeReq_FieldNumber_Extends = 6,
  PROTOGetChargeReq_FieldNumber_ExtraData = 7,
  PROTOGetChargeReq_FieldNumber_SubType = 8,
  PROTOGetChargeReq_FieldNumber_ReturnURL = 9,
};

 
@interface PROTOGetChargeReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) int64_t accountId;

@property(nonatomic, readwrite) int64_t gold;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extends;
 
@property(nonatomic, readonly) NSUInteger extends_Count;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extraData;
 
@property(nonatomic, readonly) NSUInteger extraData_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *returnURL;

@end

#pragma mark - PROTOGetChargeRes

typedef GPB_ENUM(PROTOGetChargeRes_FieldNumber) {
  PROTOGetChargeRes_FieldNumber_Code = 1,
  PROTOGetChargeRes_FieldNumber_Detail = 2,
  PROTOGetChargeRes_FieldNumber_Data_p = 3,
  PROTOGetChargeRes_FieldNumber_RedirectURL = 4,
};

@interface PROTOGetChargeRes : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *redirectURL;

@end

#pragma mark - PROTOGetSmsCodeReq

typedef GPB_ENUM(PROTOGetSmsCodeReq_FieldNumber) {
  PROTOGetSmsCodeReq_FieldNumber_Country = 1,
  PROTOGetSmsCodeReq_FieldNumber_PhoneNo = 2,
  PROTOGetSmsCodeReq_FieldNumber_PhoneSign = 3,
  PROTOGetSmsCodeReq_FieldNumber_SmsCodeTpl = 4,
};

 
@interface PROTOGetSmsCodeReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNo;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneSign;

 
@property(nonatomic, readwrite) PROTOSMSCodeTpl smsCodeTpl;

@end

 
int32_t PROTOGetSmsCodeReq_SmsCodeTpl_RawValue(PROTOGetSmsCodeReq *message);
 
void SetPROTOGetSmsCodeReq_SmsCodeTpl_RawValue(PROTOGetSmsCodeReq *message, int32_t value);

#pragma mark - PROTOGetSmsCodeRes

@interface PROTOGetSmsCodeRes : GPBMessage

@end

#pragma mark - PROTOGetSmsTokenReq

typedef GPB_ENUM(PROTOGetSmsTokenReq_FieldNumber) {
  PROTOGetSmsTokenReq_FieldNumber_Country = 1,
  PROTOGetSmsTokenReq_FieldNumber_PhoneNo = 2,
  PROTOGetSmsTokenReq_FieldNumber_SmsCode = 3,
  PROTOGetSmsTokenReq_FieldNumber_PhoneSign = 4,
  PROTOGetSmsTokenReq_FieldNumber_SmsCodeTpl = 5,
};

 
@interface PROTOGetSmsTokenReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNo;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsCode;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneSign;

 
@property(nonatomic, readwrite) PROTOSMSCodeTpl smsCodeTpl;

@end

 
int32_t PROTOGetSmsTokenReq_SmsCodeTpl_RawValue(PROTOGetSmsTokenReq *message);
 
void SetPROTOGetSmsTokenReq_SmsCodeTpl_RawValue(PROTOGetSmsTokenReq *message, int32_t value);

#pragma mark - PROTOGetSmsTokenRes

typedef GPB_ENUM(PROTOGetSmsTokenRes_FieldNumber) {
  PROTOGetSmsTokenRes_FieldNumber_SmsToken = 1,
};

@interface PROTOGetSmsTokenRes : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsToken;

@end

#pragma mark - PROTOPhoneSmsCodeReq

typedef GPB_ENUM(PROTOPhoneSmsCodeReq_FieldNumber) {
  PROTOPhoneSmsCodeReq_FieldNumber_SmsCodeTpl = 1,
};

 
@interface PROTOPhoneSmsCodeReq : GPBMessage

 
@property(nonatomic, readwrite) PROTOSMSCodeTpl smsCodeTpl;

@end

 
int32_t PROTOPhoneSmsCodeReq_SmsCodeTpl_RawValue(PROTOPhoneSmsCodeReq *message);
 
void SetPROTOPhoneSmsCodeReq_SmsCodeTpl_RawValue(PROTOPhoneSmsCodeReq *message, int32_t value);

#pragma mark - PROTOPhoneSmsCodeRes

@interface PROTOPhoneSmsCodeRes : GPBMessage

@end

#pragma mark - PROTOCheckPhoneSmsCodeReq

typedef GPB_ENUM(PROTOCheckPhoneSmsCodeReq_FieldNumber) {
  PROTOCheckPhoneSmsCodeReq_FieldNumber_SmsCodeTpl = 1,
  PROTOCheckPhoneSmsCodeReq_FieldNumber_SmsCode = 2,
};

 
@interface PROTOCheckPhoneSmsCodeReq : GPBMessage

 
@property(nonatomic, readwrite) PROTOSMSCodeTpl smsCodeTpl;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsCode;

@end

 
int32_t PROTOCheckPhoneSmsCodeReq_SmsCodeTpl_RawValue(PROTOCheckPhoneSmsCodeReq *message);
 
void SetPROTOCheckPhoneSmsCodeReq_SmsCodeTpl_RawValue(PROTOCheckPhoneSmsCodeReq *message, int32_t value);

#pragma mark - PROTOCheckPhoneSmsCodeRes

@interface PROTOCheckPhoneSmsCodeRes : GPBMessage

@end

#pragma mark - PROTOCommonSignInRes

typedef GPB_ENUM(PROTOCommonSignInRes_FieldNumber) {
  PROTOCommonSignInRes_FieldNumber_LoginToken = 1,
  PROTOCommonSignInRes_FieldNumber_IsNew = 2,
  PROTOCommonSignInRes_FieldNumber_UserId = 3,
  PROTOCommonSignInRes_FieldNumber_Extends = 4,
  PROTOCommonSignInRes_FieldNumber_LoginType = 5,
};

 
@interface PROTOCommonSignInRes : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

 
@property(nonatomic, readwrite) BOOL isNew;

@property(nonatomic, readwrite) int64_t userId;

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extends;
 
@property(nonatomic, readonly) NSUInteger extends_Count;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType loginType;

@end

 
int32_t PROTOCommonSignInRes_LoginType_RawValue(PROTOCommonSignInRes *message);
 
void SetPROTOCommonSignInRes_LoginType_RawValue(PROTOCommonSignInRes *message, int32_t value);

#pragma mark - PROTOSignInWithAppleReq

typedef GPB_ENUM(PROTOSignInWithAppleReq_FieldNumber) {
  PROTOSignInWithAppleReq_FieldNumber_IdentityToken = 1,
  PROTOSignInWithAppleReq_FieldNumber_AuthorizationCode = 2,
  PROTOSignInWithAppleReq_FieldNumber_FullName = 3,
  PROTOSignInWithAppleReq_FieldNumber_DeviceId = 4,
  PROTOSignInWithAppleReq_FieldNumber_UMengDeviceId = 5,
  PROTOSignInWithAppleReq_FieldNumber_YidunToken = 6,
  PROTOSignInWithAppleReq_FieldNumber_DeviceMessage = 7,
};

 
@interface PROTOSignInWithAppleReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *identityToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *authorizationCode;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *fullName;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTOIdOrPhoneLoginReq

typedef GPB_ENUM(PROTOIdOrPhoneLoginReq_FieldNumber) {
  PROTOIdOrPhoneLoginReq_FieldNumber_Country = 1,
  PROTOIdOrPhoneLoginReq_FieldNumber_Value = 2,
  PROTOIdOrPhoneLoginReq_FieldNumber_Password = 3,
  PROTOIdOrPhoneLoginReq_FieldNumber_Sign = 4,
  PROTOIdOrPhoneLoginReq_FieldNumber_DeviceId = 5,
  PROTOIdOrPhoneLoginReq_FieldNumber_UMengDeviceId = 6,
  PROTOIdOrPhoneLoginReq_FieldNumber_YidunToken = 7,
};

 
@interface PROTOIdOrPhoneLoginReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@end

#pragma mark - PROTOLoginWithPhoneSMSReq

typedef GPB_ENUM(PROTOLoginWithPhoneSMSReq_FieldNumber) {
  PROTOLoginWithPhoneSMSReq_FieldNumber_Phone = 1,
  PROTOLoginWithPhoneSMSReq_FieldNumber_SmsToken = 2,
  PROTOLoginWithPhoneSMSReq_FieldNumber_DeviceId = 3,
  PROTOLoginWithPhoneSMSReq_FieldNumber_DeviceType = 4,
  PROTOLoginWithPhoneSMSReq_FieldNumber_Channel = 5,
  PROTOLoginWithPhoneSMSReq_FieldNumber_SmsCode = 6,
  PROTOLoginWithPhoneSMSReq_FieldNumber_UMengDeviceId = 8,
  PROTOLoginWithPhoneSMSReq_FieldNumber_YidunToken = 9,
  PROTOLoginWithPhoneSMSReq_FieldNumber_PhoneSign = 10,
  PROTOLoginWithPhoneSMSReq_FieldNumber_DeviceMessage = 11,
  PROTOLoginWithPhoneSMSReq_FieldNumber_SmsCodeTpl = 12,
};

 
@interface PROTOLoginWithPhoneSMSReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsToken;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsCode;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneSign;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

 
@property(nonatomic, readwrite) PROTOSMSCodeTpl smsCodeTpl;

@end

 
int32_t PROTOLoginWithPhoneSMSReq_SmsCodeTpl_RawValue(PROTOLoginWithPhoneSMSReq *message);
 
void SetPROTOLoginWithPhoneSMSReq_SmsCodeTpl_RawValue(PROTOLoginWithPhoneSMSReq *message, int32_t value);

#pragma mark - PROTOThirdLoginReq

typedef GPB_ENUM(PROTOThirdLoginReq_FieldNumber) {
  PROTOThirdLoginReq_FieldNumber_Code = 1,
  PROTOThirdLoginReq_FieldNumber_AccessToken = 2,
  PROTOThirdLoginReq_FieldNumber_AppId = 3,
  PROTOThirdLoginReq_FieldNumber_DeviceId = 4,
  PROTOThirdLoginReq_FieldNumber_DeviceType = 5,
  PROTOThirdLoginReq_FieldNumber_Channel = 6,
  PROTOThirdLoginReq_FieldNumber_LoginType = 7,
  PROTOThirdLoginReq_FieldNumber_UMengDeviceId = 8,
  PROTOThirdLoginReq_FieldNumber_YidunToken = 9,
  PROTOThirdLoginReq_FieldNumber_TokenSecret = 10,
  PROTOThirdLoginReq_FieldNumber_DeviceMessage = 11,
};

 
@interface PROTOThirdLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType loginType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tokenSecret;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

 
int32_t PROTOThirdLoginReq_LoginType_RawValue(PROTOThirdLoginReq *message);
 
void SetPROTOThirdLoginReq_LoginType_RawValue(PROTOThirdLoginReq *message, int32_t value);

#pragma mark - PROTOChinaMobileQuickLoginReq

typedef GPB_ENUM(PROTOChinaMobileQuickLoginReq_FieldNumber) {
  PROTOChinaMobileQuickLoginReq_FieldNumber_AppId = 1,
  PROTOChinaMobileQuickLoginReq_FieldNumber_Token = 2,
  PROTOChinaMobileQuickLoginReq_FieldNumber_DeviceId = 3,
  PROTOChinaMobileQuickLoginReq_FieldNumber_DeviceType = 4,
  PROTOChinaMobileQuickLoginReq_FieldNumber_Channel = 5,
  PROTOChinaMobileQuickLoginReq_FieldNumber_UMengDeviceId = 6,
  PROTOChinaMobileQuickLoginReq_FieldNumber_YidunToken = 7,
  PROTOChinaMobileQuickLoginReq_FieldNumber_DeviceMessage = 8,
};

 
@interface PROTOChinaMobileQuickLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTOChinaTelecomAuthReq

typedef GPB_ENUM(PROTOChinaTelecomAuthReq_FieldNumber) {
  PROTOChinaTelecomAuthReq_FieldNumber_AccessToken = 1,
  PROTOChinaTelecomAuthReq_FieldNumber_DeviceId = 3,
  PROTOChinaTelecomAuthReq_FieldNumber_DeviceType = 4,
  PROTOChinaTelecomAuthReq_FieldNumber_Channel = 5,
  PROTOChinaTelecomAuthReq_FieldNumber_UMengDeviceId = 6,
  PROTOChinaTelecomAuthReq_FieldNumber_YidunToken = 7,
  PROTOChinaTelecomAuthReq_FieldNumber_DeviceMessage = 8,
};

 
@interface PROTOChinaTelecomAuthReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTOUmengQuickLoginReq

typedef GPB_ENUM(PROTOUmengQuickLoginReq_FieldNumber) {
  PROTOUmengQuickLoginReq_FieldNumber_AppKey = 1,
  PROTOUmengQuickLoginReq_FieldNumber_Token = 2,
  PROTOUmengQuickLoginReq_FieldNumber_DeviceId = 3,
  PROTOUmengQuickLoginReq_FieldNumber_DeviceType = 4,
  PROTOUmengQuickLoginReq_FieldNumber_Channel = 5,
  PROTOUmengQuickLoginReq_FieldNumber_UMengDeviceId = 8,
  PROTOUmengQuickLoginReq_FieldNumber_YidunToken = 9,
  PROTOUmengQuickLoginReq_FieldNumber_DeviceMessage = 10,
};

 
@interface PROTOUmengQuickLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *appKey;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTODevLoginReq

typedef GPB_ENUM(PROTODevLoginReq_FieldNumber) {
  PROTODevLoginReq_FieldNumber_Name = 1,
  PROTODevLoginReq_FieldNumber_DeviceId = 3,
  PROTODevLoginReq_FieldNumber_DeviceType = 4,
  PROTODevLoginReq_FieldNumber_Channel = 5,
  PROTODevLoginReq_FieldNumber_UMengDeviceId = 6,
  PROTODevLoginReq_FieldNumber_YidunToken = 7,
  PROTODevLoginReq_FieldNumber_DeviceMessage = 8,
};

 
@interface PROTODevLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTOResetPasswordReq

typedef GPB_ENUM(PROTOResetPasswordReq_FieldNumber) {
  PROTOResetPasswordReq_FieldNumber_Country = 1,
  PROTOResetPasswordReq_FieldNumber_PhoneNo = 2,
  PROTOResetPasswordReq_FieldNumber_SmsToken = 3,
  PROTOResetPasswordReq_FieldNumber_Password = 4,
  PROTOResetPasswordReq_FieldNumber_Sign = 5,
  PROTOResetPasswordReq_FieldNumber_PhoneSign = 6,
  PROTOResetPasswordReq_FieldNumber_PlayerId = 7,
};

 
@interface PROTOResetPasswordReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNo;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsToken;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneSign;

 
@property(nonatomic, readwrite) int64_t playerId;

@end

#pragma mark - PROTOResetPasswordRes

@interface PROTOResetPasswordRes : GPBMessage

@end

#pragma mark - PROTOLoginSecretReq

@interface PROTOLoginSecretReq : GPBMessage

@end

#pragma mark - PROTOLoginSecretRes

typedef GPB_ENUM(PROTOLoginSecretRes_FieldNumber) {
  PROTOLoginSecretRes_FieldNumber_Key = 1,
};

@interface PROTOLoginSecretRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@end

#pragma mark - PROTOUpdatePasswdReq

typedef GPB_ENUM(PROTOUpdatePasswdReq_FieldNumber) {
  PROTOUpdatePasswdReq_FieldNumber_OldPasswd = 1,
  PROTOUpdatePasswdReq_FieldNumber_NewPasswd = 2,
  PROTOUpdatePasswdReq_FieldNumber_Sign = 3,
  PROTOUpdatePasswdReq_FieldNumber_IsNew = 4,
};

@interface PROTOUpdatePasswdReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *oldPasswd;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *newPasswd NS_RETURNS_NOT_RETAINED;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

 
@property(nonatomic, readwrite) BOOL isNew;

@end

#pragma mark - PROTOUpdatePasswdRes

@interface PROTOUpdatePasswdRes : GPBMessage

@end

#pragma mark - PROTOInviteReq

typedef GPB_ENUM(PROTOInviteReq_FieldNumber) {
  PROTOInviteReq_FieldNumber_PlayerId = 1,
  PROTOInviteReq_FieldNumber_Type = 2,
  PROTOInviteReq_FieldNumber_Extend = 3,
};

 
@interface PROTOInviteReq : GPBMessage

@property(nonatomic, readwrite) int64_t playerId;

 
@property(nonatomic, readwrite) int32_t type;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *extend;

@end

#pragma mark - PROTOInviteRes

@interface PROTOInviteRes : GPBMessage

@end

#pragma mark - PROTOGetSyncTimeReq

@interface PROTOGetSyncTimeReq : GPBMessage

@end

#pragma mark - PROTOGetSyncTimeRes

@interface PROTOGetSyncTimeRes : GPBMessage

@end

#pragma mark - PROTOReportBuyNobilityReq

typedef GPB_ENUM(PROTOReportBuyNobilityReq_FieldNumber) {
  PROTOReportBuyNobilityReq_FieldNumber_RoomId = 1,
  PROTOReportBuyNobilityReq_FieldNumber_BenefitId = 2,
};

@interface PROTOReportBuyNobilityReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t roomId;

 
@property(nonatomic, readwrite) int64_t benefitId;

@end

#pragma mark - PROTOReportBuyNobilityRes

@interface PROTOReportBuyNobilityRes : GPBMessage

@end

#pragma mark - PROTOGoogleIABNotifyReq

typedef GPB_ENUM(PROTOGoogleIABNotifyReq_FieldNumber) {
  PROTOGoogleIABNotifyReq_FieldNumber_UserId = 1,
  PROTOGoogleIABNotifyReq_FieldNumber_PackageName = 2,
  PROTOGoogleIABNotifyReq_FieldNumber_BuyIntent = 3,
};

@interface PROTOGoogleIABNotifyReq : GPBMessage

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packageName;

@property(nonatomic, readwrite, strong, null_resettable) PROTOGoogleIABNotifyReq_BuyIntent *buyIntent;
 
@property(nonatomic, readwrite) BOOL hasBuyIntent;

@end

#pragma mark - PROTOGoogleIABNotifyReq_BuyIntent

typedef GPB_ENUM(PROTOGoogleIABNotifyReq_BuyIntent_FieldNumber) {
  PROTOGoogleIABNotifyReq_BuyIntent_FieldNumber_PurchaseData = 1,
  PROTOGoogleIABNotifyReq_BuyIntent_FieldNumber_DataSignature = 2,
};

@interface PROTOGoogleIABNotifyReq_BuyIntent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *purchaseData;

@property(nonatomic, readwrite, copy, null_resettable) NSString *dataSignature;

@end

#pragma mark - PROTOGoogleIABNotifyRes

@interface PROTOGoogleIABNotifyRes : GPBMessage

@end

#pragma mark - PROTOGoogleIABProductItem

typedef GPB_ENUM(PROTOGoogleIABProductItem_FieldNumber) {
  PROTOGoogleIABProductItem_FieldNumber_Id_p = 1,
  PROTOGoogleIABProductItem_FieldNumber_Name = 2,
  PROTOGoogleIABProductItem_FieldNumber_Price = 3,
  PROTOGoogleIABProductItem_FieldNumber_Desc = 4,
};

@interface PROTOGoogleIABProductItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *price;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

@end

#pragma mark - PROTOGoogleIABProductItemsReq

@interface PROTOGoogleIABProductItemsReq : GPBMessage

@end

#pragma mark - PROTOGoogleIABProductItemsRes

typedef GPB_ENUM(PROTOGoogleIABProductItemsRes_FieldNumber) {
  PROTOGoogleIABProductItemsRes_FieldNumber_ItemsArray = 1,
};

@interface PROTOGoogleIABProductItemsRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PROTOGoogleIABProductItem*> *itemsArray;
 
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - PROTOGetWeChatAppIdReq

 
@interface PROTOGetWeChatAppIdReq : GPBMessage

@end

#pragma mark - PROTOGetWeChatAppIdRes

typedef GPB_ENUM(PROTOGetWeChatAppIdRes_FieldNumber) {
  PROTOGetWeChatAppIdRes_FieldNumber_AppId = 1,
};

@interface PROTOGetWeChatAppIdRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - PROTOGetWeChatIdLoginReq

typedef GPB_ENUM(PROTOGetWeChatIdLoginReq_FieldNumber) {
  PROTOGetWeChatIdLoginReq_FieldNumber_Code = 1,
};

 
@interface PROTOGetWeChatIdLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

#pragma mark - PROTOGetWeChatIdLoginRes

typedef GPB_ENUM(PROTOGetWeChatIdLoginRes_FieldNumber) {
  PROTOGetWeChatIdLoginRes_FieldNumber_Token = 1,
  PROTOGetWeChatIdLoginRes_FieldNumber_UnionId = 2,
  PROTOGetWeChatIdLoginRes_FieldNumber_OpenId = 3,
};

@interface PROTOGetWeChatIdLoginRes : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *unionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *openId;

@end

#pragma mark - PROTOUserInfo

typedef GPB_ENUM(PROTOUserInfo_FieldNumber) {
  PROTOUserInfo_FieldNumber_Nickname = 1,
  PROTOUserInfo_FieldNumber_Icon = 2,
  PROTOUserInfo_FieldNumber_Gender = 3,
};

@interface PROTOUserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

 
@property(nonatomic, readwrite) int32_t gender;

@end

#pragma mark - PROTOGetMiniProgramLoginReq

typedef GPB_ENUM(PROTOGetMiniProgramLoginReq_FieldNumber) {
  PROTOGetMiniProgramLoginReq_FieldNumber_Code = 1,
  PROTOGetMiniProgramLoginReq_FieldNumber_Appid = 2,
  PROTOGetMiniProgramLoginReq_FieldNumber_LoginType = 3,
  PROTOGetMiniProgramLoginReq_FieldNumber_UserInfo = 4,
  PROTOGetMiniProgramLoginReq_FieldNumber_EncryptedData = 5,
  PROTOGetMiniProgramLoginReq_FieldNumber_Iv = 6,
  PROTOGetMiniProgramLoginReq_FieldNumber_DeviceMessage = 7,
};

@interface PROTOGetMiniProgramLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *appid;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType loginType;

 
@property(nonatomic, readwrite, strong, null_resettable) PROTOUserInfo *userInfo;
 
@property(nonatomic, readwrite) BOOL hasUserInfo;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *encryptedData;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *iv;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

 
int32_t PROTOGetMiniProgramLoginReq_LoginType_RawValue(PROTOGetMiniProgramLoginReq *message);
 
void SetPROTOGetMiniProgramLoginReq_LoginType_RawValue(PROTOGetMiniProgramLoginReq *message, int32_t value);

#pragma mark - PROTOMiniProgramPhoneReq

typedef GPB_ENUM(PROTOMiniProgramPhoneReq_FieldNumber) {
  PROTOMiniProgramPhoneReq_FieldNumber_EncryptedData = 1,
  PROTOMiniProgramPhoneReq_FieldNumber_Iv = 2,
  PROTOMiniProgramPhoneReq_FieldNumber_LoginType = 3,
  PROTOMiniProgramPhoneReq_FieldNumber_Code = 4,
};

@interface PROTOMiniProgramPhoneReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *encryptedData;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *iv;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType loginType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

 
int32_t PROTOMiniProgramPhoneReq_LoginType_RawValue(PROTOMiniProgramPhoneReq *message);
 
void SetPROTOMiniProgramPhoneReq_LoginType_RawValue(PROTOMiniProgramPhoneReq *message, int32_t value);

#pragma mark - PROTOMiniProgramPhoneRes

@interface PROTOMiniProgramPhoneRes : GPBMessage

@end

#pragma mark - PROTOApplyCertifyReq

typedef GPB_ENUM(PROTOApplyCertifyReq_FieldNumber) {
  PROTOApplyCertifyReq_FieldNumber_CertifyType = 1,
  PROTOApplyCertifyReq_FieldNumber_IdCard = 2,
  PROTOApplyCertifyReq_FieldNumber_Name = 3,
};

@interface PROTOApplyCertifyReq : GPBMessage

 
@property(nonatomic, readwrite) PROTOCertifyType certifyType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *idCard;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

 
int32_t PROTOApplyCertifyReq_CertifyType_RawValue(PROTOApplyCertifyReq *message);
 
void SetPROTOApplyCertifyReq_CertifyType_RawValue(PROTOApplyCertifyReq *message, int32_t value);

#pragma mark - PROTOApplyCertifyRes

typedef GPB_ENUM(PROTOApplyCertifyRes_FieldNumber) {
  PROTOApplyCertifyRes_FieldNumber_FaceId = 1,
  PROTOApplyCertifyRes_FieldNumber_TradeNo = 2,
  PROTOApplyCertifyRes_FieldNumber_Nonce = 3,
  PROTOApplyCertifyRes_FieldNumber_UserId = 4,
  PROTOApplyCertifyRes_FieldNumber_Sign = 5,
};

@interface PROTOApplyCertifyRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *faceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tradeNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nonce;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@end

#pragma mark - PROTOApplyCertifySignReq

typedef GPB_ENUM(PROTOApplyCertifySignReq_FieldNumber) {
  PROTOApplyCertifySignReq_FieldNumber_CertifyType = 1,
  PROTOApplyCertifySignReq_FieldNumber_IdCard = 2,
  PROTOApplyCertifySignReq_FieldNumber_IdCardSign = 3,
  PROTOApplyCertifySignReq_FieldNumber_Name = 4,
  PROTOApplyCertifySignReq_FieldNumber_NameSign = 5,
};

@interface PROTOApplyCertifySignReq : GPBMessage

 
@property(nonatomic, readwrite) PROTOCertifyType certifyType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *idCard;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *idCardSign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *nameSign;

@end

 
int32_t PROTOApplyCertifySignReq_CertifyType_RawValue(PROTOApplyCertifySignReq *message);
 
void SetPROTOApplyCertifySignReq_CertifyType_RawValue(PROTOApplyCertifySignReq *message, int32_t value);

#pragma mark - PROTOCertifyResultReq

@interface PROTOCertifyResultReq : GPBMessage

@end

#pragma mark - PROTOCertifyResultRes

typedef GPB_ENUM(PROTOCertifyResultRes_FieldNumber) {
  PROTOCertifyResultRes_FieldNumber_CertifyType = 1,
  PROTOCertifyResultRes_FieldNumber_IdCard = 2,
  PROTOCertifyResultRes_FieldNumber_Name = 3,
};

@interface PROTOCertifyResultRes : GPBMessage

 
@property(nonatomic, readwrite) PROTOCertifyType certifyType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *idCard;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

 
int32_t PROTOCertifyResultRes_CertifyType_RawValue(PROTOCertifyResultRes *message);
 
void SetPROTOCertifyResultRes_CertifyType_RawValue(PROTOCertifyResultRes *message, int32_t value);

#pragma mark - PROTOAccountPhoneSmsCodeReq

@interface PROTOAccountPhoneSmsCodeReq : GPBMessage

@end

#pragma mark - PROTOAccountPhoneSmsCodeRes

@interface PROTOAccountPhoneSmsCodeRes : GPBMessage

@end

#pragma mark - PROTOAccountSubsidiaryLoginReq

typedef GPB_ENUM(PROTOAccountSubsidiaryLoginReq_FieldNumber) {
  PROTOAccountSubsidiaryLoginReq_FieldNumber_DeviceId = 1,
  PROTOAccountSubsidiaryLoginReq_FieldNumber_DeviceType = 2,
  PROTOAccountSubsidiaryLoginReq_FieldNumber_Channel = 3,
  PROTOAccountSubsidiaryLoginReq_FieldNumber_SmsCode = 4,
  PROTOAccountSubsidiaryLoginReq_FieldNumber_UMengDeviceId = 5,
  PROTOAccountSubsidiaryLoginReq_FieldNumber_YidunToken = 6,
  PROTOAccountSubsidiaryLoginReq_FieldNumber_DeviceMessage = 7,
};

@interface PROTOAccountSubsidiaryLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsCode;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *uMengDeviceId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *yidunToken;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTOGetGuestLoginReq

typedef GPB_ENUM(PROTOGetGuestLoginReq_FieldNumber) {
  PROTOGetGuestLoginReq_FieldNumber_GuestKey = 1,
  PROTOGetGuestLoginReq_FieldNumber_Sign = 2,
  PROTOGetGuestLoginReq_FieldNumber_DeviceType = 3,
  PROTOGetGuestLoginReq_FieldNumber_Channel = 4,
  PROTOGetGuestLoginReq_FieldNumber_DeviceMessage = 5,
};

@interface PROTOGetGuestLoginReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *guestKey;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite) int32_t channel;

@property(nonatomic, readwrite, strong, null_resettable) PROTODeviceMessage *deviceMessage;
 
@property(nonatomic, readwrite) BOOL hasDeviceMessage;

@end

#pragma mark - PROTOAccountBindPhoneSMSReq

typedef GPB_ENUM(PROTOAccountBindPhoneSMSReq_FieldNumber) {
  PROTOAccountBindPhoneSMSReq_FieldNumber_Phone = 1,
  PROTOAccountBindPhoneSMSReq_FieldNumber_SmsCode = 2,
  PROTOAccountBindPhoneSMSReq_FieldNumber_VerifyOld = 3,
  PROTOAccountBindPhoneSMSReq_FieldNumber_PhoneSign = 4,
};

@interface PROTOAccountBindPhoneSMSReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *smsCode;

 
@property(nonatomic, readwrite) BOOL verifyOld;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneSign;

@end

#pragma mark - PROTOAccountBindPhoneSMSRes

@interface PROTOAccountBindPhoneSMSRes : GPBMessage

@end

#pragma mark - PROTOAccountBindThirdReq

typedef GPB_ENUM(PROTOAccountBindThirdReq_FieldNumber) {
  PROTOAccountBindThirdReq_FieldNumber_Code = 1,
  PROTOAccountBindThirdReq_FieldNumber_AccessToken = 2,
  PROTOAccountBindThirdReq_FieldNumber_AppId = 3,
  PROTOAccountBindThirdReq_FieldNumber_LoginType = 4,
  PROTOAccountBindThirdReq_FieldNumber_TokenSecret = 5,
};

@interface PROTOAccountBindThirdReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType loginType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tokenSecret;

@end

 
int32_t PROTOAccountBindThirdReq_LoginType_RawValue(PROTOAccountBindThirdReq *message);
 
void SetPROTOAccountBindThirdReq_LoginType_RawValue(PROTOAccountBindThirdReq *message, int32_t value);

#pragma mark - PROTOAccountBindThirdRes

@interface PROTOAccountBindThirdRes : GPBMessage

@end

#pragma mark - PROTOAccountBindListReq

@interface PROTOAccountBindListReq : GPBMessage

@end

#pragma mark - PROTOAccountBindListRes

typedef GPB_ENUM(PROTOAccountBindListRes_FieldNumber) {
  PROTOAccountBindListRes_FieldNumber_ListArray = 1,
  PROTOAccountBindListRes_FieldNumber_Phone = 2,
  PROTOAccountBindListRes_FieldNumber_Email = 3,
};

@interface PROTOAccountBindListRes : GPBMessage

 
 
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *listArray;
 
@property(nonatomic, readonly) NSUInteger listArray_Count;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@end

#pragma mark - PROTOBindPhoneSmsCodeReq

typedef GPB_ENUM(PROTOBindPhoneSmsCodeReq_FieldNumber) {
  PROTOBindPhoneSmsCodeReq_FieldNumber_Country = 1,
  PROTOBindPhoneSmsCodeReq_FieldNumber_PhoneNo = 2,
  PROTOBindPhoneSmsCodeReq_FieldNumber_VerifyOld = 3,
  PROTOBindPhoneSmsCodeReq_FieldNumber_PhoneSign = 4,
};

@interface PROTOBindPhoneSmsCodeReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNo;

 
@property(nonatomic, readwrite) BOOL verifyOld;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneSign;

@end

#pragma mark - PROTOBindPhoneSmsCodeRes

@interface PROTOBindPhoneSmsCodeRes : GPBMessage

@end

#pragma mark - PROTOBindEmailSesCodeReq

typedef GPB_ENUM(PROTOBindEmailSesCodeReq_FieldNumber) {
  PROTOBindEmailSesCodeReq_FieldNumber_Email = 1,
  PROTOBindEmailSesCodeReq_FieldNumber_EmailSign = 2,
  PROTOBindEmailSesCodeReq_FieldNumber_VerifyOld = 3,
};

@interface PROTOBindEmailSesCodeReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *emailSign;

 
@property(nonatomic, readwrite) BOOL verifyOld;

@end

#pragma mark - PROTOBindEmailSesCodeRes

@interface PROTOBindEmailSesCodeRes : GPBMessage

@end

#pragma mark - PROTOAccountBindEmailSESReq

typedef GPB_ENUM(PROTOAccountBindEmailSESReq_FieldNumber) {
  PROTOAccountBindEmailSESReq_FieldNumber_Email = 1,
  PROTOAccountBindEmailSESReq_FieldNumber_EmailSign = 2,
  PROTOAccountBindEmailSESReq_FieldNumber_SesCode = 3,
  PROTOAccountBindEmailSESReq_FieldNumber_VerifyOld = 4,
};

@interface PROTOAccountBindEmailSESReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *emailSign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sesCode;

 
@property(nonatomic, readwrite) BOOL verifyOld;

@end

#pragma mark - PROTOAccountBindEmailSESRes

@interface PROTOAccountBindEmailSESRes : GPBMessage

@end

#pragma mark - PROTOGetAccountRegisterReq

typedef GPB_ENUM(PROTOGetAccountRegisterReq_FieldNumber) {
  PROTOGetAccountRegisterReq_FieldNumber_Country = 1,
  PROTOGetAccountRegisterReq_FieldNumber_Value = 2,
  PROTOGetAccountRegisterReq_FieldNumber_Password = 3,
  PROTOGetAccountRegisterReq_FieldNumber_DeviceType = 4,
  PROTOGetAccountRegisterReq_FieldNumber_Nickname = 5,
  PROTOGetAccountRegisterReq_FieldNumber_RegisterType = 6,
  PROTOGetAccountRegisterReq_FieldNumber_Code = 7,
  PROTOGetAccountRegisterReq_FieldNumber_Sign = 8,
  PROTOGetAccountRegisterReq_FieldNumber_ValueSign = 9,
};

@interface PROTOGetAccountRegisterReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType registerType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *valueSign;

@end

 
int32_t PROTOGetAccountRegisterReq_RegisterType_RawValue(PROTOGetAccountRegisterReq *message);
 
void SetPROTOGetAccountRegisterReq_RegisterType_RawValue(PROTOGetAccountRegisterReq *message, int32_t value);

#pragma mark - PROTOGetAccountPasswordLoginReq

typedef GPB_ENUM(PROTOGetAccountPasswordLoginReq_FieldNumber) {
  PROTOGetAccountPasswordLoginReq_FieldNumber_Country = 1,
  PROTOGetAccountPasswordLoginReq_FieldNumber_Value = 2,
  PROTOGetAccountPasswordLoginReq_FieldNumber_Password = 3,
  PROTOGetAccountPasswordLoginReq_FieldNumber_LoginType = 4,
  PROTOGetAccountPasswordLoginReq_FieldNumber_DeviceType = 5,
  PROTOGetAccountPasswordLoginReq_FieldNumber_Sign = 6,
  PROTOGetAccountPasswordLoginReq_FieldNumber_ValueSign = 7,
};

@interface PROTOGetAccountPasswordLoginReq : GPBMessage

 
@property(nonatomic, readwrite) int32_t country;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

 
@property(nonatomic, readwrite) enum PROTOUauthLoginType loginType;

 
@property(nonatomic, readwrite) int32_t deviceType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *valueSign;

@end

 
int32_t PROTOGetAccountPasswordLoginReq_LoginType_RawValue(PROTOGetAccountPasswordLoginReq *message);
 
void SetPROTOGetAccountPasswordLoginReq_LoginType_RawValue(PROTOGetAccountPasswordLoginReq *message, int32_t value);

#pragma mark - PROTOGetSesCodeReq

typedef GPB_ENUM(PROTOGetSesCodeReq_FieldNumber) {
  PROTOGetSesCodeReq_FieldNumber_Email = 1,
  PROTOGetSesCodeReq_FieldNumber_EmailSign = 2,
};

@interface PROTOGetSesCodeReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *emailSign;

@end

#pragma mark - PROTOGetSesCodeRes

@interface PROTOGetSesCodeRes : GPBMessage

@end

#pragma mark - PROTOGetSesTokenReq

typedef GPB_ENUM(PROTOGetSesTokenReq_FieldNumber) {
  PROTOGetSesTokenReq_FieldNumber_Email = 1,
  PROTOGetSesTokenReq_FieldNumber_EmailSign = 2,
  PROTOGetSesTokenReq_FieldNumber_SesCode = 3,
};

 
@interface PROTOGetSesTokenReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *emailSign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sesCode;

@end

#pragma mark - PROTOGetSesTokenRes

typedef GPB_ENUM(PROTOGetSesTokenRes_FieldNumber) {
  PROTOGetSesTokenRes_FieldNumber_SesToken = 1,
};

@interface PROTOGetSesTokenRes : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sesToken;

@end

#pragma mark - PROTOResetPasswordBySesReq

typedef GPB_ENUM(PROTOResetPasswordBySesReq_FieldNumber) {
  PROTOResetPasswordBySesReq_FieldNumber_Email = 1,
  PROTOResetPasswordBySesReq_FieldNumber_EmailSign = 2,
  PROTOResetPasswordBySesReq_FieldNumber_SesToken = 3,
  PROTOResetPasswordBySesReq_FieldNumber_Password = 4,
  PROTOResetPasswordBySesReq_FieldNumber_Sign = 5,
};

@interface PROTOResetPasswordBySesReq : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *emailSign;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sesToken;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@end

#pragma mark - PROTOResetPasswordBySesRes

@interface PROTOResetPasswordBySesRes : GPBMessage

@end

#pragma mark - PROTORemoteLoginSendCodeReq

typedef GPB_ENUM(PROTORemoteLoginSendCodeReq_FieldNumber) {
  PROTORemoteLoginSendCodeReq_FieldNumber_UserId = 1,
};

 
@interface PROTORemoteLoginSendCodeReq : GPBMessage

 
@property(nonatomic, readwrite) int64_t userId;

@end

#pragma mark - PROTORemoteLoginSendCodeRes

@interface PROTORemoteLoginSendCodeRes : GPBMessage

@end

#pragma mark - PROTORemoteLoginConfirmCodeReq

typedef GPB_ENUM(PROTORemoteLoginConfirmCodeReq_FieldNumber) {
  PROTORemoteLoginConfirmCodeReq_FieldNumber_Code = 1,
  PROTORemoteLoginConfirmCodeReq_FieldNumber_UserId = 2,
};

 
@interface PROTORemoteLoginConfirmCodeReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

 
@property(nonatomic, readwrite) int64_t userId;

@end

#pragma mark - PROTORemoteLoginConfirmCodeRes

typedef GPB_ENUM(PROTORemoteLoginConfirmCodeRes_FieldNumber) {
  PROTORemoteLoginConfirmCodeRes_FieldNumber_Res = 1,
};

@interface PROTORemoteLoginConfirmCodeRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) PROTOCommonSignInRes *res;
 
@property(nonatomic, readwrite) BOOL hasRes;

@end

#pragma mark - PROTOVerifyCancelSignInWithAppleReq

typedef GPB_ENUM(PROTOVerifyCancelSignInWithAppleReq_FieldNumber) {
  PROTOVerifyCancelSignInWithAppleReq_FieldNumber_IdentityToken = 1,
  PROTOVerifyCancelSignInWithAppleReq_FieldNumber_AuthorizationCode = 2,
};

@interface PROTOVerifyCancelSignInWithAppleReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *identityToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *authorizationCode;

@end

#pragma mark - PROTOVerifyCancelSignInWithAppleRes

@interface PROTOVerifyCancelSignInWithAppleRes : GPBMessage

@end

#pragma mark - PROTOWechatCodeLoginTicketReq

typedef GPB_ENUM(PROTOWechatCodeLoginTicketReq_FieldNumber) {
  PROTOWechatCodeLoginTicketReq_FieldNumber_AppId = 1,
};

@interface PROTOWechatCodeLoginTicketReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - PROTOWechatCodeLoginTicketRes

typedef GPB_ENUM(PROTOWechatCodeLoginTicketRes_FieldNumber) {
  PROTOWechatCodeLoginTicketRes_FieldNumber_Ticket = 1,
};

@interface PROTOWechatCodeLoginTicketRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ticket;

@end

#pragma mark - PROTOThirdAccountBindWeChatInfo

typedef GPB_ENUM(PROTOThirdAccountBindWeChatInfo_FieldNumber) {
  PROTOThirdAccountBindWeChatInfo_FieldNumber_Nickname = 1,
};

@interface PROTOThirdAccountBindWeChatInfo : GPBMessage

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@end

#pragma mark - PROTOThirdAccountBindQqInfo

typedef GPB_ENUM(PROTOThirdAccountBindQqInfo_FieldNumber) {
  PROTOThirdAccountBindQqInfo_FieldNumber_Nickname = 2,
};

@interface PROTOThirdAccountBindQqInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@end

#pragma mark - PROTOThirdAccountBindInfo

typedef GPB_ENUM(PROTOThirdAccountBindInfo_FieldNumber) {
  PROTOThirdAccountBindInfo_FieldNumber_WechatInfo = 1,
  PROTOThirdAccountBindInfo_FieldNumber_QqInfo = 2,
};

typedef GPB_ENUM(PROTOThirdAccountBindInfo_BindInfo_OneOfCase) {
  PROTOThirdAccountBindInfo_BindInfo_OneOfCase_GPBUnsetOneOfCase = 0,
  PROTOThirdAccountBindInfo_BindInfo_OneOfCase_WechatInfo = 1,
  PROTOThirdAccountBindInfo_BindInfo_OneOfCase_QqInfo = 2,
};

 
@interface PROTOThirdAccountBindInfo : GPBMessage

@property(nonatomic, readonly) PROTOThirdAccountBindInfo_BindInfo_OneOfCase bindInfoOneOfCase;

 
@property(nonatomic, readwrite, strong, null_resettable) PROTOThirdAccountBindWeChatInfo *wechatInfo;

 
@property(nonatomic, readwrite, strong, null_resettable) PROTOThirdAccountBindQqInfo *qqInfo;

@end

 
void PROTOThirdAccountBindInfo_ClearBindInfoOneOfCase(PROTOThirdAccountBindInfo *message);

#pragma mark - PROTOThirdAccountBindInfoData

typedef GPB_ENUM(PROTOThirdAccountBindInfoData_FieldNumber) {
  PROTOThirdAccountBindInfoData_FieldNumber_BindType = 1,
  PROTOThirdAccountBindInfoData_FieldNumber_Info = 2,
};

 
@interface PROTOThirdAccountBindInfoData : GPBMessage

 
@property(nonatomic, readwrite) PROTOThirdAccountBindType bindType;

 
@property(nonatomic, readwrite, strong, null_resettable) PROTOThirdAccountBindInfo *info;
 
@property(nonatomic, readwrite) BOOL hasInfo;

@end

 
int32_t PROTOThirdAccountBindInfoData_BindType_RawValue(PROTOThirdAccountBindInfoData *message);
 
void SetPROTOThirdAccountBindInfoData_BindType_RawValue(PROTOThirdAccountBindInfoData *message, int32_t value);

#pragma mark - PROTOThirdAccountBindInfoReq

 
@interface PROTOThirdAccountBindInfoReq : GPBMessage

@end

#pragma mark - PROTOThirdAccountBindInfoRes

typedef GPB_ENUM(PROTOThirdAccountBindInfoRes_FieldNumber) {
  PROTOThirdAccountBindInfoRes_FieldNumber_InfoDataArray = 1,
};

@interface PROTOThirdAccountBindInfoRes : GPBMessage

 
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PROTOThirdAccountBindInfoData*> *infoDataArray;
 
@property(nonatomic, readonly) NSUInteger infoDataArray_Count;

@end

#pragma mark - PROTOBindThirdAccountReq

typedef GPB_ENUM(PROTOBindThirdAccountReq_FieldNumber) {
  PROTOBindThirdAccountReq_FieldNumber_BindType = 1,
  PROTOBindThirdAccountReq_FieldNumber_AppId = 2,
  PROTOBindThirdAccountReq_FieldNumber_Code = 3,
  PROTOBindThirdAccountReq_FieldNumber_AccessToken = 4,
};

 
@interface PROTOBindThirdAccountReq : GPBMessage

 
@property(nonatomic, readwrite) PROTOThirdAccountBindType bindType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@end

 
int32_t PROTOBindThirdAccountReq_BindType_RawValue(PROTOBindThirdAccountReq *message);
 
void SetPROTOBindThirdAccountReq_BindType_RawValue(PROTOBindThirdAccountReq *message, int32_t value);

#pragma mark - PROTOBindThirdAccountRes

@interface PROTOBindThirdAccountRes : GPBMessage

@end

#pragma mark - PROTOUnbindThirdAccountReq

typedef GPB_ENUM(PROTOUnbindThirdAccountReq_FieldNumber) {
  PROTOUnbindThirdAccountReq_FieldNumber_OptType = 1,
  PROTOUnbindThirdAccountReq_FieldNumber_SmsCode = 2,
};

 
@interface PROTOUnbindThirdAccountReq : GPBMessage

 
@property(nonatomic, readwrite) PROTOUnbindThirdAccountOptType optType;

 
@property(nonatomic, readwrite, copy, null_resettable) NSString *smsCode;

@end

 
int32_t PROTOUnbindThirdAccountReq_OptType_RawValue(PROTOUnbindThirdAccountReq *message);
 
void SetPROTOUnbindThirdAccountReq_OptType_RawValue(PROTOUnbindThirdAccountReq *message, int32_t value);

#pragma mark - PROTOUnbindThirdAccountRes

@interface PROTOUnbindThirdAccountRes : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

 
