// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_pb/video.ext.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB4ExtraInfo;
@class PB4PAuthInfo;
@class PB4TrendTag;
@class PB4VideoButton;
@class PB4VideoContentTop;
@class PB4VideoInfo;
GPB_ENUM_FWD_DECLARE(PB4PluginSexType);
GPB_ENUM_FWD_DECLARE(PB4VideoRecmdSource);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB4VideoCmdId

/** 广播cmdId定义 // 304 */
typedef GPB_ENUM(PB4VideoCmdId) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoCmdId_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoCmdId_IcVideoZero = 0,
};

GPBEnumDescriptor *PB4VideoCmdId_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoCmdId_IsValidValue(int32_t value);

#pragma mark - Enum PB4VideoGetType

/** 获取类型 */
typedef GPB_ENUM(PB4VideoGetType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoGetType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoGetType_VgtZero = 0,

  /** 进app后首次拉取 */
  PB4VideoGetType_VgtFirst = 1,
};

GPBEnumDescriptor *PB4VideoGetType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoGetType_IsValidValue(int32_t value);

#pragma mark - Enum PB4EIButtonType

typedef GPB_ENUM(PB4EIButtonType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4EIButtonType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4EIButtonType_EibtZero = 0,

  /** 互动按钮 */
  PB4EIButtonType_EibtSkill = 1,

  /** 聊一聊按钮 */
  PB4EIButtonType_EibtChat = 2,

  /** 撩TA */
  PB4EIButtonType_EibtLiaoTa = 3,

  /** 真心话 */
  PB4EIButtonType_EibtZhenxinhua = 4,

  /**  CP约会 */
  PB4EIButtonType_EibtCpYuehui = 5,
};

GPBEnumDescriptor *PB4EIButtonType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4EIButtonType_IsValidValue(int32_t value);

#pragma mark - Enum PB4VideoPlayerStatus

typedef GPB_ENUM(PB4VideoPlayerStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoPlayerStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoPlayerStatus_VpsZero = 0,

  /** 不在房 */
  PB4VideoPlayerStatus_VpsOutRoom = 1,

  /** 在房 */
  PB4VideoPlayerStatus_VpsInRoom = 2,

  /** 在麦上 */
  PB4VideoPlayerStatus_VpsOnChair = 3,

  /** 在唱歌 */
  PB4VideoPlayerStatus_VpsSinging = 4,
};

GPBEnumDescriptor *PB4VideoPlayerStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoPlayerStatus_IsValidValue(int32_t value);

#pragma mark - Enum PB4VideoCTopType

typedef GPB_ENUM(PB4VideoCTopType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoCTopType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoCTopType_VctZero = 0,

  /** 活动 */
  PB4VideoCTopType_VctActivity = 1,

  /** 同城 */
  PB4VideoCTopType_VctSameCity = 2,

  /** 你关注的人 */
  PB4VideoCTopType_VctFallow = 3,
};

GPBEnumDescriptor *PB4VideoCTopType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoCTopType_IsValidValue(int32_t value);

#pragma mark - Enum PB4VideoRecReason

/** 视频推荐原因 */
typedef GPB_ENUM(PB4VideoRecReason) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoRecReason_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoRecReason_VrrZero = 0,

  /** 附近的人 */
  PB4VideoRecReason_VrrNearby = 1,

  /** 关注的人 */
  PB4VideoRecReason_VrrFocus = 2,

  /** 精选 */
  PB4VideoRecReason_VrrGood = 4,

  /** 运营位置 置顶 */
  PB4VideoRecReason_VrrTop = 3,

  /** 标签内容库 */
  PB4VideoRecReason_VrrLabel = 5,
};

GPBEnumDescriptor *PB4VideoRecReason_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoRecReason_IsValidValue(int32_t value);

#pragma mark - Enum PB4VideoButtonType

typedef GPB_ENUM(PB4VideoButtonType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoButtonType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoButtonType_VbtZero = 0,

  /** 互动 */
  PB4VideoButtonType_VbtInteraction = 1,

  /** 技能点单 */
  PB4VideoButtonType_VbtBill = 2,

  /** 私聊 */
  PB4VideoButtonType_VbtIm = 3,
};

GPBEnumDescriptor *PB4VideoButtonType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoButtonType_IsValidValue(int32_t value);

#pragma mark - Enum PB4VideoOptType

typedef GPB_ENUM(PB4VideoOptType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB4VideoOptType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 占位 */
  PB4VideoOptType_VotZero = 0,

  /** 开始 */
  PB4VideoOptType_VotStart = 1,

  /** 播完了某个视频 */
  PB4VideoOptType_VotComplete = 2,

  /** 停止 */
  PB4VideoOptType_VotStop = 3,

  /** 不感兴趣 */
  PB4VideoOptType_VotUninterested = 4,

  /** 加载完封面 */
  PB4VideoOptType_VotCover = 5,
};

GPBEnumDescriptor *PB4VideoOptType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB4VideoOptType_IsValidValue(int32_t value);

#pragma mark - PB4VideoExtRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PB4VideoExtRoot : GPBRootObject
@end

#pragma mark - PB4VideoReq

typedef GPB_ENUM(PB4VideoReq_FieldNumber) {
  PB4VideoReq_FieldNumber_GetType = 1,
  PB4VideoReq_FieldNumber_LastTrendId = 2,
  PB4VideoReq_FieldNumber_LastIdsArray = 3,
  PB4VideoReq_FieldNumber_LastIndex = 4,
};

@interface PB4VideoReq : GPBMessage

/** 拉取类型 */
@property(nonatomic, readwrite) PB4VideoGetType getType;

/** 最后一条视频动态ID */
@property(nonatomic, readwrite) int64_t lastTrendId;

/** 最后20条视频id列表 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *lastIdsArray;
/** The number of items in @c lastIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger lastIdsArray_Count;

/** 倒数条数请求（5，2，1） */
@property(nonatomic, readwrite) int32_t lastIndex;

@end

/**
 * Fetches the raw value of a @c PB4VideoReq's @c getType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoReq_GetType_RawValue(PB4VideoReq *message);
/**
 * Sets the raw value of an @c PB4VideoReq's @c getType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoReq_GetType_RawValue(PB4VideoReq *message, int32_t value);

#pragma mark - PB4VideoRes

typedef GPB_ENUM(PB4VideoRes_FieldNumber) {
  PB4VideoRes_FieldNumber_InfosArray = 1,
  PB4VideoRes_FieldNumber_PreloadIdxArray = 2,
};

@interface PB4VideoRes : GPBMessage

/** 视频信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB4VideoInfo*> *infosArray;
/** The number of items in @c infosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger infosArray_Count;

/** 预加载位置（倒数） */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *preloadIdxArray;
/** The number of items in @c preloadIdxArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preloadIdxArray_Count;

@end

#pragma mark - PB4VideoInfo

typedef GPB_ENUM(PB4VideoInfo_FieldNumber) {
  PB4VideoInfo_FieldNumber_TrendId = 1,
  PB4VideoInfo_FieldNumber_PlayerId = 2,
  PB4VideoInfo_FieldNumber_Name = 3,
  PB4VideoInfo_FieldNumber_Sex = 4,
  PB4VideoInfo_FieldNumber_Icon = 5,
  PB4VideoInfo_FieldNumber_VideoURL = 6,
  PB4VideoInfo_FieldNumber_LikeNum = 7,
  PB4VideoInfo_FieldNumber_CommentNum = 8,
  PB4VideoInfo_FieldNumber_Content = 9,
  PB4VideoInfo_FieldNumber_TagsArray = 10,
  PB4VideoInfo_FieldNumber_IsGaveLike = 11,
  PB4VideoInfo_FieldNumber_CoverURL = 12,
  PB4VideoInfo_FieldNumber_VideoWidth = 13,
  PB4VideoInfo_FieldNumber_VideoHeight = 14,
  PB4VideoInfo_FieldNumber_SkillId = 15,
  PB4VideoInfo_FieldNumber_IaId = 16,
  PB4VideoInfo_FieldNumber_ActivityId = 17,
  PB4VideoInfo_FieldNumber_SourceId = 18,
  PB4VideoInfo_FieldNumber_From = 19,
  PB4VideoInfo_FieldNumber_Quality = 20,
  PB4VideoInfo_FieldNumber_LabelId = 21,
  PB4VideoInfo_FieldNumber_RecmdSource = 22,
  PB4VideoInfo_FieldNumber_RecmdSourceId = 23,
  PB4VideoInfo_FieldNumber_TraceInfo = 24,
  PB4VideoInfo_FieldNumber_AuthInfoListArray = 25,
};

@interface PB4VideoInfo : GPBMessage

/** 视频ID */
@property(nonatomic, readwrite) int64_t trendId;

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

/** 玩家昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) enum PB4PluginSexType sex;

/** 玩家头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 视频url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *videoURL;

/** 点赞数 */
@property(nonatomic, readwrite) int64_t likeNum;

/** 评论数 */
@property(nonatomic, readwrite) int64_t commentNum;

/** 动态内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 标签 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB4TrendTag*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

/** 是否点过赞 */
@property(nonatomic, readwrite) BOOL isGaveLike;

/** 视频第一帧url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *coverURL;

/** 视频宽 */
@property(nonatomic, readwrite) int32_t videoWidth;

/** 视频高 */
@property(nonatomic, readwrite) int32_t videoHeight;

/** 技能id */
@property(nonatomic, readwrite) int32_t skillId;

/** 互动id */
@property(nonatomic, readwrite) int32_t iaId;

/** 该条视频的活动id，没有则0 */
@property(nonatomic, readwrite) int32_t activityId;

/** 客户端在对这条视频做操作（VideoOptReq）的时候，返回该id */
@property(nonatomic, readwrite) int64_t sourceId;

/** 来源 */
@property(nonatomic, readwrite) int32_t from;

/** 品质 */
@property(nonatomic, readwrite) int32_t quality;

/** 标签ID */
@property(nonatomic, readwrite) int32_t labelId;

/** 视频推荐来源 */
@property(nonatomic, readwrite) enum PB4VideoRecmdSource recmdSource;

/** 算法ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *recmdSourceId;

/** 阿里云推荐详情 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *traceInfo;

/** 认证信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB4PAuthInfo*> *authInfoListArray;
/** The number of items in @c authInfoListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger authInfoListArray_Count;

@end

/**
 * Fetches the raw value of a @c PB4VideoInfo's @c sex property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoInfo_Sex_RawValue(PB4VideoInfo *message);
/**
 * Sets the raw value of an @c PB4VideoInfo's @c sex property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoInfo_Sex_RawValue(PB4VideoInfo *message, int32_t value);

/**
 * Fetches the raw value of a @c PB4VideoInfo's @c recmdSource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoInfo_RecmdSource_RawValue(PB4VideoInfo *message);
/**
 * Sets the raw value of an @c PB4VideoInfo's @c recmdSource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoInfo_RecmdSource_RawValue(PB4VideoInfo *message, int32_t value);

#pragma mark - PB4VideoPlayerReq

typedef GPB_ENUM(PB4VideoPlayerReq_FieldNumber) {
  PB4VideoPlayerReq_FieldNumber_TrendId = 1,
  PB4VideoPlayerReq_FieldNumber_From = 2,
  PB4VideoPlayerReq_FieldNumber_Quality = 3,
  PB4VideoPlayerReq_FieldNumber_LabelId = 4,
};

/**
 * 视频玩家信息
 **/
@interface PB4VideoPlayerReq : GPBMessage

/** 视频ID */
@property(nonatomic, readwrite) int64_t trendId;

/** 来源 */
@property(nonatomic, readwrite) int32_t from;

/** 品质 */
@property(nonatomic, readwrite) int32_t quality;

/** 标签ID */
@property(nonatomic, readwrite) int32_t labelId;

@end

#pragma mark - PB4VideoPlayerRes

typedef GPB_ENUM(PB4VideoPlayerRes_FieldNumber) {
  PB4VideoPlayerRes_FieldNumber_ContentTop = 1,
  PB4VideoPlayerRes_FieldNumber_Button = 2,
  PB4VideoPlayerRes_FieldNumber_Status = 3,
  PB4VideoPlayerRes_FieldNumber_RoomId = 4,
  PB4VideoPlayerRes_FieldNumber_RecReason = 5,
  PB4VideoPlayerRes_FieldNumber_ExtraInfoBtn = 6,
};

@interface PB4VideoPlayerRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PB4VideoContentTop *contentTop;
/** Test to see if @c contentTop has been set. */
@property(nonatomic, readwrite) BOOL hasContentTop;

/** 底部按钮 */
@property(nonatomic, readwrite, strong, null_resettable) PB4VideoButton *button;
/** Test to see if @c button has been set. */
@property(nonatomic, readwrite) BOOL hasButton;

@property(nonatomic, readwrite) PB4VideoPlayerStatus status;

/** 玩家所在房间id */
@property(nonatomic, readwrite) int64_t roomId;

/** 推荐原因 */
@property(nonatomic, readwrite) PB4VideoRecReason recReason;

/** 新按钮 */
@property(nonatomic, readwrite, strong, null_resettable) PB4ExtraInfo *extraInfoBtn;
/** Test to see if @c extraInfoBtn has been set. */
@property(nonatomic, readwrite) BOOL hasExtraInfoBtn;

@end

/**
 * Fetches the raw value of a @c PB4VideoPlayerRes's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoPlayerRes_Status_RawValue(PB4VideoPlayerRes *message);
/**
 * Sets the raw value of an @c PB4VideoPlayerRes's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoPlayerRes_Status_RawValue(PB4VideoPlayerRes *message, int32_t value);

/**
 * Fetches the raw value of a @c PB4VideoPlayerRes's @c recReason property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoPlayerRes_RecReason_RawValue(PB4VideoPlayerRes *message);
/**
 * Sets the raw value of an @c PB4VideoPlayerRes's @c recReason property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoPlayerRes_RecReason_RawValue(PB4VideoPlayerRes *message, int32_t value);

#pragma mark - PB4ExtraInfo

typedef GPB_ENUM(PB4ExtraInfo_FieldNumber) {
  PB4ExtraInfo_FieldNumber_ButtonType = 1,
  PB4ExtraInfo_FieldNumber_ButtonIcon = 2,
  PB4ExtraInfo_FieldNumber_ButtonContent = 3,
  PB4ExtraInfo_FieldNumber_Icon = 4,
  PB4ExtraInfo_FieldNumber_Content = 5,
  PB4ExtraInfo_FieldNumber_OrderNum = 6,
  PB4ExtraInfo_FieldNumber_SkillInfo = 7,
  PB4ExtraInfo_FieldNumber_ExpireTime = 8,
  PB4ExtraInfo_FieldNumber_JumpURL = 9,
  PB4ExtraInfo_FieldNumber_Price = 10,
};

@interface PB4ExtraInfo : GPBMessage

/** 按钮类型 */
@property(nonatomic, readwrite) PB4EIButtonType buttonType;

/** 按钮图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buttonIcon;

/** 按钮内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buttonContent;

/** 图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 接单数量 */
@property(nonatomic, readwrite) int32_t orderNum;

/** 技能介绍 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *skillInfo;

/** 显示倒计时 */
@property(nonatomic, readwrite) int64_t expireTime;

/** 跳转路由 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jumpURL;

/** 价格 */
@property(nonatomic, readwrite) int32_t price;

@end

/**
 * Fetches the raw value of a @c PB4ExtraInfo's @c buttonType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4ExtraInfo_ButtonType_RawValue(PB4ExtraInfo *message);
/**
 * Sets the raw value of an @c PB4ExtraInfo's @c buttonType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4ExtraInfo_ButtonType_RawValue(PB4ExtraInfo *message, int32_t value);

#pragma mark - PB4VideoContentTop

typedef GPB_ENUM(PB4VideoContentTop_FieldNumber) {
  PB4VideoContentTop_FieldNumber_CtType = 1,
  PB4VideoContentTop_FieldNumber_Icon = 2,
  PB4VideoContentTop_FieldNumber_Text = 3,
  PB4VideoContentTop_FieldNumber_JumpURL = 4,
};

@interface PB4VideoContentTop : GPBMessage

/** l类型 */
@property(nonatomic, readwrite) PB4VideoCTopType ctType;

/** icon，可能没有 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 文字，可能为空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

/** 跳转路由，可能为空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jumpURL;

@end

/**
 * Fetches the raw value of a @c PB4VideoContentTop's @c ctType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoContentTop_CtType_RawValue(PB4VideoContentTop *message);
/**
 * Sets the raw value of an @c PB4VideoContentTop's @c ctType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoContentTop_CtType_RawValue(PB4VideoContentTop *message, int32_t value);

#pragma mark - PB4VideoButton

typedef GPB_ENUM(PB4VideoButton_FieldNumber) {
  PB4VideoButton_FieldNumber_Icon = 1,
  PB4VideoButton_FieldNumber_Text = 2,
  PB4VideoButton_FieldNumber_JumpURL = 3,
  PB4VideoButton_FieldNumber_CtType = 4,
  PB4VideoButton_FieldNumber_TypeId = 5,
};

/**
 * 视频底部按钮
 **/
@interface PB4VideoButton : GPBMessage

/** 活动图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

/** 文字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

/** 跳转路由 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jumpURL;

/** 类型 */
@property(nonatomic, readwrite) PB4VideoButtonType ctType;

/** 互动/技能id */
@property(nonatomic, readwrite) int64_t typeId;

@end

/**
 * Fetches the raw value of a @c PB4VideoButton's @c ctType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoButton_CtType_RawValue(PB4VideoButton *message);
/**
 * Sets the raw value of an @c PB4VideoButton's @c ctType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoButton_CtType_RawValue(PB4VideoButton *message, int32_t value);

#pragma mark - PB4VideoLikeReq

typedef GPB_ENUM(PB4VideoLikeReq_FieldNumber) {
  PB4VideoLikeReq_FieldNumber_Page = 1,
};

/**
 * 我喜欢的视频
 **/
@interface PB4VideoLikeReq : GPBMessage

/** 从1开始 */
@property(nonatomic, readwrite) int32_t page;

@end

#pragma mark - PB4VideoLikeRes

typedef GPB_ENUM(PB4VideoLikeRes_FieldNumber) {
  PB4VideoLikeRes_FieldNumber_NextPage = 1,
  PB4VideoLikeRes_FieldNumber_InfosArray = 2,
};

@interface PB4VideoLikeRes : GPBMessage

/** 下一页页码，如果没有下一页，则为-1 */
@property(nonatomic, readwrite) int32_t nextPage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB4VideoInfo*> *infosArray;
/** The number of items in @c infosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger infosArray_Count;

@end

#pragma mark - PB4VideoOptReq

typedef GPB_ENUM(PB4VideoOptReq_FieldNumber) {
  PB4VideoOptReq_FieldNumber_OptType = 1,
  PB4VideoOptReq_FieldNumber_TrendId = 2,
  PB4VideoOptReq_FieldNumber_Second = 3,
  PB4VideoOptReq_FieldNumber_LeftNum = 4,
  PB4VideoOptReq_FieldNumber_SourceId = 5,
  PB4VideoOptReq_FieldNumber_RecmdSource = 6,
  PB4VideoOptReq_FieldNumber_RecmdSourceId = 7,
  PB4VideoOptReq_FieldNumber_TraceInfo = 8,
  PB4VideoOptReq_FieldNumber_FirstPlay = 9,
};

/**
 * 用户播放、结束播放视频
 **/
@interface PB4VideoOptReq : GPBMessage

@property(nonatomic, readwrite) PB4VideoOptType optType;

@property(nonatomic, readwrite) int64_t trendId;

/** 视频剩余秒数 */
@property(nonatomic, readwrite) int64_t second;

/** 客户端本地还剩下多少个视频没有划过 */
@property(nonatomic, readwrite) int32_t leftNum;

/** VideoInfo 里的 source_id */
@property(nonatomic, readwrite) int64_t sourceId;

/** 视频推荐来源 */
@property(nonatomic, readwrite) enum PB4VideoRecmdSource recmdSource;

/** 算法ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *recmdSourceId;

/** 阿里云推荐详情 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *traceInfo;

/** 首次完播 */
@property(nonatomic, readwrite) BOOL firstPlay;

@end

/**
 * Fetches the raw value of a @c PB4VideoOptReq's @c optType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoOptReq_OptType_RawValue(PB4VideoOptReq *message);
/**
 * Sets the raw value of an @c PB4VideoOptReq's @c optType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoOptReq_OptType_RawValue(PB4VideoOptReq *message, int32_t value);

/**
 * Fetches the raw value of a @c PB4VideoOptReq's @c recmdSource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoOptReq_RecmdSource_RawValue(PB4VideoOptReq *message);
/**
 * Sets the raw value of an @c PB4VideoOptReq's @c recmdSource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoOptReq_RecmdSource_RawValue(PB4VideoOptReq *message, int32_t value);

#pragma mark - PB4VideoOptRes

@interface PB4VideoOptRes : GPBMessage

@end

#pragma mark - PB4VideoButtonReportReq

typedef GPB_ENUM(PB4VideoButtonReportReq_FieldNumber) {
  PB4VideoButtonReportReq_FieldNumber_Btn = 1,
  PB4VideoButtonReportReq_FieldNumber_TrendId = 2,
};

@interface PB4VideoButtonReportReq : GPBMessage

/** 按钮类型 */
@property(nonatomic, readwrite) PB4EIButtonType btn;

/** 视频ID */
@property(nonatomic, readwrite) int64_t trendId;

@end

/**
 * Fetches the raw value of a @c PB4VideoButtonReportReq's @c btn property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB4VideoButtonReportReq_Btn_RawValue(PB4VideoButtonReportReq *message);
/**
 * Sets the raw value of an @c PB4VideoButtonReportReq's @c btn property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB4VideoButtonReportReq_Btn_RawValue(PB4VideoButtonReportReq *message, int32_t value);

#pragma mark - PB4VideoButtonReportRes

@interface PB4VideoButtonReportRes : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
