// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/common.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PROTOImageInfo;
@class PROTOSceneID;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PROTOSexType

typedef GPB_ENUM(PROTOSexType) {
  PROTOSexType_Unknown = 0,
  PROTOSexType_Mail = 1,
  PROTOSexType_Femail = 2,
};

GPBEnumDescriptor *PROTOSexType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PROTOSexType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOSceneType

typedef GPB_ENUM(PROTOSceneType) {
  PROTOSceneType_StHome = 1,
};

GPBEnumDescriptor *PROTOSceneType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PROTOSceneType_IsValidValue(int32_t value);

#pragma mark - Enum PROTOOnlineStateType

typedef GPB_ENUM(PROTOOnlineStateType) {
  PROTOOnlineStateType_OstOffline = 0,
  PROTOOnlineStateType_OstDisconnected = 20,
  PROTOOnlineStateType_OstBackground = 80,
  PROTOOnlineStateType_OstOnline = 100,
};

GPBEnumDescriptor *PROTOOnlineStateType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PROTOOnlineStateType_IsValidValue(int32_t value);

#pragma mark - PROTOCommonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PROTOCommonRoot : GPBRootObject
@end

#pragma mark - PROTOIntegerVO

typedef GPB_ENUM(PROTOIntegerVO_FieldNumber) {
  PROTOIntegerVO_FieldNumber_Value = 1,
};

@interface PROTOIntegerVO : GPBMessage

@property(nonatomic, readwrite) int32_t value;

@property(nonatomic, readwrite) BOOL hasValue;
@end

#pragma mark - PROTOIntString

typedef GPB_ENUM(PROTOIntString_FieldNumber) {
  PROTOIntString_FieldNumber_Key = 1,
  PROTOIntString_FieldNumber_Value = 2,
};

@interface PROTOIntString : GPBMessage

@property(nonatomic, readwrite) int32_t key;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

#pragma mark - PROTOLongInt

typedef GPB_ENUM(PROTOLongInt_FieldNumber) {
  PROTOLongInt_FieldNumber_Key = 1,
  PROTOLongInt_FieldNumber_Value = 2,
};

@interface PROTOLongInt : GPBMessage

@property(nonatomic, readwrite) int64_t key;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite) int32_t value;

@property(nonatomic, readwrite) BOOL hasValue;
@end

#pragma mark - PROTOSceneID

typedef GPB_ENUM(PROTOSceneID_FieldNumber) {
  PROTOSceneID_FieldNumber_Type = 1,
  PROTOSceneID_FieldNumber_Seq = 2,
};

@interface PROTOSceneID : GPBMessage

@property(nonatomic, readwrite) PROTOSceneType type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) int64_t seq;

@property(nonatomic, readwrite) BOOL hasSeq;
@end

#pragma mark - PROTOImageInfo

typedef GPB_ENUM(PROTOImageInfo_FieldNumber) {
  PROTOImageInfo_FieldNumber_Id_p = 1,
  PROTOImageInfo_FieldNumber_Width = 2,
  PROTOImageInfo_FieldNumber_Height = 3,
  PROTOImageInfo_FieldNumber_IsVideo = 4,
};

@interface PROTOImageInfo : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite) uint32_t width;

@property(nonatomic, readwrite) BOOL hasWidth;
@property(nonatomic, readwrite) uint32_t height;

@property(nonatomic, readwrite) BOOL hasHeight;
@property(nonatomic, readwrite) BOOL isVideo;

@property(nonatomic, readwrite) BOOL hasIsVideo;
@end

#pragma mark - PROTOImageInfoList

typedef GPB_ENUM(PROTOImageInfoList_FieldNumber) {
  PROTOImageInfoList_FieldNumber_PicsArray = 1,
};

@interface PROTOImageInfoList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PROTOImageInfo*> *picsArray;
/** The number of items in @c picsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger picsArray_Count;

@end

#pragma mark - PROTOSearchPlayerEntry

typedef GPB_ENUM(PROTOSearchPlayerEntry_FieldNumber) {
  PROTOSearchPlayerEntry_FieldNumber_Id_p = 1,
  PROTOSearchPlayerEntry_FieldNumber_Id2 = 2,
  PROTOSearchPlayerEntry_FieldNumber_Nickname = 3,
  PROTOSearchPlayerEntry_FieldNumber_Sex = 4,
  PROTOSearchPlayerEntry_FieldNumber_Icon = 5,
  PROTOSearchPlayerEntry_FieldNumber_Charm = 6,
  PROTOSearchPlayerEntry_FieldNumber_CharmLevel = 7,
  PROTOSearchPlayerEntry_FieldNumber_Wealth = 8,
  PROTOSearchPlayerEntry_FieldNumber_WealthLevel = 9,
  PROTOSearchPlayerEntry_FieldNumber_Online = 10,
  PROTOSearchPlayerEntry_FieldNumber_SceneId = 11,
  PROTOSearchPlayerEntry_FieldNumber_HasPasswd = 13,
};

@interface PROTOSearchPlayerEntry : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite) int64_t id2;

@property(nonatomic, readwrite) BOOL hasId2;
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;
/** Test to see if @c nickname has been set. */
@property(nonatomic, readwrite) BOOL hasNickname;

@property(nonatomic, readwrite) PROTOSexType sex;

@property(nonatomic, readwrite) BOOL hasSex;
@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;
/** Test to see if @c icon has been set. */
@property(nonatomic, readwrite) BOOL hasIcon;

@property(nonatomic, readwrite) int64_t charm;

@property(nonatomic, readwrite) BOOL hasCharm;
@property(nonatomic, readwrite) int32_t charmLevel;

@property(nonatomic, readwrite) BOOL hasCharmLevel;
@property(nonatomic, readwrite) int32_t wealth;

@property(nonatomic, readwrite) BOOL hasWealth;
@property(nonatomic, readwrite) int32_t wealthLevel;

@property(nonatomic, readwrite) BOOL hasWealthLevel;
@property(nonatomic, readwrite) BOOL online;

@property(nonatomic, readwrite) BOOL hasOnline;
@property(nonatomic, readwrite, strong, null_resettable) PROTOSceneID *sceneId;
/** Test to see if @c sceneId has been set. */
@property(nonatomic, readwrite) BOOL hasSceneId;

@property(nonatomic, readwrite) BOOL hasPasswd;

@property(nonatomic, readwrite) BOOL hasHasPasswd;
@end

#pragma mark - PROTOTaskGiftStep

typedef GPB_ENUM(PROTOTaskGiftStep_FieldNumber) {
  PROTOTaskGiftStep_FieldNumber_Id_p = 1,
  PROTOTaskGiftStep_FieldNumber_TaskId = 2,
  PROTOTaskGiftStep_FieldNumber_Step = 3,
  PROTOTaskGiftStep_FieldNumber_GiftId = 4,
  PROTOTaskGiftStep_FieldNumber_GiftNum = 5,
  PROTOTaskGiftStep_FieldNumber_RoomPoint = 6,
  PROTOTaskGiftStep_FieldNumber_PlayerPoint = 7,
};

@interface PROTOTaskGiftStep : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite) int64_t taskId;

@property(nonatomic, readwrite) BOOL hasTaskId;
@property(nonatomic, readwrite) uint32_t step;

@property(nonatomic, readwrite) BOOL hasStep;
@property(nonatomic, readwrite) uint32_t giftId;

@property(nonatomic, readwrite) BOOL hasGiftId;
@property(nonatomic, readwrite) uint32_t giftNum;

@property(nonatomic, readwrite) BOOL hasGiftNum;
@property(nonatomic, readwrite) uint32_t roomPoint;

@property(nonatomic, readwrite) BOOL hasRoomPoint;
@property(nonatomic, readwrite) uint32_t playerPoint;

@property(nonatomic, readwrite) BOOL hasPlayerPoint;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
